// Code generated by ent, DO NOT EDIT.

package attempt

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the attempt type in the database.
	Label = "attempt"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGoalID holds the string denoting the goal_id field in the database.
	FieldGoalID = "goal_id"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// FieldWorkerID holds the string denoting the worker_id field in the database.
	FieldWorkerID = "worker_id"
	// FieldPhase holds the string denoting the phase field in the database.
	FieldPhase = "phase"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldOutcome holds the string denoting the outcome field in the database.
	FieldOutcome = "outcome"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldStoppedAt holds the string denoting the stopped_at field in the database.
	FieldStoppedAt = "stopped_at"
	// FieldDurationMs holds the string denoting the duration_ms field in the database.
	FieldDurationMs = "duration_ms"
	// Table holds the table name of the attempt in the database.
	Table = "attempts"
)

// Columns holds all SQL columns for attempt fields.
var Columns = []string{
	FieldID,
	FieldGoalID,
	FieldSessionID,
	FieldWorkerID,
	FieldPhase,
	FieldState,
	FieldOutcome,
	FieldStartedAt,
	FieldStoppedAt,
	FieldDurationMs,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the Attempt queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByGoalID orders the results by the goal_id field.
func ByGoalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGoalID, opts...).ToFunc()
}

// BySessionID orders the results by the session_id field.
func BySessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionID, opts...).ToFunc()
}

// ByWorkerID orders the results by the worker_id field.
func ByWorkerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkerID, opts...).ToFunc()
}

// ByPhase orders the results by the phase field.
func ByPhase(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhase, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByOutcome orders the results by the outcome field.
func ByOutcome(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutcome, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByStoppedAt orders the results by the stopped_at field.
func ByStoppedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStoppedAt, opts...).ToFunc()
}

// ByDurationMs orders the results by the duration_ms field.
func ByDurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationMs, opts...).ToFunc()
}
