// Code generated by ent, DO NOT EDIT.

package workflowsteprun

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/piglor/loom/services/loom/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldContainsFold(FieldID, id))
}

// RunID applies equality check predicate on the "run_id" field. It's identical to RunIDEQ.
func RunID(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldEQ(FieldRunID, v))
}

// StepKey applies equality check predicate on the "step_key" field. It's identical to StepKeyEQ.
func StepKey(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldEQ(FieldStepKey, v))
}

// StepType applies equality check predicate on the "step_type" field. It's identical to StepTypeEQ.
func StepType(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldEQ(FieldStepType, v))
}

// Position applies equality check predicate on the "position" field. It's identical to PositionEQ.
func Position(v int) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldEQ(FieldPosition, v))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldEQ(FieldState, v))
}

// Attempt applies equality check predicate on the "attempt" field. It's identical to AttemptEQ.
func Attempt(v int) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldEQ(FieldAttempt, v))
}

// ErrorCode applies equality check predicate on the "error_code" field. It's identical to ErrorCodeEQ.
func ErrorCode(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldEQ(FieldErrorCode, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldEQ(FieldStartedAt, v))
}

// EndedAt applies equality check predicate on the "ended_at" field. It's identical to EndedAtEQ.
func EndedAt(v time.Time) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldEQ(FieldEndedAt, v))
}

// RunIDEQ applies the EQ predicate on the "run_id" field.
func RunIDEQ(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldEQ(FieldRunID, v))
}

// RunIDNEQ applies the NEQ predicate on the "run_id" field.
func RunIDNEQ(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldNEQ(FieldRunID, v))
}

// RunIDIn applies the In predicate on the "run_id" field.
func RunIDIn(vs ...string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldIn(FieldRunID, vs...))
}

// RunIDNotIn applies the NotIn predicate on the "run_id" field.
func RunIDNotIn(vs ...string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldNotIn(FieldRunID, vs...))
}

// RunIDGT applies the GT predicate on the "run_id" field.
func RunIDGT(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldGT(FieldRunID, v))
}

// RunIDGTE applies the GTE predicate on the "run_id" field.
func RunIDGTE(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldGTE(FieldRunID, v))
}

// RunIDLT applies the LT predicate on the "run_id" field.
func RunIDLT(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldLT(FieldRunID, v))
}

// RunIDLTE applies the LTE predicate on the "run_id" field.
func RunIDLTE(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldLTE(FieldRunID, v))
}

// RunIDContains applies the Contains predicate on the "run_id" field.
func RunIDContains(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldContains(FieldRunID, v))
}

// RunIDHasPrefix applies the HasPrefix predicate on the "run_id" field.
func RunIDHasPrefix(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldHasPrefix(FieldRunID, v))
}

// RunIDHasSuffix applies the HasSuffix predicate on the "run_id" field.
func RunIDHasSuffix(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldHasSuffix(FieldRunID, v))
}

// RunIDEqualFold applies the EqualFold predicate on the "run_id" field.
func RunIDEqualFold(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldEqualFold(FieldRunID, v))
}

// RunIDContainsFold applies the ContainsFold predicate on the "run_id" field.
func RunIDContainsFold(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldContainsFold(FieldRunID, v))
}

// StepKeyEQ applies the EQ predicate on the "step_key" field.
func StepKeyEQ(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldEQ(FieldStepKey, v))
}

// StepKeyNEQ applies the NEQ predicate on the "step_key" field.
func StepKeyNEQ(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldNEQ(FieldStepKey, v))
}

// StepKeyIn applies the In predicate on the "step_key" field.
func StepKeyIn(vs ...string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldIn(FieldStepKey, vs...))
}

// StepKeyNotIn applies the NotIn predicate on the "step_key" field.
func StepKeyNotIn(vs ...string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldNotIn(FieldStepKey, vs...))
}

// StepKeyGT applies the GT predicate on the "step_key" field.
func StepKeyGT(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldGT(FieldStepKey, v))
}

// StepKeyGTE applies the GTE predicate on the "step_key" field.
func StepKeyGTE(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldGTE(FieldStepKey, v))
}

// StepKeyLT applies the LT predicate on the "step_key" field.
func StepKeyLT(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldLT(FieldStepKey, v))
}

// StepKeyLTE applies the LTE predicate on the "step_key" field.
func StepKeyLTE(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldLTE(FieldStepKey, v))
}

// StepKeyContains applies the Contains predicate on the "step_key" field.
func StepKeyContains(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldContains(FieldStepKey, v))
}

// StepKeyHasPrefix applies the HasPrefix predicate on the "step_key" field.
func StepKeyHasPrefix(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldHasPrefix(FieldStepKey, v))
}

// StepKeyHasSuffix applies the HasSuffix predicate on the "step_key" field.
func StepKeyHasSuffix(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldHasSuffix(FieldStepKey, v))
}

// StepKeyEqualFold applies the EqualFold predicate on the "step_key" field.
func StepKeyEqualFold(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldEqualFold(FieldStepKey, v))
}

// StepKeyContainsFold applies the ContainsFold predicate on the "step_key" field.
func StepKeyContainsFold(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldContainsFold(FieldStepKey, v))
}

// StepTypeEQ applies the EQ predicate on the "step_type" field.
func StepTypeEQ(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldEQ(FieldStepType, v))
}

// StepTypeNEQ applies the NEQ predicate on the "step_type" field.
func StepTypeNEQ(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldNEQ(FieldStepType, v))
}

// StepTypeIn applies the In predicate on the "step_type" field.
func StepTypeIn(vs ...string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldIn(FieldStepType, vs...))
}

// StepTypeNotIn applies the NotIn predicate on the "step_type" field.
func StepTypeNotIn(vs ...string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldNotIn(FieldStepType, vs...))
}

// StepTypeGT applies the GT predicate on the "step_type" field.
func StepTypeGT(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldGT(FieldStepType, v))
}

// StepTypeGTE applies the GTE predicate on the "step_type" field.
func StepTypeGTE(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldGTE(FieldStepType, v))
}

// StepTypeLT applies the LT predicate on the "step_type" field.
func StepTypeLT(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldLT(FieldStepType, v))
}

// StepTypeLTE applies the LTE predicate on the "step_type" field.
func StepTypeLTE(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldLTE(FieldStepType, v))
}

// StepTypeContains applies the Contains predicate on the "step_type" field.
func StepTypeContains(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldContains(FieldStepType, v))
}

// StepTypeHasPrefix applies the HasPrefix predicate on the "step_type" field.
func StepTypeHasPrefix(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldHasPrefix(FieldStepType, v))
}

// StepTypeHasSuffix applies the HasSuffix predicate on the "step_type" field.
func StepTypeHasSuffix(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldHasSuffix(FieldStepType, v))
}

// StepTypeEqualFold applies the EqualFold predicate on the "step_type" field.
func StepTypeEqualFold(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldEqualFold(FieldStepType, v))
}

// StepTypeContainsFold applies the ContainsFold predicate on the "step_type" field.
func StepTypeContainsFold(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldContainsFold(FieldStepType, v))
}

// PositionEQ applies the EQ predicate on the "position" field.
func PositionEQ(v int) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldEQ(FieldPosition, v))
}

// PositionNEQ applies the NEQ predicate on the "position" field.
func PositionNEQ(v int) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldNEQ(FieldPosition, v))
}

// PositionIn applies the In predicate on the "position" field.
func PositionIn(vs ...int) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldIn(FieldPosition, vs...))
}

// PositionNotIn applies the NotIn predicate on the "position" field.
func PositionNotIn(vs ...int) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldNotIn(FieldPosition, vs...))
}

// PositionGT applies the GT predicate on the "position" field.
func PositionGT(v int) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldGT(FieldPosition, v))
}

// PositionGTE applies the GTE predicate on the "position" field.
func PositionGTE(v int) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldGTE(FieldPosition, v))
}

// PositionLT applies the LT predicate on the "position" field.
func PositionLT(v int) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldLT(FieldPosition, v))
}

// PositionLTE applies the LTE predicate on the "position" field.
func PositionLTE(v int) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldLTE(FieldPosition, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldNotIn(FieldState, vs...))
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldGT(FieldState, v))
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldGTE(FieldState, v))
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldLT(FieldState, v))
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldLTE(FieldState, v))
}

// StateContains applies the Contains predicate on the "state" field.
func StateContains(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldContains(FieldState, v))
}

// StateHasPrefix applies the HasPrefix predicate on the "state" field.
func StateHasPrefix(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldHasPrefix(FieldState, v))
}

// StateHasSuffix applies the HasSuffix predicate on the "state" field.
func StateHasSuffix(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldHasSuffix(FieldState, v))
}

// StateEqualFold applies the EqualFold predicate on the "state" field.
func StateEqualFold(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldEqualFold(FieldState, v))
}

// StateContainsFold applies the ContainsFold predicate on the "state" field.
func StateContainsFold(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldContainsFold(FieldState, v))
}

// AttemptEQ applies the EQ predicate on the "attempt" field.
func AttemptEQ(v int) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldEQ(FieldAttempt, v))
}

// AttemptNEQ applies the NEQ predicate on the "attempt" field.
func AttemptNEQ(v int) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldNEQ(FieldAttempt, v))
}

// AttemptIn applies the In predicate on the "attempt" field.
func AttemptIn(vs ...int) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldIn(FieldAttempt, vs...))
}

// AttemptNotIn applies the NotIn predicate on the "attempt" field.
func AttemptNotIn(vs ...int) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldNotIn(FieldAttempt, vs...))
}

// AttemptGT applies the GT predicate on the "attempt" field.
func AttemptGT(v int) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldGT(FieldAttempt, v))
}

// AttemptGTE applies the GTE predicate on the "attempt" field.
func AttemptGTE(v int) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldGTE(FieldAttempt, v))
}

// AttemptLT applies the LT predicate on the "attempt" field.
func AttemptLT(v int) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldLT(FieldAttempt, v))
}

// AttemptLTE applies the LTE predicate on the "attempt" field.
func AttemptLTE(v int) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldLTE(FieldAttempt, v))
}

// InputIsNil applies the IsNil predicate on the "input" field.
func InputIsNil() predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldIsNull(FieldInput))
}

// InputNotNil applies the NotNil predicate on the "input" field.
func InputNotNil() predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldNotNull(FieldInput))
}

// OutputIsNil applies the IsNil predicate on the "output" field.
func OutputIsNil() predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldIsNull(FieldOutput))
}

// OutputNotNil applies the NotNil predicate on the "output" field.
func OutputNotNil() predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldNotNull(FieldOutput))
}

// ErrorCodeEQ applies the EQ predicate on the "error_code" field.
func ErrorCodeEQ(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorCodeNEQ applies the NEQ predicate on the "error_code" field.
func ErrorCodeNEQ(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldNEQ(FieldErrorCode, v))
}

// ErrorCodeIn applies the In predicate on the "error_code" field.
func ErrorCodeIn(vs ...string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldIn(FieldErrorCode, vs...))
}

// ErrorCodeNotIn applies the NotIn predicate on the "error_code" field.
func ErrorCodeNotIn(vs ...string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldNotIn(FieldErrorCode, vs...))
}

// ErrorCodeGT applies the GT predicate on the "error_code" field.
func ErrorCodeGT(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldGT(FieldErrorCode, v))
}

// ErrorCodeGTE applies the GTE predicate on the "error_code" field.
func ErrorCodeGTE(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldGTE(FieldErrorCode, v))
}

// ErrorCodeLT applies the LT predicate on the "error_code" field.
func ErrorCodeLT(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldLT(FieldErrorCode, v))
}

// ErrorCodeLTE applies the LTE predicate on the "error_code" field.
func ErrorCodeLTE(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldLTE(FieldErrorCode, v))
}

// ErrorCodeContains applies the Contains predicate on the "error_code" field.
func ErrorCodeContains(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldContains(FieldErrorCode, v))
}

// ErrorCodeHasPrefix applies the HasPrefix predicate on the "error_code" field.
func ErrorCodeHasPrefix(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldHasPrefix(FieldErrorCode, v))
}

// ErrorCodeHasSuffix applies the HasSuffix predicate on the "error_code" field.
func ErrorCodeHasSuffix(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldHasSuffix(FieldErrorCode, v))
}

// ErrorCodeIsNil applies the IsNil predicate on the "error_code" field.
func ErrorCodeIsNil() predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldIsNull(FieldErrorCode))
}

// ErrorCodeNotNil applies the NotNil predicate on the "error_code" field.
func ErrorCodeNotNil() predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldNotNull(FieldErrorCode))
}

// ErrorCodeEqualFold applies the EqualFold predicate on the "error_code" field.
func ErrorCodeEqualFold(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldEqualFold(FieldErrorCode, v))
}

// ErrorCodeContainsFold applies the ContainsFold predicate on the "error_code" field.
func ErrorCodeContainsFold(v string) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldContainsFold(FieldErrorCode, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldNotNull(FieldStartedAt))
}

// EndedAtEQ applies the EQ predicate on the "ended_at" field.
func EndedAtEQ(v time.Time) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldEQ(FieldEndedAt, v))
}

// EndedAtNEQ applies the NEQ predicate on the "ended_at" field.
func EndedAtNEQ(v time.Time) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldNEQ(FieldEndedAt, v))
}

// EndedAtIn applies the In predicate on the "ended_at" field.
func EndedAtIn(vs ...time.Time) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldIn(FieldEndedAt, vs...))
}

// EndedAtNotIn applies the NotIn predicate on the "ended_at" field.
func EndedAtNotIn(vs ...time.Time) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldNotIn(FieldEndedAt, vs...))
}

// EndedAtGT applies the GT predicate on the "ended_at" field.
func EndedAtGT(v time.Time) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldGT(FieldEndedAt, v))
}

// EndedAtGTE applies the GTE predicate on the "ended_at" field.
func EndedAtGTE(v time.Time) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldGTE(FieldEndedAt, v))
}

// EndedAtLT applies the LT predicate on the "ended_at" field.
func EndedAtLT(v time.Time) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldLT(FieldEndedAt, v))
}

// EndedAtLTE applies the LTE predicate on the "ended_at" field.
func EndedAtLTE(v time.Time) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldLTE(FieldEndedAt, v))
}

// EndedAtIsNil applies the IsNil predicate on the "ended_at" field.
func EndedAtIsNil() predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldIsNull(FieldEndedAt))
}

// EndedAtNotNil applies the NotNil predicate on the "ended_at" field.
func EndedAtNotNil() predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.FieldNotNull(FieldEndedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WorkflowStepRun) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WorkflowStepRun) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WorkflowStepRun) predicate.WorkflowStepRun {
	return predicate.WorkflowStepRun(sql.NotPredicates(p))
}
