// Code generated by ent, DO NOT EDIT.

package integrationcredential

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/piglor/loom/services/loom/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldContainsFold(FieldID, id))
}

// Organization applies equality check predicate on the "organization" field. It's identical to OrganizationEQ.
func Organization(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldEQ(FieldOrganization, v))
}

// PluginID applies equality check predicate on the "plugin_id" field. It's identical to PluginIDEQ.
func PluginID(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldEQ(FieldPluginID, v))
}

// SecretReference applies equality check predicate on the "secret_reference" field. It's identical to SecretReferenceEQ.
func SecretReference(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldEQ(FieldSecretReference, v))
}

// SecretVersion applies equality check predicate on the "secret_version" field. It's identical to SecretVersionEQ.
func SecretVersion(v int) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldEQ(FieldSecretVersion, v))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldEQ(FieldState, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldEQ(FieldUpdatedAt, v))
}

// OrganizationEQ applies the EQ predicate on the "organization" field.
func OrganizationEQ(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldEQ(FieldOrganization, v))
}

// OrganizationNEQ applies the NEQ predicate on the "organization" field.
func OrganizationNEQ(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldNEQ(FieldOrganization, v))
}

// OrganizationIn applies the In predicate on the "organization" field.
func OrganizationIn(vs ...string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldIn(FieldOrganization, vs...))
}

// OrganizationNotIn applies the NotIn predicate on the "organization" field.
func OrganizationNotIn(vs ...string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldNotIn(FieldOrganization, vs...))
}

// OrganizationGT applies the GT predicate on the "organization" field.
func OrganizationGT(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldGT(FieldOrganization, v))
}

// OrganizationGTE applies the GTE predicate on the "organization" field.
func OrganizationGTE(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldGTE(FieldOrganization, v))
}

// OrganizationLT applies the LT predicate on the "organization" field.
func OrganizationLT(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldLT(FieldOrganization, v))
}

// OrganizationLTE applies the LTE predicate on the "organization" field.
func OrganizationLTE(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldLTE(FieldOrganization, v))
}

// OrganizationContains applies the Contains predicate on the "organization" field.
func OrganizationContains(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldContains(FieldOrganization, v))
}

// OrganizationHasPrefix applies the HasPrefix predicate on the "organization" field.
func OrganizationHasPrefix(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldHasPrefix(FieldOrganization, v))
}

// OrganizationHasSuffix applies the HasSuffix predicate on the "organization" field.
func OrganizationHasSuffix(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldHasSuffix(FieldOrganization, v))
}

// OrganizationEqualFold applies the EqualFold predicate on the "organization" field.
func OrganizationEqualFold(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldEqualFold(FieldOrganization, v))
}

// OrganizationContainsFold applies the ContainsFold predicate on the "organization" field.
func OrganizationContainsFold(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldContainsFold(FieldOrganization, v))
}

// PluginIDEQ applies the EQ predicate on the "plugin_id" field.
func PluginIDEQ(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldEQ(FieldPluginID, v))
}

// PluginIDNEQ applies the NEQ predicate on the "plugin_id" field.
func PluginIDNEQ(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldNEQ(FieldPluginID, v))
}

// PluginIDIn applies the In predicate on the "plugin_id" field.
func PluginIDIn(vs ...string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldIn(FieldPluginID, vs...))
}

// PluginIDNotIn applies the NotIn predicate on the "plugin_id" field.
func PluginIDNotIn(vs ...string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldNotIn(FieldPluginID, vs...))
}

// PluginIDGT applies the GT predicate on the "plugin_id" field.
func PluginIDGT(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldGT(FieldPluginID, v))
}

// PluginIDGTE applies the GTE predicate on the "plugin_id" field.
func PluginIDGTE(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldGTE(FieldPluginID, v))
}

// PluginIDLT applies the LT predicate on the "plugin_id" field.
func PluginIDLT(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldLT(FieldPluginID, v))
}

// PluginIDLTE applies the LTE predicate on the "plugin_id" field.
func PluginIDLTE(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldLTE(FieldPluginID, v))
}

// PluginIDContains applies the Contains predicate on the "plugin_id" field.
func PluginIDContains(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldContains(FieldPluginID, v))
}

// PluginIDHasPrefix applies the HasPrefix predicate on the "plugin_id" field.
func PluginIDHasPrefix(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldHasPrefix(FieldPluginID, v))
}

// PluginIDHasSuffix applies the HasSuffix predicate on the "plugin_id" field.
func PluginIDHasSuffix(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldHasSuffix(FieldPluginID, v))
}

// PluginIDEqualFold applies the EqualFold predicate on the "plugin_id" field.
func PluginIDEqualFold(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldEqualFold(FieldPluginID, v))
}

// PluginIDContainsFold applies the ContainsFold predicate on the "plugin_id" field.
func PluginIDContainsFold(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldContainsFold(FieldPluginID, v))
}

// LabelEQ applies the EQ predicate on the "label" field.
func LabelEQ(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldEQ(FieldLabel, v))
}

// LabelNEQ applies the NEQ predicate on the "label" field.
func LabelNEQ(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldNEQ(FieldLabel, v))
}

// LabelIn applies the In predicate on the "label" field.
func LabelIn(vs ...string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldIn(FieldLabel, vs...))
}

// LabelNotIn applies the NotIn predicate on the "label" field.
func LabelNotIn(vs ...string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldNotIn(FieldLabel, vs...))
}

// LabelGT applies the GT predicate on the "label" field.
func LabelGT(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldGT(FieldLabel, v))
}

// LabelGTE applies the GTE predicate on the "label" field.
func LabelGTE(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldGTE(FieldLabel, v))
}

// LabelLT applies the LT predicate on the "label" field.
func LabelLT(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldLT(FieldLabel, v))
}

// LabelLTE applies the LTE predicate on the "label" field.
func LabelLTE(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldLTE(FieldLabel, v))
}

// LabelContains applies the Contains predicate on the "label" field.
func LabelContains(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldContains(FieldLabel, v))
}

// LabelHasPrefix applies the HasPrefix predicate on the "label" field.
func LabelHasPrefix(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldHasPrefix(FieldLabel, v))
}

// LabelHasSuffix applies the HasSuffix predicate on the "label" field.
func LabelHasSuffix(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldHasSuffix(FieldLabel, v))
}

// LabelEqualFold applies the EqualFold predicate on the "label" field.
func LabelEqualFold(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldEqualFold(FieldLabel, v))
}

// LabelContainsFold applies the ContainsFold predicate on the "label" field.
func LabelContainsFold(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldContainsFold(FieldLabel, v))
}

// SecretReferenceEQ applies the EQ predicate on the "secret_reference" field.
func SecretReferenceEQ(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldEQ(FieldSecretReference, v))
}

// SecretReferenceNEQ applies the NEQ predicate on the "secret_reference" field.
func SecretReferenceNEQ(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldNEQ(FieldSecretReference, v))
}

// SecretReferenceIn applies the In predicate on the "secret_reference" field.
func SecretReferenceIn(vs ...string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldIn(FieldSecretReference, vs...))
}

// SecretReferenceNotIn applies the NotIn predicate on the "secret_reference" field.
func SecretReferenceNotIn(vs ...string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldNotIn(FieldSecretReference, vs...))
}

// SecretReferenceGT applies the GT predicate on the "secret_reference" field.
func SecretReferenceGT(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldGT(FieldSecretReference, v))
}

// SecretReferenceGTE applies the GTE predicate on the "secret_reference" field.
func SecretReferenceGTE(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldGTE(FieldSecretReference, v))
}

// SecretReferenceLT applies the LT predicate on the "secret_reference" field.
func SecretReferenceLT(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldLT(FieldSecretReference, v))
}

// SecretReferenceLTE applies the LTE predicate on the "secret_reference" field.
func SecretReferenceLTE(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldLTE(FieldSecretReference, v))
}

// SecretReferenceContains applies the Contains predicate on the "secret_reference" field.
func SecretReferenceContains(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldContains(FieldSecretReference, v))
}

// SecretReferenceHasPrefix applies the HasPrefix predicate on the "secret_reference" field.
func SecretReferenceHasPrefix(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldHasPrefix(FieldSecretReference, v))
}

// SecretReferenceHasSuffix applies the HasSuffix predicate on the "secret_reference" field.
func SecretReferenceHasSuffix(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldHasSuffix(FieldSecretReference, v))
}

// SecretReferenceEqualFold applies the EqualFold predicate on the "secret_reference" field.
func SecretReferenceEqualFold(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldEqualFold(FieldSecretReference, v))
}

// SecretReferenceContainsFold applies the ContainsFold predicate on the "secret_reference" field.
func SecretReferenceContainsFold(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldContainsFold(FieldSecretReference, v))
}

// SecretVersionEQ applies the EQ predicate on the "secret_version" field.
func SecretVersionEQ(v int) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldEQ(FieldSecretVersion, v))
}

// SecretVersionNEQ applies the NEQ predicate on the "secret_version" field.
func SecretVersionNEQ(v int) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldNEQ(FieldSecretVersion, v))
}

// SecretVersionIn applies the In predicate on the "secret_version" field.
func SecretVersionIn(vs ...int) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldIn(FieldSecretVersion, vs...))
}

// SecretVersionNotIn applies the NotIn predicate on the "secret_version" field.
func SecretVersionNotIn(vs ...int) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldNotIn(FieldSecretVersion, vs...))
}

// SecretVersionGT applies the GT predicate on the "secret_version" field.
func SecretVersionGT(v int) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldGT(FieldSecretVersion, v))
}

// SecretVersionGTE applies the GTE predicate on the "secret_version" field.
func SecretVersionGTE(v int) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldGTE(FieldSecretVersion, v))
}

// SecretVersionLT applies the LT predicate on the "secret_version" field.
func SecretVersionLT(v int) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldLT(FieldSecretVersion, v))
}

// SecretVersionLTE applies the LTE predicate on the "secret_version" field.
func SecretVersionLTE(v int) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldLTE(FieldSecretVersion, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldNotIn(FieldState, vs...))
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldGT(FieldState, v))
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldGTE(FieldState, v))
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldLT(FieldState, v))
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldLTE(FieldState, v))
}

// StateContains applies the Contains predicate on the "state" field.
func StateContains(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldContains(FieldState, v))
}

// StateHasPrefix applies the HasPrefix predicate on the "state" field.
func StateHasPrefix(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldHasPrefix(FieldState, v))
}

// StateHasSuffix applies the HasSuffix predicate on the "state" field.
func StateHasSuffix(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldHasSuffix(FieldState, v))
}

// StateEqualFold applies the EqualFold predicate on the "state" field.
func StateEqualFold(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldEqualFold(FieldState, v))
}

// StateContainsFold applies the ContainsFold predicate on the "state" field.
func StateContainsFold(v string) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldContainsFold(FieldState, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.FieldNotNull(FieldUpdatedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.IntegrationCredential) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.IntegrationCredential) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.IntegrationCredential) predicate.IntegrationCredential {
	return predicate.IntegrationCredential(sql.NotPredicates(p))
}
