// Code generated by ent, DO NOT EDIT.

package integrationbinding

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/piglor/loom/services/loom/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldContainsFold(FieldID, id))
}

// GoalID applies equality check predicate on the "goal_id" field. It's identical to GoalIDEQ.
func GoalID(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldEQ(FieldGoalID, v))
}

// Generation applies equality check predicate on the "generation" field. It's identical to GenerationEQ.
func Generation(v int) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldEQ(FieldGeneration, v))
}

// Organization applies equality check predicate on the "organization" field. It's identical to OrganizationEQ.
func Organization(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldEQ(FieldOrganization, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldEQ(FieldSource, v))
}

// Instance applies equality check predicate on the "instance" field. It's identical to InstanceEQ.
func Instance(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldEQ(FieldInstance, v))
}

// EventType applies equality check predicate on the "event_type" field. It's identical to EventTypeEQ.
func EventType(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldEQ(FieldEventType, v))
}

// Resource applies equality check predicate on the "resource" field. It's identical to ResourceEQ.
func Resource(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldEQ(FieldResource, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldEQ(FieldVersion, v))
}

// ReconciledAt applies equality check predicate on the "reconciled_at" field. It's identical to ReconciledAtEQ.
func ReconciledAt(v time.Time) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldEQ(FieldReconciledAt, v))
}

// GoalIDEQ applies the EQ predicate on the "goal_id" field.
func GoalIDEQ(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldEQ(FieldGoalID, v))
}

// GoalIDNEQ applies the NEQ predicate on the "goal_id" field.
func GoalIDNEQ(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldNEQ(FieldGoalID, v))
}

// GoalIDIn applies the In predicate on the "goal_id" field.
func GoalIDIn(vs ...string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldIn(FieldGoalID, vs...))
}

// GoalIDNotIn applies the NotIn predicate on the "goal_id" field.
func GoalIDNotIn(vs ...string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldNotIn(FieldGoalID, vs...))
}

// GoalIDGT applies the GT predicate on the "goal_id" field.
func GoalIDGT(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldGT(FieldGoalID, v))
}

// GoalIDGTE applies the GTE predicate on the "goal_id" field.
func GoalIDGTE(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldGTE(FieldGoalID, v))
}

// GoalIDLT applies the LT predicate on the "goal_id" field.
func GoalIDLT(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldLT(FieldGoalID, v))
}

// GoalIDLTE applies the LTE predicate on the "goal_id" field.
func GoalIDLTE(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldLTE(FieldGoalID, v))
}

// GoalIDContains applies the Contains predicate on the "goal_id" field.
func GoalIDContains(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldContains(FieldGoalID, v))
}

// GoalIDHasPrefix applies the HasPrefix predicate on the "goal_id" field.
func GoalIDHasPrefix(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldHasPrefix(FieldGoalID, v))
}

// GoalIDHasSuffix applies the HasSuffix predicate on the "goal_id" field.
func GoalIDHasSuffix(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldHasSuffix(FieldGoalID, v))
}

// GoalIDEqualFold applies the EqualFold predicate on the "goal_id" field.
func GoalIDEqualFold(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldEqualFold(FieldGoalID, v))
}

// GoalIDContainsFold applies the ContainsFold predicate on the "goal_id" field.
func GoalIDContainsFold(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldContainsFold(FieldGoalID, v))
}

// GenerationEQ applies the EQ predicate on the "generation" field.
func GenerationEQ(v int) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldEQ(FieldGeneration, v))
}

// GenerationNEQ applies the NEQ predicate on the "generation" field.
func GenerationNEQ(v int) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldNEQ(FieldGeneration, v))
}

// GenerationIn applies the In predicate on the "generation" field.
func GenerationIn(vs ...int) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldIn(FieldGeneration, vs...))
}

// GenerationNotIn applies the NotIn predicate on the "generation" field.
func GenerationNotIn(vs ...int) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldNotIn(FieldGeneration, vs...))
}

// GenerationGT applies the GT predicate on the "generation" field.
func GenerationGT(v int) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldGT(FieldGeneration, v))
}

// GenerationGTE applies the GTE predicate on the "generation" field.
func GenerationGTE(v int) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldGTE(FieldGeneration, v))
}

// GenerationLT applies the LT predicate on the "generation" field.
func GenerationLT(v int) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldLT(FieldGeneration, v))
}

// GenerationLTE applies the LTE predicate on the "generation" field.
func GenerationLTE(v int) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldLTE(FieldGeneration, v))
}

// OrganizationEQ applies the EQ predicate on the "organization" field.
func OrganizationEQ(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldEQ(FieldOrganization, v))
}

// OrganizationNEQ applies the NEQ predicate on the "organization" field.
func OrganizationNEQ(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldNEQ(FieldOrganization, v))
}

// OrganizationIn applies the In predicate on the "organization" field.
func OrganizationIn(vs ...string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldIn(FieldOrganization, vs...))
}

// OrganizationNotIn applies the NotIn predicate on the "organization" field.
func OrganizationNotIn(vs ...string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldNotIn(FieldOrganization, vs...))
}

// OrganizationGT applies the GT predicate on the "organization" field.
func OrganizationGT(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldGT(FieldOrganization, v))
}

// OrganizationGTE applies the GTE predicate on the "organization" field.
func OrganizationGTE(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldGTE(FieldOrganization, v))
}

// OrganizationLT applies the LT predicate on the "organization" field.
func OrganizationLT(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldLT(FieldOrganization, v))
}

// OrganizationLTE applies the LTE predicate on the "organization" field.
func OrganizationLTE(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldLTE(FieldOrganization, v))
}

// OrganizationContains applies the Contains predicate on the "organization" field.
func OrganizationContains(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldContains(FieldOrganization, v))
}

// OrganizationHasPrefix applies the HasPrefix predicate on the "organization" field.
func OrganizationHasPrefix(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldHasPrefix(FieldOrganization, v))
}

// OrganizationHasSuffix applies the HasSuffix predicate on the "organization" field.
func OrganizationHasSuffix(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldHasSuffix(FieldOrganization, v))
}

// OrganizationEqualFold applies the EqualFold predicate on the "organization" field.
func OrganizationEqualFold(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldEqualFold(FieldOrganization, v))
}

// OrganizationContainsFold applies the ContainsFold predicate on the "organization" field.
func OrganizationContainsFold(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldContainsFold(FieldOrganization, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldContainsFold(FieldSource, v))
}

// InstanceEQ applies the EQ predicate on the "instance" field.
func InstanceEQ(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldEQ(FieldInstance, v))
}

// InstanceNEQ applies the NEQ predicate on the "instance" field.
func InstanceNEQ(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldNEQ(FieldInstance, v))
}

// InstanceIn applies the In predicate on the "instance" field.
func InstanceIn(vs ...string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldIn(FieldInstance, vs...))
}

// InstanceNotIn applies the NotIn predicate on the "instance" field.
func InstanceNotIn(vs ...string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldNotIn(FieldInstance, vs...))
}

// InstanceGT applies the GT predicate on the "instance" field.
func InstanceGT(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldGT(FieldInstance, v))
}

// InstanceGTE applies the GTE predicate on the "instance" field.
func InstanceGTE(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldGTE(FieldInstance, v))
}

// InstanceLT applies the LT predicate on the "instance" field.
func InstanceLT(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldLT(FieldInstance, v))
}

// InstanceLTE applies the LTE predicate on the "instance" field.
func InstanceLTE(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldLTE(FieldInstance, v))
}

// InstanceContains applies the Contains predicate on the "instance" field.
func InstanceContains(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldContains(FieldInstance, v))
}

// InstanceHasPrefix applies the HasPrefix predicate on the "instance" field.
func InstanceHasPrefix(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldHasPrefix(FieldInstance, v))
}

// InstanceHasSuffix applies the HasSuffix predicate on the "instance" field.
func InstanceHasSuffix(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldHasSuffix(FieldInstance, v))
}

// InstanceEqualFold applies the EqualFold predicate on the "instance" field.
func InstanceEqualFold(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldEqualFold(FieldInstance, v))
}

// InstanceContainsFold applies the ContainsFold predicate on the "instance" field.
func InstanceContainsFold(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldContainsFold(FieldInstance, v))
}

// EventTypeEQ applies the EQ predicate on the "event_type" field.
func EventTypeEQ(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldEQ(FieldEventType, v))
}

// EventTypeNEQ applies the NEQ predicate on the "event_type" field.
func EventTypeNEQ(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldNEQ(FieldEventType, v))
}

// EventTypeIn applies the In predicate on the "event_type" field.
func EventTypeIn(vs ...string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldIn(FieldEventType, vs...))
}

// EventTypeNotIn applies the NotIn predicate on the "event_type" field.
func EventTypeNotIn(vs ...string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldNotIn(FieldEventType, vs...))
}

// EventTypeGT applies the GT predicate on the "event_type" field.
func EventTypeGT(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldGT(FieldEventType, v))
}

// EventTypeGTE applies the GTE predicate on the "event_type" field.
func EventTypeGTE(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldGTE(FieldEventType, v))
}

// EventTypeLT applies the LT predicate on the "event_type" field.
func EventTypeLT(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldLT(FieldEventType, v))
}

// EventTypeLTE applies the LTE predicate on the "event_type" field.
func EventTypeLTE(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldLTE(FieldEventType, v))
}

// EventTypeContains applies the Contains predicate on the "event_type" field.
func EventTypeContains(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldContains(FieldEventType, v))
}

// EventTypeHasPrefix applies the HasPrefix predicate on the "event_type" field.
func EventTypeHasPrefix(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldHasPrefix(FieldEventType, v))
}

// EventTypeHasSuffix applies the HasSuffix predicate on the "event_type" field.
func EventTypeHasSuffix(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldHasSuffix(FieldEventType, v))
}

// EventTypeEqualFold applies the EqualFold predicate on the "event_type" field.
func EventTypeEqualFold(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldEqualFold(FieldEventType, v))
}

// EventTypeContainsFold applies the ContainsFold predicate on the "event_type" field.
func EventTypeContainsFold(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldContainsFold(FieldEventType, v))
}

// ResourceEQ applies the EQ predicate on the "resource" field.
func ResourceEQ(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldEQ(FieldResource, v))
}

// ResourceNEQ applies the NEQ predicate on the "resource" field.
func ResourceNEQ(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldNEQ(FieldResource, v))
}

// ResourceIn applies the In predicate on the "resource" field.
func ResourceIn(vs ...string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldIn(FieldResource, vs...))
}

// ResourceNotIn applies the NotIn predicate on the "resource" field.
func ResourceNotIn(vs ...string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldNotIn(FieldResource, vs...))
}

// ResourceGT applies the GT predicate on the "resource" field.
func ResourceGT(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldGT(FieldResource, v))
}

// ResourceGTE applies the GTE predicate on the "resource" field.
func ResourceGTE(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldGTE(FieldResource, v))
}

// ResourceLT applies the LT predicate on the "resource" field.
func ResourceLT(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldLT(FieldResource, v))
}

// ResourceLTE applies the LTE predicate on the "resource" field.
func ResourceLTE(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldLTE(FieldResource, v))
}

// ResourceContains applies the Contains predicate on the "resource" field.
func ResourceContains(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldContains(FieldResource, v))
}

// ResourceHasPrefix applies the HasPrefix predicate on the "resource" field.
func ResourceHasPrefix(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldHasPrefix(FieldResource, v))
}

// ResourceHasSuffix applies the HasSuffix predicate on the "resource" field.
func ResourceHasSuffix(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldHasSuffix(FieldResource, v))
}

// ResourceEqualFold applies the EqualFold predicate on the "resource" field.
func ResourceEqualFold(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldEqualFold(FieldResource, v))
}

// ResourceContainsFold applies the ContainsFold predicate on the "resource" field.
func ResourceContainsFold(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldContainsFold(FieldResource, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldContainsFold(FieldVersion, v))
}

// AttributesIsNil applies the IsNil predicate on the "attributes" field.
func AttributesIsNil() predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldIsNull(FieldAttributes))
}

// AttributesNotNil applies the NotNil predicate on the "attributes" field.
func AttributesNotNil() predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldNotNull(FieldAttributes))
}

// ReconciledAtEQ applies the EQ predicate on the "reconciled_at" field.
func ReconciledAtEQ(v time.Time) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldEQ(FieldReconciledAt, v))
}

// ReconciledAtNEQ applies the NEQ predicate on the "reconciled_at" field.
func ReconciledAtNEQ(v time.Time) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldNEQ(FieldReconciledAt, v))
}

// ReconciledAtIn applies the In predicate on the "reconciled_at" field.
func ReconciledAtIn(vs ...time.Time) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldIn(FieldReconciledAt, vs...))
}

// ReconciledAtNotIn applies the NotIn predicate on the "reconciled_at" field.
func ReconciledAtNotIn(vs ...time.Time) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldNotIn(FieldReconciledAt, vs...))
}

// ReconciledAtGT applies the GT predicate on the "reconciled_at" field.
func ReconciledAtGT(v time.Time) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldGT(FieldReconciledAt, v))
}

// ReconciledAtGTE applies the GTE predicate on the "reconciled_at" field.
func ReconciledAtGTE(v time.Time) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldGTE(FieldReconciledAt, v))
}

// ReconciledAtLT applies the LT predicate on the "reconciled_at" field.
func ReconciledAtLT(v time.Time) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldLT(FieldReconciledAt, v))
}

// ReconciledAtLTE applies the LTE predicate on the "reconciled_at" field.
func ReconciledAtLTE(v time.Time) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldLTE(FieldReconciledAt, v))
}

// ReconciledAtIsNil applies the IsNil predicate on the "reconciled_at" field.
func ReconciledAtIsNil() predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldIsNull(FieldReconciledAt))
}

// ReconciledAtNotNil applies the NotNil predicate on the "reconciled_at" field.
func ReconciledAtNotNil() predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.FieldNotNull(FieldReconciledAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.IntegrationBinding) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.IntegrationBinding) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.IntegrationBinding) predicate.IntegrationBinding {
	return predicate.IntegrationBinding(sql.NotPredicates(p))
}
