// Code generated by ent, DO NOT EDIT.

package run

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/piglor/loom/services/loom/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Run {
	return predicate.Run(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Run {
	return predicate.Run(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Run {
	return predicate.Run(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Run {
	return predicate.Run(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Run {
	return predicate.Run(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Run {
	return predicate.Run(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Run {
	return predicate.Run(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Run {
	return predicate.Run(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Run {
	return predicate.Run(sql.FieldContainsFold(FieldID, id))
}

// GoalID applies equality check predicate on the "goal_id" field. It's identical to GoalIDEQ.
func GoalID(v string) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldGoalID, v))
}

// WorkflowID applies equality check predicate on the "workflow_id" field. It's identical to WorkflowIDEQ.
func WorkflowID(v string) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldWorkflowID, v))
}

// WorkflowDefinitionID applies equality check predicate on the "workflow_definition_id" field. It's identical to WorkflowDefinitionIDEQ.
func WorkflowDefinitionID(v string) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldWorkflowDefinitionID, v))
}

// WorkflowVersionID applies equality check predicate on the "workflow_version_id" field. It's identical to WorkflowVersionIDEQ.
func WorkflowVersionID(v string) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldWorkflowVersionID, v))
}

// ParentRunID applies equality check predicate on the "parent_run_id" field. It's identical to ParentRunIDEQ.
func ParentRunID(v string) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldParentRunID, v))
}

// InvokingStepKey applies equality check predicate on the "invoking_step_key" field. It's identical to InvokingStepKeyEQ.
func InvokingStepKey(v string) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldInvokingStepKey, v))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v string) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldState, v))
}

// CurrentStepKey applies equality check predicate on the "current_step_key" field. It's identical to CurrentStepKeyEQ.
func CurrentStepKey(v string) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldCurrentStepKey, v))
}

// OrchestrationReference applies equality check predicate on the "orchestration_reference" field. It's identical to OrchestrationReferenceEQ.
func OrchestrationReference(v string) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldOrchestrationReference, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldUpdatedAt, v))
}

// EndedAt applies equality check predicate on the "ended_at" field. It's identical to EndedAtEQ.
func EndedAt(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldEndedAt, v))
}

// GoalIDEQ applies the EQ predicate on the "goal_id" field.
func GoalIDEQ(v string) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldGoalID, v))
}

// GoalIDNEQ applies the NEQ predicate on the "goal_id" field.
func GoalIDNEQ(v string) predicate.Run {
	return predicate.Run(sql.FieldNEQ(FieldGoalID, v))
}

// GoalIDIn applies the In predicate on the "goal_id" field.
func GoalIDIn(vs ...string) predicate.Run {
	return predicate.Run(sql.FieldIn(FieldGoalID, vs...))
}

// GoalIDNotIn applies the NotIn predicate on the "goal_id" field.
func GoalIDNotIn(vs ...string) predicate.Run {
	return predicate.Run(sql.FieldNotIn(FieldGoalID, vs...))
}

// GoalIDGT applies the GT predicate on the "goal_id" field.
func GoalIDGT(v string) predicate.Run {
	return predicate.Run(sql.FieldGT(FieldGoalID, v))
}

// GoalIDGTE applies the GTE predicate on the "goal_id" field.
func GoalIDGTE(v string) predicate.Run {
	return predicate.Run(sql.FieldGTE(FieldGoalID, v))
}

// GoalIDLT applies the LT predicate on the "goal_id" field.
func GoalIDLT(v string) predicate.Run {
	return predicate.Run(sql.FieldLT(FieldGoalID, v))
}

// GoalIDLTE applies the LTE predicate on the "goal_id" field.
func GoalIDLTE(v string) predicate.Run {
	return predicate.Run(sql.FieldLTE(FieldGoalID, v))
}

// GoalIDContains applies the Contains predicate on the "goal_id" field.
func GoalIDContains(v string) predicate.Run {
	return predicate.Run(sql.FieldContains(FieldGoalID, v))
}

// GoalIDHasPrefix applies the HasPrefix predicate on the "goal_id" field.
func GoalIDHasPrefix(v string) predicate.Run {
	return predicate.Run(sql.FieldHasPrefix(FieldGoalID, v))
}

// GoalIDHasSuffix applies the HasSuffix predicate on the "goal_id" field.
func GoalIDHasSuffix(v string) predicate.Run {
	return predicate.Run(sql.FieldHasSuffix(FieldGoalID, v))
}

// GoalIDEqualFold applies the EqualFold predicate on the "goal_id" field.
func GoalIDEqualFold(v string) predicate.Run {
	return predicate.Run(sql.FieldEqualFold(FieldGoalID, v))
}

// GoalIDContainsFold applies the ContainsFold predicate on the "goal_id" field.
func GoalIDContainsFold(v string) predicate.Run {
	return predicate.Run(sql.FieldContainsFold(FieldGoalID, v))
}

// ContextIsNil applies the IsNil predicate on the "context" field.
func ContextIsNil() predicate.Run {
	return predicate.Run(sql.FieldIsNull(FieldContext))
}

// ContextNotNil applies the NotNil predicate on the "context" field.
func ContextNotNil() predicate.Run {
	return predicate.Run(sql.FieldNotNull(FieldContext))
}

// WorkflowIDEQ applies the EQ predicate on the "workflow_id" field.
func WorkflowIDEQ(v string) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldWorkflowID, v))
}

// WorkflowIDNEQ applies the NEQ predicate on the "workflow_id" field.
func WorkflowIDNEQ(v string) predicate.Run {
	return predicate.Run(sql.FieldNEQ(FieldWorkflowID, v))
}

// WorkflowIDIn applies the In predicate on the "workflow_id" field.
func WorkflowIDIn(vs ...string) predicate.Run {
	return predicate.Run(sql.FieldIn(FieldWorkflowID, vs...))
}

// WorkflowIDNotIn applies the NotIn predicate on the "workflow_id" field.
func WorkflowIDNotIn(vs ...string) predicate.Run {
	return predicate.Run(sql.FieldNotIn(FieldWorkflowID, vs...))
}

// WorkflowIDGT applies the GT predicate on the "workflow_id" field.
func WorkflowIDGT(v string) predicate.Run {
	return predicate.Run(sql.FieldGT(FieldWorkflowID, v))
}

// WorkflowIDGTE applies the GTE predicate on the "workflow_id" field.
func WorkflowIDGTE(v string) predicate.Run {
	return predicate.Run(sql.FieldGTE(FieldWorkflowID, v))
}

// WorkflowIDLT applies the LT predicate on the "workflow_id" field.
func WorkflowIDLT(v string) predicate.Run {
	return predicate.Run(sql.FieldLT(FieldWorkflowID, v))
}

// WorkflowIDLTE applies the LTE predicate on the "workflow_id" field.
func WorkflowIDLTE(v string) predicate.Run {
	return predicate.Run(sql.FieldLTE(FieldWorkflowID, v))
}

// WorkflowIDContains applies the Contains predicate on the "workflow_id" field.
func WorkflowIDContains(v string) predicate.Run {
	return predicate.Run(sql.FieldContains(FieldWorkflowID, v))
}

// WorkflowIDHasPrefix applies the HasPrefix predicate on the "workflow_id" field.
func WorkflowIDHasPrefix(v string) predicate.Run {
	return predicate.Run(sql.FieldHasPrefix(FieldWorkflowID, v))
}

// WorkflowIDHasSuffix applies the HasSuffix predicate on the "workflow_id" field.
func WorkflowIDHasSuffix(v string) predicate.Run {
	return predicate.Run(sql.FieldHasSuffix(FieldWorkflowID, v))
}

// WorkflowIDIsNil applies the IsNil predicate on the "workflow_id" field.
func WorkflowIDIsNil() predicate.Run {
	return predicate.Run(sql.FieldIsNull(FieldWorkflowID))
}

// WorkflowIDNotNil applies the NotNil predicate on the "workflow_id" field.
func WorkflowIDNotNil() predicate.Run {
	return predicate.Run(sql.FieldNotNull(FieldWorkflowID))
}

// WorkflowIDEqualFold applies the EqualFold predicate on the "workflow_id" field.
func WorkflowIDEqualFold(v string) predicate.Run {
	return predicate.Run(sql.FieldEqualFold(FieldWorkflowID, v))
}

// WorkflowIDContainsFold applies the ContainsFold predicate on the "workflow_id" field.
func WorkflowIDContainsFold(v string) predicate.Run {
	return predicate.Run(sql.FieldContainsFold(FieldWorkflowID, v))
}

// WorkflowDefinitionIDEQ applies the EQ predicate on the "workflow_definition_id" field.
func WorkflowDefinitionIDEQ(v string) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldWorkflowDefinitionID, v))
}

// WorkflowDefinitionIDNEQ applies the NEQ predicate on the "workflow_definition_id" field.
func WorkflowDefinitionIDNEQ(v string) predicate.Run {
	return predicate.Run(sql.FieldNEQ(FieldWorkflowDefinitionID, v))
}

// WorkflowDefinitionIDIn applies the In predicate on the "workflow_definition_id" field.
func WorkflowDefinitionIDIn(vs ...string) predicate.Run {
	return predicate.Run(sql.FieldIn(FieldWorkflowDefinitionID, vs...))
}

// WorkflowDefinitionIDNotIn applies the NotIn predicate on the "workflow_definition_id" field.
func WorkflowDefinitionIDNotIn(vs ...string) predicate.Run {
	return predicate.Run(sql.FieldNotIn(FieldWorkflowDefinitionID, vs...))
}

// WorkflowDefinitionIDGT applies the GT predicate on the "workflow_definition_id" field.
func WorkflowDefinitionIDGT(v string) predicate.Run {
	return predicate.Run(sql.FieldGT(FieldWorkflowDefinitionID, v))
}

// WorkflowDefinitionIDGTE applies the GTE predicate on the "workflow_definition_id" field.
func WorkflowDefinitionIDGTE(v string) predicate.Run {
	return predicate.Run(sql.FieldGTE(FieldWorkflowDefinitionID, v))
}

// WorkflowDefinitionIDLT applies the LT predicate on the "workflow_definition_id" field.
func WorkflowDefinitionIDLT(v string) predicate.Run {
	return predicate.Run(sql.FieldLT(FieldWorkflowDefinitionID, v))
}

// WorkflowDefinitionIDLTE applies the LTE predicate on the "workflow_definition_id" field.
func WorkflowDefinitionIDLTE(v string) predicate.Run {
	return predicate.Run(sql.FieldLTE(FieldWorkflowDefinitionID, v))
}

// WorkflowDefinitionIDContains applies the Contains predicate on the "workflow_definition_id" field.
func WorkflowDefinitionIDContains(v string) predicate.Run {
	return predicate.Run(sql.FieldContains(FieldWorkflowDefinitionID, v))
}

// WorkflowDefinitionIDHasPrefix applies the HasPrefix predicate on the "workflow_definition_id" field.
func WorkflowDefinitionIDHasPrefix(v string) predicate.Run {
	return predicate.Run(sql.FieldHasPrefix(FieldWorkflowDefinitionID, v))
}

// WorkflowDefinitionIDHasSuffix applies the HasSuffix predicate on the "workflow_definition_id" field.
func WorkflowDefinitionIDHasSuffix(v string) predicate.Run {
	return predicate.Run(sql.FieldHasSuffix(FieldWorkflowDefinitionID, v))
}

// WorkflowDefinitionIDIsNil applies the IsNil predicate on the "workflow_definition_id" field.
func WorkflowDefinitionIDIsNil() predicate.Run {
	return predicate.Run(sql.FieldIsNull(FieldWorkflowDefinitionID))
}

// WorkflowDefinitionIDNotNil applies the NotNil predicate on the "workflow_definition_id" field.
func WorkflowDefinitionIDNotNil() predicate.Run {
	return predicate.Run(sql.FieldNotNull(FieldWorkflowDefinitionID))
}

// WorkflowDefinitionIDEqualFold applies the EqualFold predicate on the "workflow_definition_id" field.
func WorkflowDefinitionIDEqualFold(v string) predicate.Run {
	return predicate.Run(sql.FieldEqualFold(FieldWorkflowDefinitionID, v))
}

// WorkflowDefinitionIDContainsFold applies the ContainsFold predicate on the "workflow_definition_id" field.
func WorkflowDefinitionIDContainsFold(v string) predicate.Run {
	return predicate.Run(sql.FieldContainsFold(FieldWorkflowDefinitionID, v))
}

// WorkflowVersionIDEQ applies the EQ predicate on the "workflow_version_id" field.
func WorkflowVersionIDEQ(v string) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldWorkflowVersionID, v))
}

// WorkflowVersionIDNEQ applies the NEQ predicate on the "workflow_version_id" field.
func WorkflowVersionIDNEQ(v string) predicate.Run {
	return predicate.Run(sql.FieldNEQ(FieldWorkflowVersionID, v))
}

// WorkflowVersionIDIn applies the In predicate on the "workflow_version_id" field.
func WorkflowVersionIDIn(vs ...string) predicate.Run {
	return predicate.Run(sql.FieldIn(FieldWorkflowVersionID, vs...))
}

// WorkflowVersionIDNotIn applies the NotIn predicate on the "workflow_version_id" field.
func WorkflowVersionIDNotIn(vs ...string) predicate.Run {
	return predicate.Run(sql.FieldNotIn(FieldWorkflowVersionID, vs...))
}

// WorkflowVersionIDGT applies the GT predicate on the "workflow_version_id" field.
func WorkflowVersionIDGT(v string) predicate.Run {
	return predicate.Run(sql.FieldGT(FieldWorkflowVersionID, v))
}

// WorkflowVersionIDGTE applies the GTE predicate on the "workflow_version_id" field.
func WorkflowVersionIDGTE(v string) predicate.Run {
	return predicate.Run(sql.FieldGTE(FieldWorkflowVersionID, v))
}

// WorkflowVersionIDLT applies the LT predicate on the "workflow_version_id" field.
func WorkflowVersionIDLT(v string) predicate.Run {
	return predicate.Run(sql.FieldLT(FieldWorkflowVersionID, v))
}

// WorkflowVersionIDLTE applies the LTE predicate on the "workflow_version_id" field.
func WorkflowVersionIDLTE(v string) predicate.Run {
	return predicate.Run(sql.FieldLTE(FieldWorkflowVersionID, v))
}

// WorkflowVersionIDContains applies the Contains predicate on the "workflow_version_id" field.
func WorkflowVersionIDContains(v string) predicate.Run {
	return predicate.Run(sql.FieldContains(FieldWorkflowVersionID, v))
}

// WorkflowVersionIDHasPrefix applies the HasPrefix predicate on the "workflow_version_id" field.
func WorkflowVersionIDHasPrefix(v string) predicate.Run {
	return predicate.Run(sql.FieldHasPrefix(FieldWorkflowVersionID, v))
}

// WorkflowVersionIDHasSuffix applies the HasSuffix predicate on the "workflow_version_id" field.
func WorkflowVersionIDHasSuffix(v string) predicate.Run {
	return predicate.Run(sql.FieldHasSuffix(FieldWorkflowVersionID, v))
}

// WorkflowVersionIDIsNil applies the IsNil predicate on the "workflow_version_id" field.
func WorkflowVersionIDIsNil() predicate.Run {
	return predicate.Run(sql.FieldIsNull(FieldWorkflowVersionID))
}

// WorkflowVersionIDNotNil applies the NotNil predicate on the "workflow_version_id" field.
func WorkflowVersionIDNotNil() predicate.Run {
	return predicate.Run(sql.FieldNotNull(FieldWorkflowVersionID))
}

// WorkflowVersionIDEqualFold applies the EqualFold predicate on the "workflow_version_id" field.
func WorkflowVersionIDEqualFold(v string) predicate.Run {
	return predicate.Run(sql.FieldEqualFold(FieldWorkflowVersionID, v))
}

// WorkflowVersionIDContainsFold applies the ContainsFold predicate on the "workflow_version_id" field.
func WorkflowVersionIDContainsFold(v string) predicate.Run {
	return predicate.Run(sql.FieldContainsFold(FieldWorkflowVersionID, v))
}

// ParentRunIDEQ applies the EQ predicate on the "parent_run_id" field.
func ParentRunIDEQ(v string) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldParentRunID, v))
}

// ParentRunIDNEQ applies the NEQ predicate on the "parent_run_id" field.
func ParentRunIDNEQ(v string) predicate.Run {
	return predicate.Run(sql.FieldNEQ(FieldParentRunID, v))
}

// ParentRunIDIn applies the In predicate on the "parent_run_id" field.
func ParentRunIDIn(vs ...string) predicate.Run {
	return predicate.Run(sql.FieldIn(FieldParentRunID, vs...))
}

// ParentRunIDNotIn applies the NotIn predicate on the "parent_run_id" field.
func ParentRunIDNotIn(vs ...string) predicate.Run {
	return predicate.Run(sql.FieldNotIn(FieldParentRunID, vs...))
}

// ParentRunIDGT applies the GT predicate on the "parent_run_id" field.
func ParentRunIDGT(v string) predicate.Run {
	return predicate.Run(sql.FieldGT(FieldParentRunID, v))
}

// ParentRunIDGTE applies the GTE predicate on the "parent_run_id" field.
func ParentRunIDGTE(v string) predicate.Run {
	return predicate.Run(sql.FieldGTE(FieldParentRunID, v))
}

// ParentRunIDLT applies the LT predicate on the "parent_run_id" field.
func ParentRunIDLT(v string) predicate.Run {
	return predicate.Run(sql.FieldLT(FieldParentRunID, v))
}

// ParentRunIDLTE applies the LTE predicate on the "parent_run_id" field.
func ParentRunIDLTE(v string) predicate.Run {
	return predicate.Run(sql.FieldLTE(FieldParentRunID, v))
}

// ParentRunIDContains applies the Contains predicate on the "parent_run_id" field.
func ParentRunIDContains(v string) predicate.Run {
	return predicate.Run(sql.FieldContains(FieldParentRunID, v))
}

// ParentRunIDHasPrefix applies the HasPrefix predicate on the "parent_run_id" field.
func ParentRunIDHasPrefix(v string) predicate.Run {
	return predicate.Run(sql.FieldHasPrefix(FieldParentRunID, v))
}

// ParentRunIDHasSuffix applies the HasSuffix predicate on the "parent_run_id" field.
func ParentRunIDHasSuffix(v string) predicate.Run {
	return predicate.Run(sql.FieldHasSuffix(FieldParentRunID, v))
}

// ParentRunIDIsNil applies the IsNil predicate on the "parent_run_id" field.
func ParentRunIDIsNil() predicate.Run {
	return predicate.Run(sql.FieldIsNull(FieldParentRunID))
}

// ParentRunIDNotNil applies the NotNil predicate on the "parent_run_id" field.
func ParentRunIDNotNil() predicate.Run {
	return predicate.Run(sql.FieldNotNull(FieldParentRunID))
}

// ParentRunIDEqualFold applies the EqualFold predicate on the "parent_run_id" field.
func ParentRunIDEqualFold(v string) predicate.Run {
	return predicate.Run(sql.FieldEqualFold(FieldParentRunID, v))
}

// ParentRunIDContainsFold applies the ContainsFold predicate on the "parent_run_id" field.
func ParentRunIDContainsFold(v string) predicate.Run {
	return predicate.Run(sql.FieldContainsFold(FieldParentRunID, v))
}

// InvokingStepKeyEQ applies the EQ predicate on the "invoking_step_key" field.
func InvokingStepKeyEQ(v string) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldInvokingStepKey, v))
}

// InvokingStepKeyNEQ applies the NEQ predicate on the "invoking_step_key" field.
func InvokingStepKeyNEQ(v string) predicate.Run {
	return predicate.Run(sql.FieldNEQ(FieldInvokingStepKey, v))
}

// InvokingStepKeyIn applies the In predicate on the "invoking_step_key" field.
func InvokingStepKeyIn(vs ...string) predicate.Run {
	return predicate.Run(sql.FieldIn(FieldInvokingStepKey, vs...))
}

// InvokingStepKeyNotIn applies the NotIn predicate on the "invoking_step_key" field.
func InvokingStepKeyNotIn(vs ...string) predicate.Run {
	return predicate.Run(sql.FieldNotIn(FieldInvokingStepKey, vs...))
}

// InvokingStepKeyGT applies the GT predicate on the "invoking_step_key" field.
func InvokingStepKeyGT(v string) predicate.Run {
	return predicate.Run(sql.FieldGT(FieldInvokingStepKey, v))
}

// InvokingStepKeyGTE applies the GTE predicate on the "invoking_step_key" field.
func InvokingStepKeyGTE(v string) predicate.Run {
	return predicate.Run(sql.FieldGTE(FieldInvokingStepKey, v))
}

// InvokingStepKeyLT applies the LT predicate on the "invoking_step_key" field.
func InvokingStepKeyLT(v string) predicate.Run {
	return predicate.Run(sql.FieldLT(FieldInvokingStepKey, v))
}

// InvokingStepKeyLTE applies the LTE predicate on the "invoking_step_key" field.
func InvokingStepKeyLTE(v string) predicate.Run {
	return predicate.Run(sql.FieldLTE(FieldInvokingStepKey, v))
}

// InvokingStepKeyContains applies the Contains predicate on the "invoking_step_key" field.
func InvokingStepKeyContains(v string) predicate.Run {
	return predicate.Run(sql.FieldContains(FieldInvokingStepKey, v))
}

// InvokingStepKeyHasPrefix applies the HasPrefix predicate on the "invoking_step_key" field.
func InvokingStepKeyHasPrefix(v string) predicate.Run {
	return predicate.Run(sql.FieldHasPrefix(FieldInvokingStepKey, v))
}

// InvokingStepKeyHasSuffix applies the HasSuffix predicate on the "invoking_step_key" field.
func InvokingStepKeyHasSuffix(v string) predicate.Run {
	return predicate.Run(sql.FieldHasSuffix(FieldInvokingStepKey, v))
}

// InvokingStepKeyIsNil applies the IsNil predicate on the "invoking_step_key" field.
func InvokingStepKeyIsNil() predicate.Run {
	return predicate.Run(sql.FieldIsNull(FieldInvokingStepKey))
}

// InvokingStepKeyNotNil applies the NotNil predicate on the "invoking_step_key" field.
func InvokingStepKeyNotNil() predicate.Run {
	return predicate.Run(sql.FieldNotNull(FieldInvokingStepKey))
}

// InvokingStepKeyEqualFold applies the EqualFold predicate on the "invoking_step_key" field.
func InvokingStepKeyEqualFold(v string) predicate.Run {
	return predicate.Run(sql.FieldEqualFold(FieldInvokingStepKey, v))
}

// InvokingStepKeyContainsFold applies the ContainsFold predicate on the "invoking_step_key" field.
func InvokingStepKeyContainsFold(v string) predicate.Run {
	return predicate.Run(sql.FieldContainsFold(FieldInvokingStepKey, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v string) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v string) predicate.Run {
	return predicate.Run(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...string) predicate.Run {
	return predicate.Run(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...string) predicate.Run {
	return predicate.Run(sql.FieldNotIn(FieldState, vs...))
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v string) predicate.Run {
	return predicate.Run(sql.FieldGT(FieldState, v))
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v string) predicate.Run {
	return predicate.Run(sql.FieldGTE(FieldState, v))
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v string) predicate.Run {
	return predicate.Run(sql.FieldLT(FieldState, v))
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v string) predicate.Run {
	return predicate.Run(sql.FieldLTE(FieldState, v))
}

// StateContains applies the Contains predicate on the "state" field.
func StateContains(v string) predicate.Run {
	return predicate.Run(sql.FieldContains(FieldState, v))
}

// StateHasPrefix applies the HasPrefix predicate on the "state" field.
func StateHasPrefix(v string) predicate.Run {
	return predicate.Run(sql.FieldHasPrefix(FieldState, v))
}

// StateHasSuffix applies the HasSuffix predicate on the "state" field.
func StateHasSuffix(v string) predicate.Run {
	return predicate.Run(sql.FieldHasSuffix(FieldState, v))
}

// StateEqualFold applies the EqualFold predicate on the "state" field.
func StateEqualFold(v string) predicate.Run {
	return predicate.Run(sql.FieldEqualFold(FieldState, v))
}

// StateContainsFold applies the ContainsFold predicate on the "state" field.
func StateContainsFold(v string) predicate.Run {
	return predicate.Run(sql.FieldContainsFold(FieldState, v))
}

// CurrentStepKeyEQ applies the EQ predicate on the "current_step_key" field.
func CurrentStepKeyEQ(v string) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldCurrentStepKey, v))
}

// CurrentStepKeyNEQ applies the NEQ predicate on the "current_step_key" field.
func CurrentStepKeyNEQ(v string) predicate.Run {
	return predicate.Run(sql.FieldNEQ(FieldCurrentStepKey, v))
}

// CurrentStepKeyIn applies the In predicate on the "current_step_key" field.
func CurrentStepKeyIn(vs ...string) predicate.Run {
	return predicate.Run(sql.FieldIn(FieldCurrentStepKey, vs...))
}

// CurrentStepKeyNotIn applies the NotIn predicate on the "current_step_key" field.
func CurrentStepKeyNotIn(vs ...string) predicate.Run {
	return predicate.Run(sql.FieldNotIn(FieldCurrentStepKey, vs...))
}

// CurrentStepKeyGT applies the GT predicate on the "current_step_key" field.
func CurrentStepKeyGT(v string) predicate.Run {
	return predicate.Run(sql.FieldGT(FieldCurrentStepKey, v))
}

// CurrentStepKeyGTE applies the GTE predicate on the "current_step_key" field.
func CurrentStepKeyGTE(v string) predicate.Run {
	return predicate.Run(sql.FieldGTE(FieldCurrentStepKey, v))
}

// CurrentStepKeyLT applies the LT predicate on the "current_step_key" field.
func CurrentStepKeyLT(v string) predicate.Run {
	return predicate.Run(sql.FieldLT(FieldCurrentStepKey, v))
}

// CurrentStepKeyLTE applies the LTE predicate on the "current_step_key" field.
func CurrentStepKeyLTE(v string) predicate.Run {
	return predicate.Run(sql.FieldLTE(FieldCurrentStepKey, v))
}

// CurrentStepKeyContains applies the Contains predicate on the "current_step_key" field.
func CurrentStepKeyContains(v string) predicate.Run {
	return predicate.Run(sql.FieldContains(FieldCurrentStepKey, v))
}

// CurrentStepKeyHasPrefix applies the HasPrefix predicate on the "current_step_key" field.
func CurrentStepKeyHasPrefix(v string) predicate.Run {
	return predicate.Run(sql.FieldHasPrefix(FieldCurrentStepKey, v))
}

// CurrentStepKeyHasSuffix applies the HasSuffix predicate on the "current_step_key" field.
func CurrentStepKeyHasSuffix(v string) predicate.Run {
	return predicate.Run(sql.FieldHasSuffix(FieldCurrentStepKey, v))
}

// CurrentStepKeyIsNil applies the IsNil predicate on the "current_step_key" field.
func CurrentStepKeyIsNil() predicate.Run {
	return predicate.Run(sql.FieldIsNull(FieldCurrentStepKey))
}

// CurrentStepKeyNotNil applies the NotNil predicate on the "current_step_key" field.
func CurrentStepKeyNotNil() predicate.Run {
	return predicate.Run(sql.FieldNotNull(FieldCurrentStepKey))
}

// CurrentStepKeyEqualFold applies the EqualFold predicate on the "current_step_key" field.
func CurrentStepKeyEqualFold(v string) predicate.Run {
	return predicate.Run(sql.FieldEqualFold(FieldCurrentStepKey, v))
}

// CurrentStepKeyContainsFold applies the ContainsFold predicate on the "current_step_key" field.
func CurrentStepKeyContainsFold(v string) predicate.Run {
	return predicate.Run(sql.FieldContainsFold(FieldCurrentStepKey, v))
}

// OrchestrationReferenceEQ applies the EQ predicate on the "orchestration_reference" field.
func OrchestrationReferenceEQ(v string) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldOrchestrationReference, v))
}

// OrchestrationReferenceNEQ applies the NEQ predicate on the "orchestration_reference" field.
func OrchestrationReferenceNEQ(v string) predicate.Run {
	return predicate.Run(sql.FieldNEQ(FieldOrchestrationReference, v))
}

// OrchestrationReferenceIn applies the In predicate on the "orchestration_reference" field.
func OrchestrationReferenceIn(vs ...string) predicate.Run {
	return predicate.Run(sql.FieldIn(FieldOrchestrationReference, vs...))
}

// OrchestrationReferenceNotIn applies the NotIn predicate on the "orchestration_reference" field.
func OrchestrationReferenceNotIn(vs ...string) predicate.Run {
	return predicate.Run(sql.FieldNotIn(FieldOrchestrationReference, vs...))
}

// OrchestrationReferenceGT applies the GT predicate on the "orchestration_reference" field.
func OrchestrationReferenceGT(v string) predicate.Run {
	return predicate.Run(sql.FieldGT(FieldOrchestrationReference, v))
}

// OrchestrationReferenceGTE applies the GTE predicate on the "orchestration_reference" field.
func OrchestrationReferenceGTE(v string) predicate.Run {
	return predicate.Run(sql.FieldGTE(FieldOrchestrationReference, v))
}

// OrchestrationReferenceLT applies the LT predicate on the "orchestration_reference" field.
func OrchestrationReferenceLT(v string) predicate.Run {
	return predicate.Run(sql.FieldLT(FieldOrchestrationReference, v))
}

// OrchestrationReferenceLTE applies the LTE predicate on the "orchestration_reference" field.
func OrchestrationReferenceLTE(v string) predicate.Run {
	return predicate.Run(sql.FieldLTE(FieldOrchestrationReference, v))
}

// OrchestrationReferenceContains applies the Contains predicate on the "orchestration_reference" field.
func OrchestrationReferenceContains(v string) predicate.Run {
	return predicate.Run(sql.FieldContains(FieldOrchestrationReference, v))
}

// OrchestrationReferenceHasPrefix applies the HasPrefix predicate on the "orchestration_reference" field.
func OrchestrationReferenceHasPrefix(v string) predicate.Run {
	return predicate.Run(sql.FieldHasPrefix(FieldOrchestrationReference, v))
}

// OrchestrationReferenceHasSuffix applies the HasSuffix predicate on the "orchestration_reference" field.
func OrchestrationReferenceHasSuffix(v string) predicate.Run {
	return predicate.Run(sql.FieldHasSuffix(FieldOrchestrationReference, v))
}

// OrchestrationReferenceIsNil applies the IsNil predicate on the "orchestration_reference" field.
func OrchestrationReferenceIsNil() predicate.Run {
	return predicate.Run(sql.FieldIsNull(FieldOrchestrationReference))
}

// OrchestrationReferenceNotNil applies the NotNil predicate on the "orchestration_reference" field.
func OrchestrationReferenceNotNil() predicate.Run {
	return predicate.Run(sql.FieldNotNull(FieldOrchestrationReference))
}

// OrchestrationReferenceEqualFold applies the EqualFold predicate on the "orchestration_reference" field.
func OrchestrationReferenceEqualFold(v string) predicate.Run {
	return predicate.Run(sql.FieldEqualFold(FieldOrchestrationReference, v))
}

// OrchestrationReferenceContainsFold applies the ContainsFold predicate on the "orchestration_reference" field.
func OrchestrationReferenceContainsFold(v string) predicate.Run {
	return predicate.Run(sql.FieldContainsFold(FieldOrchestrationReference, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Run {
	return predicate.Run(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Run {
	return predicate.Run(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.Run {
	return predicate.Run(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.Run {
	return predicate.Run(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Run {
	return predicate.Run(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Run {
	return predicate.Run(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.Run {
	return predicate.Run(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.Run {
	return predicate.Run(sql.FieldNotNull(FieldUpdatedAt))
}

// EndedAtEQ applies the EQ predicate on the "ended_at" field.
func EndedAtEQ(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldEndedAt, v))
}

// EndedAtNEQ applies the NEQ predicate on the "ended_at" field.
func EndedAtNEQ(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldNEQ(FieldEndedAt, v))
}

// EndedAtIn applies the In predicate on the "ended_at" field.
func EndedAtIn(vs ...time.Time) predicate.Run {
	return predicate.Run(sql.FieldIn(FieldEndedAt, vs...))
}

// EndedAtNotIn applies the NotIn predicate on the "ended_at" field.
func EndedAtNotIn(vs ...time.Time) predicate.Run {
	return predicate.Run(sql.FieldNotIn(FieldEndedAt, vs...))
}

// EndedAtGT applies the GT predicate on the "ended_at" field.
func EndedAtGT(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldGT(FieldEndedAt, v))
}

// EndedAtGTE applies the GTE predicate on the "ended_at" field.
func EndedAtGTE(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldGTE(FieldEndedAt, v))
}

// EndedAtLT applies the LT predicate on the "ended_at" field.
func EndedAtLT(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldLT(FieldEndedAt, v))
}

// EndedAtLTE applies the LTE predicate on the "ended_at" field.
func EndedAtLTE(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldLTE(FieldEndedAt, v))
}

// EndedAtIsNil applies the IsNil predicate on the "ended_at" field.
func EndedAtIsNil() predicate.Run {
	return predicate.Run(sql.FieldIsNull(FieldEndedAt))
}

// EndedAtNotNil applies the NotNil predicate on the "ended_at" field.
func EndedAtNotNil() predicate.Run {
	return predicate.Run(sql.FieldNotNull(FieldEndedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Run) predicate.Run {
	return predicate.Run(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Run) predicate.Run {
	return predicate.Run(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Run) predicate.Run {
	return predicate.Run(sql.NotPredicates(p))
}
