// Code generated by ent, DO NOT EDIT.

package session

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the session type in the database.
	Label = "session"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRunID holds the string denoting the run_id field in the database.
	FieldRunID = "run_id"
	// FieldWorkerID holds the string denoting the worker_id field in the database.
	FieldWorkerID = "worker_id"
	// FieldRuntime holds the string denoting the runtime field in the database.
	FieldRuntime = "runtime"
	// FieldProviderSessionID holds the string denoting the provider_session_id field in the database.
	FieldProviderSessionID = "provider_session_id"
	// Table holds the table name of the session in the database.
	Table = "sessions"
)

// Columns holds all SQL columns for session fields.
var Columns = []string{
	FieldID,
	FieldRunID,
	FieldWorkerID,
	FieldRuntime,
	FieldProviderSessionID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the Session queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRunID orders the results by the run_id field.
func ByRunID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRunID, opts...).ToFunc()
}

// ByWorkerID orders the results by the worker_id field.
func ByWorkerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkerID, opts...).ToFunc()
}

// ByRuntime orders the results by the runtime field.
func ByRuntime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRuntime, opts...).ToFunc()
}

// ByProviderSessionID orders the results by the provider_session_id field.
func ByProviderSessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderSessionID, opts...).ToFunc()
}
