// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/piglor/loom/services/loom/ent/authidentity"
	"github.com/piglor/loom/services/loom/ent/predicate"
)

// AuthIdentityUpdate is the builder for updating AuthIdentity entities.
type AuthIdentityUpdate struct {
	config
	hooks    []Hook
	mutation *AuthIdentityMutation
}

// Where appends a list predicates to the AuthIdentityUpdate builder.
func (_u *AuthIdentityUpdate) Where(ps ...predicate.AuthIdentity) *AuthIdentityUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrganization sets the "organization" field.
func (_u *AuthIdentityUpdate) SetOrganization(v string) *AuthIdentityUpdate {
	_u.mutation.SetOrganization(v)
	return _u
}

// SetNillableOrganization sets the "organization" field if the given value is not nil.
func (_u *AuthIdentityUpdate) SetNillableOrganization(v *string) *AuthIdentityUpdate {
	if v != nil {
		_u.SetOrganization(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AuthIdentityUpdate) SetUserID(v string) *AuthIdentityUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AuthIdentityUpdate) SetNillableUserID(v *string) *AuthIdentityUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *AuthIdentityUpdate) SetProvider(v string) *AuthIdentityUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *AuthIdentityUpdate) SetNillableProvider(v *string) *AuthIdentityUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *AuthIdentityUpdate) SetSubject(v string) *AuthIdentityUpdate {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *AuthIdentityUpdate) SetNillableSubject(v *string) *AuthIdentityUpdate {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *AuthIdentityUpdate) SetEmail(v string) *AuthIdentityUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *AuthIdentityUpdate) SetNillableEmail(v *string) *AuthIdentityUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *AuthIdentityUpdate) ClearEmail() *AuthIdentityUpdate {
	_u.mutation.ClearEmail()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AuthIdentityUpdate) SetCreatedAt(v time.Time) *AuthIdentityUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AuthIdentityUpdate) SetNillableCreatedAt(v *time.Time) *AuthIdentityUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *AuthIdentityUpdate) ClearCreatedAt() *AuthIdentityUpdate {
	_u.mutation.ClearCreatedAt()
	return _u
}

// Mutation returns the AuthIdentityMutation object of the builder.
func (_u *AuthIdentityUpdate) Mutation() *AuthIdentityMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuthIdentityUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthIdentityUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuthIdentityUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthIdentityUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AuthIdentityUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(authidentity.Table, authidentity.Columns, sqlgraph.NewFieldSpec(authidentity.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Organization(); ok {
		_spec.SetField(authidentity.FieldOrganization, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(authidentity.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(authidentity.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(authidentity.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(authidentity.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(authidentity.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(authidentity.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(authidentity.FieldCreatedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authidentity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuthIdentityUpdateOne is the builder for updating a single AuthIdentity entity.
type AuthIdentityUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuthIdentityMutation
}

// SetOrganization sets the "organization" field.
func (_u *AuthIdentityUpdateOne) SetOrganization(v string) *AuthIdentityUpdateOne {
	_u.mutation.SetOrganization(v)
	return _u
}

// SetNillableOrganization sets the "organization" field if the given value is not nil.
func (_u *AuthIdentityUpdateOne) SetNillableOrganization(v *string) *AuthIdentityUpdateOne {
	if v != nil {
		_u.SetOrganization(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AuthIdentityUpdateOne) SetUserID(v string) *AuthIdentityUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AuthIdentityUpdateOne) SetNillableUserID(v *string) *AuthIdentityUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *AuthIdentityUpdateOne) SetProvider(v string) *AuthIdentityUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *AuthIdentityUpdateOne) SetNillableProvider(v *string) *AuthIdentityUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *AuthIdentityUpdateOne) SetSubject(v string) *AuthIdentityUpdateOne {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *AuthIdentityUpdateOne) SetNillableSubject(v *string) *AuthIdentityUpdateOne {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *AuthIdentityUpdateOne) SetEmail(v string) *AuthIdentityUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *AuthIdentityUpdateOne) SetNillableEmail(v *string) *AuthIdentityUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *AuthIdentityUpdateOne) ClearEmail() *AuthIdentityUpdateOne {
	_u.mutation.ClearEmail()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AuthIdentityUpdateOne) SetCreatedAt(v time.Time) *AuthIdentityUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AuthIdentityUpdateOne) SetNillableCreatedAt(v *time.Time) *AuthIdentityUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *AuthIdentityUpdateOne) ClearCreatedAt() *AuthIdentityUpdateOne {
	_u.mutation.ClearCreatedAt()
	return _u
}

// Mutation returns the AuthIdentityMutation object of the builder.
func (_u *AuthIdentityUpdateOne) Mutation() *AuthIdentityMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuthIdentityUpdate builder.
func (_u *AuthIdentityUpdateOne) Where(ps ...predicate.AuthIdentity) *AuthIdentityUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuthIdentityUpdateOne) Select(field string, fields ...string) *AuthIdentityUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuthIdentity entity.
func (_u *AuthIdentityUpdateOne) Save(ctx context.Context) (*AuthIdentity, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthIdentityUpdateOne) SaveX(ctx context.Context) *AuthIdentity {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuthIdentityUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthIdentityUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AuthIdentityUpdateOne) sqlSave(ctx context.Context) (_node *AuthIdentity, err error) {
	_spec := sqlgraph.NewUpdateSpec(authidentity.Table, authidentity.Columns, sqlgraph.NewFieldSpec(authidentity.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuthIdentity.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, authidentity.FieldID)
		for _, f := range fields {
			if !authidentity.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != authidentity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Organization(); ok {
		_spec.SetField(authidentity.FieldOrganization, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(authidentity.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(authidentity.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(authidentity.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(authidentity.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(authidentity.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(authidentity.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(authidentity.FieldCreatedAt, field.TypeTime)
	}
	_node = &AuthIdentity{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authidentity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
