// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/piglor/loom/services/loom/ent/authoauthstate"
)

// AuthOAuthStateCreate is the builder for creating a AuthOAuthState entity.
type AuthOAuthStateCreate struct {
	config
	mutation *AuthOAuthStateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOrganization sets the "organization" field.
func (_c *AuthOAuthStateCreate) SetOrganization(v string) *AuthOAuthStateCreate {
	_c.mutation.SetOrganization(v)
	return _c
}

// SetStateHash sets the "state_hash" field.
func (_c *AuthOAuthStateCreate) SetStateHash(v string) *AuthOAuthStateCreate {
	_c.mutation.SetStateHash(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *AuthOAuthStateCreate) SetExpiresAt(v time.Time) *AuthOAuthStateCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetConsumedAt sets the "consumed_at" field.
func (_c *AuthOAuthStateCreate) SetConsumedAt(v time.Time) *AuthOAuthStateCreate {
	_c.mutation.SetConsumedAt(v)
	return _c
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_c *AuthOAuthStateCreate) SetNillableConsumedAt(v *time.Time) *AuthOAuthStateCreate {
	if v != nil {
		_c.SetConsumedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AuthOAuthStateCreate) SetID(v string) *AuthOAuthStateCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AuthOAuthStateCreate) SetNillableID(v *string) *AuthOAuthStateCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the AuthOAuthStateMutation object of the builder.
func (_c *AuthOAuthStateCreate) Mutation() *AuthOAuthStateMutation {
	return _c.mutation
}

// Save creates the AuthOAuthState in the database.
func (_c *AuthOAuthStateCreate) Save(ctx context.Context) (*AuthOAuthState, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuthOAuthStateCreate) SaveX(ctx context.Context) *AuthOAuthState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthOAuthStateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthOAuthStateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuthOAuthStateCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := authoauthstate.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuthOAuthStateCreate) check() error {
	if _, ok := _c.mutation.Organization(); !ok {
		return &ValidationError{Name: "organization", err: errors.New(`ent: missing required field "AuthOAuthState.organization"`)}
	}
	if _, ok := _c.mutation.StateHash(); !ok {
		return &ValidationError{Name: "state_hash", err: errors.New(`ent: missing required field "AuthOAuthState.state_hash"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "AuthOAuthState.expires_at"`)}
	}
	return nil
}

func (_c *AuthOAuthStateCreate) sqlSave(ctx context.Context) (*AuthOAuthState, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected AuthOAuthState.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuthOAuthStateCreate) createSpec() (*AuthOAuthState, *sqlgraph.CreateSpec) {
	var (
		_node = &AuthOAuthState{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(authoauthstate.Table, sqlgraph.NewFieldSpec(authoauthstate.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Organization(); ok {
		_spec.SetField(authoauthstate.FieldOrganization, field.TypeString, value)
		_node.Organization = value
	}
	if value, ok := _c.mutation.StateHash(); ok {
		_spec.SetField(authoauthstate.FieldStateHash, field.TypeString, value)
		_node.StateHash = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(authoauthstate.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.ConsumedAt(); ok {
		_spec.SetField(authoauthstate.FieldConsumedAt, field.TypeTime, value)
		_node.ConsumedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuthOAuthState.Create().
//		SetOrganization(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuthOAuthStateUpsert) {
//			SetOrganization(v+v).
//		}).
//		Exec(ctx)
func (_c *AuthOAuthStateCreate) OnConflict(opts ...sql.ConflictOption) *AuthOAuthStateUpsertOne {
	_c.conflict = opts
	return &AuthOAuthStateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuthOAuthState.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuthOAuthStateCreate) OnConflictColumns(columns ...string) *AuthOAuthStateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuthOAuthStateUpsertOne{
		create: _c,
	}
}

type (
	// AuthOAuthStateUpsertOne is the builder for "upsert"-ing
	//  one AuthOAuthState node.
	AuthOAuthStateUpsertOne struct {
		create *AuthOAuthStateCreate
	}

	// AuthOAuthStateUpsert is the "OnConflict" setter.
	AuthOAuthStateUpsert struct {
		*sql.UpdateSet
	}
)

// SetOrganization sets the "organization" field.
func (u *AuthOAuthStateUpsert) SetOrganization(v string) *AuthOAuthStateUpsert {
	u.Set(authoauthstate.FieldOrganization, v)
	return u
}

// UpdateOrganization sets the "organization" field to the value that was provided on create.
func (u *AuthOAuthStateUpsert) UpdateOrganization() *AuthOAuthStateUpsert {
	u.SetExcluded(authoauthstate.FieldOrganization)
	return u
}

// SetStateHash sets the "state_hash" field.
func (u *AuthOAuthStateUpsert) SetStateHash(v string) *AuthOAuthStateUpsert {
	u.Set(authoauthstate.FieldStateHash, v)
	return u
}

// UpdateStateHash sets the "state_hash" field to the value that was provided on create.
func (u *AuthOAuthStateUpsert) UpdateStateHash() *AuthOAuthStateUpsert {
	u.SetExcluded(authoauthstate.FieldStateHash)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *AuthOAuthStateUpsert) SetExpiresAt(v time.Time) *AuthOAuthStateUpsert {
	u.Set(authoauthstate.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *AuthOAuthStateUpsert) UpdateExpiresAt() *AuthOAuthStateUpsert {
	u.SetExcluded(authoauthstate.FieldExpiresAt)
	return u
}

// SetConsumedAt sets the "consumed_at" field.
func (u *AuthOAuthStateUpsert) SetConsumedAt(v time.Time) *AuthOAuthStateUpsert {
	u.Set(authoauthstate.FieldConsumedAt, v)
	return u
}

// UpdateConsumedAt sets the "consumed_at" field to the value that was provided on create.
func (u *AuthOAuthStateUpsert) UpdateConsumedAt() *AuthOAuthStateUpsert {
	u.SetExcluded(authoauthstate.FieldConsumedAt)
	return u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (u *AuthOAuthStateUpsert) ClearConsumedAt() *AuthOAuthStateUpsert {
	u.SetNull(authoauthstate.FieldConsumedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.AuthOAuthState.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(authoauthstate.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AuthOAuthStateUpsertOne) UpdateNewValues() *AuthOAuthStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(authoauthstate.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuthOAuthState.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AuthOAuthStateUpsertOne) Ignore() *AuthOAuthStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuthOAuthStateUpsertOne) DoNothing() *AuthOAuthStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuthOAuthStateCreate.OnConflict
// documentation for more info.
func (u *AuthOAuthStateUpsertOne) Update(set func(*AuthOAuthStateUpsert)) *AuthOAuthStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuthOAuthStateUpsert{UpdateSet: update})
	}))
	return u
}

// SetOrganization sets the "organization" field.
func (u *AuthOAuthStateUpsertOne) SetOrganization(v string) *AuthOAuthStateUpsertOne {
	return u.Update(func(s *AuthOAuthStateUpsert) {
		s.SetOrganization(v)
	})
}

// UpdateOrganization sets the "organization" field to the value that was provided on create.
func (u *AuthOAuthStateUpsertOne) UpdateOrganization() *AuthOAuthStateUpsertOne {
	return u.Update(func(s *AuthOAuthStateUpsert) {
		s.UpdateOrganization()
	})
}

// SetStateHash sets the "state_hash" field.
func (u *AuthOAuthStateUpsertOne) SetStateHash(v string) *AuthOAuthStateUpsertOne {
	return u.Update(func(s *AuthOAuthStateUpsert) {
		s.SetStateHash(v)
	})
}

// UpdateStateHash sets the "state_hash" field to the value that was provided on create.
func (u *AuthOAuthStateUpsertOne) UpdateStateHash() *AuthOAuthStateUpsertOne {
	return u.Update(func(s *AuthOAuthStateUpsert) {
		s.UpdateStateHash()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *AuthOAuthStateUpsertOne) SetExpiresAt(v time.Time) *AuthOAuthStateUpsertOne {
	return u.Update(func(s *AuthOAuthStateUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *AuthOAuthStateUpsertOne) UpdateExpiresAt() *AuthOAuthStateUpsertOne {
	return u.Update(func(s *AuthOAuthStateUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetConsumedAt sets the "consumed_at" field.
func (u *AuthOAuthStateUpsertOne) SetConsumedAt(v time.Time) *AuthOAuthStateUpsertOne {
	return u.Update(func(s *AuthOAuthStateUpsert) {
		s.SetConsumedAt(v)
	})
}

// UpdateConsumedAt sets the "consumed_at" field to the value that was provided on create.
func (u *AuthOAuthStateUpsertOne) UpdateConsumedAt() *AuthOAuthStateUpsertOne {
	return u.Update(func(s *AuthOAuthStateUpsert) {
		s.UpdateConsumedAt()
	})
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (u *AuthOAuthStateUpsertOne) ClearConsumedAt() *AuthOAuthStateUpsertOne {
	return u.Update(func(s *AuthOAuthStateUpsert) {
		s.ClearConsumedAt()
	})
}

// Exec executes the query.
func (u *AuthOAuthStateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuthOAuthStateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuthOAuthStateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AuthOAuthStateUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AuthOAuthStateUpsertOne.ID is not supported by MySQL driver. Use AuthOAuthStateUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AuthOAuthStateUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AuthOAuthStateCreateBulk is the builder for creating many AuthOAuthState entities in bulk.
type AuthOAuthStateCreateBulk struct {
	config
	err      error
	builders []*AuthOAuthStateCreate
	conflict []sql.ConflictOption
}

// Save creates the AuthOAuthState entities in the database.
func (_c *AuthOAuthStateCreateBulk) Save(ctx context.Context) ([]*AuthOAuthState, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuthOAuthState, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuthOAuthStateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuthOAuthStateCreateBulk) SaveX(ctx context.Context) []*AuthOAuthState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthOAuthStateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthOAuthStateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuthOAuthState.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuthOAuthStateUpsert) {
//			SetOrganization(v+v).
//		}).
//		Exec(ctx)
func (_c *AuthOAuthStateCreateBulk) OnConflict(opts ...sql.ConflictOption) *AuthOAuthStateUpsertBulk {
	_c.conflict = opts
	return &AuthOAuthStateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuthOAuthState.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuthOAuthStateCreateBulk) OnConflictColumns(columns ...string) *AuthOAuthStateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuthOAuthStateUpsertBulk{
		create: _c,
	}
}

// AuthOAuthStateUpsertBulk is the builder for "upsert"-ing
// a bulk of AuthOAuthState nodes.
type AuthOAuthStateUpsertBulk struct {
	create *AuthOAuthStateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AuthOAuthState.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(authoauthstate.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AuthOAuthStateUpsertBulk) UpdateNewValues() *AuthOAuthStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(authoauthstate.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuthOAuthState.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AuthOAuthStateUpsertBulk) Ignore() *AuthOAuthStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuthOAuthStateUpsertBulk) DoNothing() *AuthOAuthStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuthOAuthStateCreateBulk.OnConflict
// documentation for more info.
func (u *AuthOAuthStateUpsertBulk) Update(set func(*AuthOAuthStateUpsert)) *AuthOAuthStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuthOAuthStateUpsert{UpdateSet: update})
	}))
	return u
}

// SetOrganization sets the "organization" field.
func (u *AuthOAuthStateUpsertBulk) SetOrganization(v string) *AuthOAuthStateUpsertBulk {
	return u.Update(func(s *AuthOAuthStateUpsert) {
		s.SetOrganization(v)
	})
}

// UpdateOrganization sets the "organization" field to the value that was provided on create.
func (u *AuthOAuthStateUpsertBulk) UpdateOrganization() *AuthOAuthStateUpsertBulk {
	return u.Update(func(s *AuthOAuthStateUpsert) {
		s.UpdateOrganization()
	})
}

// SetStateHash sets the "state_hash" field.
func (u *AuthOAuthStateUpsertBulk) SetStateHash(v string) *AuthOAuthStateUpsertBulk {
	return u.Update(func(s *AuthOAuthStateUpsert) {
		s.SetStateHash(v)
	})
}

// UpdateStateHash sets the "state_hash" field to the value that was provided on create.
func (u *AuthOAuthStateUpsertBulk) UpdateStateHash() *AuthOAuthStateUpsertBulk {
	return u.Update(func(s *AuthOAuthStateUpsert) {
		s.UpdateStateHash()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *AuthOAuthStateUpsertBulk) SetExpiresAt(v time.Time) *AuthOAuthStateUpsertBulk {
	return u.Update(func(s *AuthOAuthStateUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *AuthOAuthStateUpsertBulk) UpdateExpiresAt() *AuthOAuthStateUpsertBulk {
	return u.Update(func(s *AuthOAuthStateUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetConsumedAt sets the "consumed_at" field.
func (u *AuthOAuthStateUpsertBulk) SetConsumedAt(v time.Time) *AuthOAuthStateUpsertBulk {
	return u.Update(func(s *AuthOAuthStateUpsert) {
		s.SetConsumedAt(v)
	})
}

// UpdateConsumedAt sets the "consumed_at" field to the value that was provided on create.
func (u *AuthOAuthStateUpsertBulk) UpdateConsumedAt() *AuthOAuthStateUpsertBulk {
	return u.Update(func(s *AuthOAuthStateUpsert) {
		s.UpdateConsumedAt()
	})
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (u *AuthOAuthStateUpsertBulk) ClearConsumedAt() *AuthOAuthStateUpsertBulk {
	return u.Update(func(s *AuthOAuthStateUpsert) {
		s.ClearConsumedAt()
	})
}

// Exec executes the query.
func (u *AuthOAuthStateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AuthOAuthStateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuthOAuthStateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuthOAuthStateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
