// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/piglor/loom/services/loom/ent/authsession"
	"github.com/piglor/loom/services/loom/ent/predicate"
)

// AuthSessionUpdate is the builder for updating AuthSession entities.
type AuthSessionUpdate struct {
	config
	hooks    []Hook
	mutation *AuthSessionMutation
}

// Where appends a list predicates to the AuthSessionUpdate builder.
func (_u *AuthSessionUpdate) Where(ps ...predicate.AuthSession) *AuthSessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrganization sets the "organization" field.
func (_u *AuthSessionUpdate) SetOrganization(v string) *AuthSessionUpdate {
	_u.mutation.SetOrganization(v)
	return _u
}

// SetNillableOrganization sets the "organization" field if the given value is not nil.
func (_u *AuthSessionUpdate) SetNillableOrganization(v *string) *AuthSessionUpdate {
	if v != nil {
		_u.SetOrganization(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AuthSessionUpdate) SetUserID(v string) *AuthSessionUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AuthSessionUpdate) SetNillableUserID(v *string) *AuthSessionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *AuthSessionUpdate) SetTokenHash(v string) *AuthSessionUpdate {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *AuthSessionUpdate) SetNillableTokenHash(v *string) *AuthSessionUpdate {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetCsrfHash sets the "csrf_hash" field.
func (_u *AuthSessionUpdate) SetCsrfHash(v string) *AuthSessionUpdate {
	_u.mutation.SetCsrfHash(v)
	return _u
}

// SetNillableCsrfHash sets the "csrf_hash" field if the given value is not nil.
func (_u *AuthSessionUpdate) SetNillableCsrfHash(v *string) *AuthSessionUpdate {
	if v != nil {
		_u.SetCsrfHash(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AuthSessionUpdate) SetCreatedAt(v time.Time) *AuthSessionUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AuthSessionUpdate) SetNillableCreatedAt(v *time.Time) *AuthSessionUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *AuthSessionUpdate) ClearCreatedAt() *AuthSessionUpdate {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *AuthSessionUpdate) SetLastSeenAt(v time.Time) *AuthSessionUpdate {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *AuthSessionUpdate) SetNillableLastSeenAt(v *time.Time) *AuthSessionUpdate {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (_u *AuthSessionUpdate) ClearLastSeenAt() *AuthSessionUpdate {
	_u.mutation.ClearLastSeenAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AuthSessionUpdate) SetExpiresAt(v time.Time) *AuthSessionUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AuthSessionUpdate) SetNillableExpiresAt(v *time.Time) *AuthSessionUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *AuthSessionUpdate) SetRevokedAt(v time.Time) *AuthSessionUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *AuthSessionUpdate) SetNillableRevokedAt(v *time.Time) *AuthSessionUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *AuthSessionUpdate) ClearRevokedAt() *AuthSessionUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// Mutation returns the AuthSessionMutation object of the builder.
func (_u *AuthSessionUpdate) Mutation() *AuthSessionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuthSessionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuthSessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthSessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AuthSessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(authsession.Table, authsession.Columns, sqlgraph.NewFieldSpec(authsession.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Organization(); ok {
		_spec.SetField(authsession.FieldOrganization, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(authsession.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(authsession.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.CsrfHash(); ok {
		_spec.SetField(authsession.FieldCsrfHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(authsession.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(authsession.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(authsession.FieldLastSeenAt, field.TypeTime, value)
	}
	if _u.mutation.LastSeenAtCleared() {
		_spec.ClearField(authsession.FieldLastSeenAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(authsession.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(authsession.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(authsession.FieldRevokedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuthSessionUpdateOne is the builder for updating a single AuthSession entity.
type AuthSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuthSessionMutation
}

// SetOrganization sets the "organization" field.
func (_u *AuthSessionUpdateOne) SetOrganization(v string) *AuthSessionUpdateOne {
	_u.mutation.SetOrganization(v)
	return _u
}

// SetNillableOrganization sets the "organization" field if the given value is not nil.
func (_u *AuthSessionUpdateOne) SetNillableOrganization(v *string) *AuthSessionUpdateOne {
	if v != nil {
		_u.SetOrganization(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AuthSessionUpdateOne) SetUserID(v string) *AuthSessionUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AuthSessionUpdateOne) SetNillableUserID(v *string) *AuthSessionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *AuthSessionUpdateOne) SetTokenHash(v string) *AuthSessionUpdateOne {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *AuthSessionUpdateOne) SetNillableTokenHash(v *string) *AuthSessionUpdateOne {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetCsrfHash sets the "csrf_hash" field.
func (_u *AuthSessionUpdateOne) SetCsrfHash(v string) *AuthSessionUpdateOne {
	_u.mutation.SetCsrfHash(v)
	return _u
}

// SetNillableCsrfHash sets the "csrf_hash" field if the given value is not nil.
func (_u *AuthSessionUpdateOne) SetNillableCsrfHash(v *string) *AuthSessionUpdateOne {
	if v != nil {
		_u.SetCsrfHash(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AuthSessionUpdateOne) SetCreatedAt(v time.Time) *AuthSessionUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AuthSessionUpdateOne) SetNillableCreatedAt(v *time.Time) *AuthSessionUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *AuthSessionUpdateOne) ClearCreatedAt() *AuthSessionUpdateOne {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *AuthSessionUpdateOne) SetLastSeenAt(v time.Time) *AuthSessionUpdateOne {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *AuthSessionUpdateOne) SetNillableLastSeenAt(v *time.Time) *AuthSessionUpdateOne {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (_u *AuthSessionUpdateOne) ClearLastSeenAt() *AuthSessionUpdateOne {
	_u.mutation.ClearLastSeenAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AuthSessionUpdateOne) SetExpiresAt(v time.Time) *AuthSessionUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AuthSessionUpdateOne) SetNillableExpiresAt(v *time.Time) *AuthSessionUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *AuthSessionUpdateOne) SetRevokedAt(v time.Time) *AuthSessionUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *AuthSessionUpdateOne) SetNillableRevokedAt(v *time.Time) *AuthSessionUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *AuthSessionUpdateOne) ClearRevokedAt() *AuthSessionUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// Mutation returns the AuthSessionMutation object of the builder.
func (_u *AuthSessionUpdateOne) Mutation() *AuthSessionMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuthSessionUpdate builder.
func (_u *AuthSessionUpdateOne) Where(ps ...predicate.AuthSession) *AuthSessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuthSessionUpdateOne) Select(field string, fields ...string) *AuthSessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuthSession entity.
func (_u *AuthSessionUpdateOne) Save(ctx context.Context) (*AuthSession, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthSessionUpdateOne) SaveX(ctx context.Context) *AuthSession {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuthSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthSessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AuthSessionUpdateOne) sqlSave(ctx context.Context) (_node *AuthSession, err error) {
	_spec := sqlgraph.NewUpdateSpec(authsession.Table, authsession.Columns, sqlgraph.NewFieldSpec(authsession.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuthSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, authsession.FieldID)
		for _, f := range fields {
			if !authsession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != authsession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Organization(); ok {
		_spec.SetField(authsession.FieldOrganization, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(authsession.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(authsession.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.CsrfHash(); ok {
		_spec.SetField(authsession.FieldCsrfHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(authsession.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(authsession.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(authsession.FieldLastSeenAt, field.TypeTime, value)
	}
	if _u.mutation.LastSeenAtCleared() {
		_spec.ClearField(authsession.FieldLastSeenAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(authsession.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(authsession.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(authsession.FieldRevokedAt, field.TypeTime)
	}
	_node = &AuthSession{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
