// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/piglor/loom/services/loom/ent/authoauthstate"
	"github.com/piglor/loom/services/loom/ent/predicate"
)

// AuthOAuthStateUpdate is the builder for updating AuthOAuthState entities.
type AuthOAuthStateUpdate struct {
	config
	hooks    []Hook
	mutation *AuthOAuthStateMutation
}

// Where appends a list predicates to the AuthOAuthStateUpdate builder.
func (_u *AuthOAuthStateUpdate) Where(ps ...predicate.AuthOAuthState) *AuthOAuthStateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrganization sets the "organization" field.
func (_u *AuthOAuthStateUpdate) SetOrganization(v string) *AuthOAuthStateUpdate {
	_u.mutation.SetOrganization(v)
	return _u
}

// SetNillableOrganization sets the "organization" field if the given value is not nil.
func (_u *AuthOAuthStateUpdate) SetNillableOrganization(v *string) *AuthOAuthStateUpdate {
	if v != nil {
		_u.SetOrganization(*v)
	}
	return _u
}

// SetStateHash sets the "state_hash" field.
func (_u *AuthOAuthStateUpdate) SetStateHash(v string) *AuthOAuthStateUpdate {
	_u.mutation.SetStateHash(v)
	return _u
}

// SetNillableStateHash sets the "state_hash" field if the given value is not nil.
func (_u *AuthOAuthStateUpdate) SetNillableStateHash(v *string) *AuthOAuthStateUpdate {
	if v != nil {
		_u.SetStateHash(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AuthOAuthStateUpdate) SetExpiresAt(v time.Time) *AuthOAuthStateUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AuthOAuthStateUpdate) SetNillableExpiresAt(v *time.Time) *AuthOAuthStateUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *AuthOAuthStateUpdate) SetConsumedAt(v time.Time) *AuthOAuthStateUpdate {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *AuthOAuthStateUpdate) SetNillableConsumedAt(v *time.Time) *AuthOAuthStateUpdate {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *AuthOAuthStateUpdate) ClearConsumedAt() *AuthOAuthStateUpdate {
	_u.mutation.ClearConsumedAt()
	return _u
}

// Mutation returns the AuthOAuthStateMutation object of the builder.
func (_u *AuthOAuthStateUpdate) Mutation() *AuthOAuthStateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuthOAuthStateUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthOAuthStateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuthOAuthStateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthOAuthStateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AuthOAuthStateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(authoauthstate.Table, authoauthstate.Columns, sqlgraph.NewFieldSpec(authoauthstate.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Organization(); ok {
		_spec.SetField(authoauthstate.FieldOrganization, field.TypeString, value)
	}
	if value, ok := _u.mutation.StateHash(); ok {
		_spec.SetField(authoauthstate.FieldStateHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(authoauthstate.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(authoauthstate.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(authoauthstate.FieldConsumedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authoauthstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuthOAuthStateUpdateOne is the builder for updating a single AuthOAuthState entity.
type AuthOAuthStateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuthOAuthStateMutation
}

// SetOrganization sets the "organization" field.
func (_u *AuthOAuthStateUpdateOne) SetOrganization(v string) *AuthOAuthStateUpdateOne {
	_u.mutation.SetOrganization(v)
	return _u
}

// SetNillableOrganization sets the "organization" field if the given value is not nil.
func (_u *AuthOAuthStateUpdateOne) SetNillableOrganization(v *string) *AuthOAuthStateUpdateOne {
	if v != nil {
		_u.SetOrganization(*v)
	}
	return _u
}

// SetStateHash sets the "state_hash" field.
func (_u *AuthOAuthStateUpdateOne) SetStateHash(v string) *AuthOAuthStateUpdateOne {
	_u.mutation.SetStateHash(v)
	return _u
}

// SetNillableStateHash sets the "state_hash" field if the given value is not nil.
func (_u *AuthOAuthStateUpdateOne) SetNillableStateHash(v *string) *AuthOAuthStateUpdateOne {
	if v != nil {
		_u.SetStateHash(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AuthOAuthStateUpdateOne) SetExpiresAt(v time.Time) *AuthOAuthStateUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AuthOAuthStateUpdateOne) SetNillableExpiresAt(v *time.Time) *AuthOAuthStateUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *AuthOAuthStateUpdateOne) SetConsumedAt(v time.Time) *AuthOAuthStateUpdateOne {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *AuthOAuthStateUpdateOne) SetNillableConsumedAt(v *time.Time) *AuthOAuthStateUpdateOne {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *AuthOAuthStateUpdateOne) ClearConsumedAt() *AuthOAuthStateUpdateOne {
	_u.mutation.ClearConsumedAt()
	return _u
}

// Mutation returns the AuthOAuthStateMutation object of the builder.
func (_u *AuthOAuthStateUpdateOne) Mutation() *AuthOAuthStateMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuthOAuthStateUpdate builder.
func (_u *AuthOAuthStateUpdateOne) Where(ps ...predicate.AuthOAuthState) *AuthOAuthStateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuthOAuthStateUpdateOne) Select(field string, fields ...string) *AuthOAuthStateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuthOAuthState entity.
func (_u *AuthOAuthStateUpdateOne) Save(ctx context.Context) (*AuthOAuthState, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthOAuthStateUpdateOne) SaveX(ctx context.Context) *AuthOAuthState {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuthOAuthStateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthOAuthStateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AuthOAuthStateUpdateOne) sqlSave(ctx context.Context) (_node *AuthOAuthState, err error) {
	_spec := sqlgraph.NewUpdateSpec(authoauthstate.Table, authoauthstate.Columns, sqlgraph.NewFieldSpec(authoauthstate.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuthOAuthState.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, authoauthstate.FieldID)
		for _, f := range fields {
			if !authoauthstate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != authoauthstate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Organization(); ok {
		_spec.SetField(authoauthstate.FieldOrganization, field.TypeString, value)
	}
	if value, ok := _u.mutation.StateHash(); ok {
		_spec.SetField(authoauthstate.FieldStateHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(authoauthstate.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(authoauthstate.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(authoauthstate.FieldConsumedAt, field.TypeTime)
	}
	_node = &AuthOAuthState{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authoauthstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
