// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/piglor/loom/services/loom/ent/command"
)

// Command is the model entity for the Command schema.
type Command struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// GoalID holds the value of the "goal_id" field.
	GoalID string `json:"goal_id,omitempty"`
	// AttemptID holds the value of the "attempt_id" field.
	AttemptID string `json:"attempt_id,omitempty"`
	// WorkerID holds the value of the "worker_id" field.
	WorkerID string `json:"worker_id,omitempty"`
	// State holds the value of the "state" field.
	State string `json:"state,omitempty"`
	// ClaimID holds the value of the "claim_id" field.
	ClaimID *string `json:"claim_id,omitempty"`
	// ReportDigest holds the value of the "report_digest" field.
	ReportDigest *string `json:"report_digest,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// ClaimedAt holds the value of the "claimed_at" field.
	ClaimedAt *time.Time `json:"claimed_at,omitempty"`
	// StoppedAt holds the value of the "stopped_at" field.
	StoppedAt    *time.Time `json:"stopped_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Command) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case command.FieldID, command.FieldGoalID, command.FieldAttemptID, command.FieldWorkerID, command.FieldState, command.FieldClaimID, command.FieldReportDigest:
			values[i] = new(sql.NullString)
		case command.FieldCreatedAt, command.FieldClaimedAt, command.FieldStoppedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Command fields.
func (_m *Command) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case command.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case command.FieldGoalID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field goal_id", values[i])
			} else if value.Valid {
				_m.GoalID = value.String
			}
		case command.FieldAttemptID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field attempt_id", values[i])
			} else if value.Valid {
				_m.AttemptID = value.String
			}
		case command.FieldWorkerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field worker_id", values[i])
			} else if value.Valid {
				_m.WorkerID = value.String
			}
		case command.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = value.String
			}
		case command.FieldClaimID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field claim_id", values[i])
			} else if value.Valid {
				_m.ClaimID = new(string)
				*_m.ClaimID = value.String
			}
		case command.FieldReportDigest:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field report_digest", values[i])
			} else if value.Valid {
				_m.ReportDigest = new(string)
				*_m.ReportDigest = value.String
			}
		case command.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case command.FieldClaimedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field claimed_at", values[i])
			} else if value.Valid {
				_m.ClaimedAt = new(time.Time)
				*_m.ClaimedAt = value.Time
			}
		case command.FieldStoppedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field stopped_at", values[i])
			} else if value.Valid {
				_m.StoppedAt = new(time.Time)
				*_m.StoppedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Command.
// This includes values selected through modifiers, order, etc.
func (_m *Command) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Command.
// Note that you need to call Command.Unwrap() before calling this method if this Command
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Command) Update() *CommandUpdateOne {
	return NewCommandClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Command entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Command) Unwrap() *Command {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Command is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Command) String() string {
	var builder strings.Builder
	builder.WriteString("Command(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("goal_id=")
	builder.WriteString(_m.GoalID)
	builder.WriteString(", ")
	builder.WriteString("attempt_id=")
	builder.WriteString(_m.AttemptID)
	builder.WriteString(", ")
	builder.WriteString("worker_id=")
	builder.WriteString(_m.WorkerID)
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(_m.State)
	builder.WriteString(", ")
	if v := _m.ClaimID; v != nil {
		builder.WriteString("claim_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ReportDigest; v != nil {
		builder.WriteString("report_digest=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ClaimedAt; v != nil {
		builder.WriteString("claimed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.StoppedAt; v != nil {
		builder.WriteString("stopped_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Commands is a parsable slice of Command.
type Commands []*Command
