// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/piglor/loom/services/loom/ent/command"
	"github.com/piglor/loom/services/loom/ent/predicate"
)

// CommandUpdate is the builder for updating Command entities.
type CommandUpdate struct {
	config
	hooks    []Hook
	mutation *CommandMutation
}

// Where appends a list predicates to the CommandUpdate builder.
func (_u *CommandUpdate) Where(ps ...predicate.Command) *CommandUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGoalID sets the "goal_id" field.
func (_u *CommandUpdate) SetGoalID(v string) *CommandUpdate {
	_u.mutation.SetGoalID(v)
	return _u
}

// SetNillableGoalID sets the "goal_id" field if the given value is not nil.
func (_u *CommandUpdate) SetNillableGoalID(v *string) *CommandUpdate {
	if v != nil {
		_u.SetGoalID(*v)
	}
	return _u
}

// SetAttemptID sets the "attempt_id" field.
func (_u *CommandUpdate) SetAttemptID(v string) *CommandUpdate {
	_u.mutation.SetAttemptID(v)
	return _u
}

// SetNillableAttemptID sets the "attempt_id" field if the given value is not nil.
func (_u *CommandUpdate) SetNillableAttemptID(v *string) *CommandUpdate {
	if v != nil {
		_u.SetAttemptID(*v)
	}
	return _u
}

// SetWorkerID sets the "worker_id" field.
func (_u *CommandUpdate) SetWorkerID(v string) *CommandUpdate {
	_u.mutation.SetWorkerID(v)
	return _u
}

// SetNillableWorkerID sets the "worker_id" field if the given value is not nil.
func (_u *CommandUpdate) SetNillableWorkerID(v *string) *CommandUpdate {
	if v != nil {
		_u.SetWorkerID(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *CommandUpdate) SetState(v string) *CommandUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *CommandUpdate) SetNillableState(v *string) *CommandUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetClaimID sets the "claim_id" field.
func (_u *CommandUpdate) SetClaimID(v string) *CommandUpdate {
	_u.mutation.SetClaimID(v)
	return _u
}

// SetNillableClaimID sets the "claim_id" field if the given value is not nil.
func (_u *CommandUpdate) SetNillableClaimID(v *string) *CommandUpdate {
	if v != nil {
		_u.SetClaimID(*v)
	}
	return _u
}

// ClearClaimID clears the value of the "claim_id" field.
func (_u *CommandUpdate) ClearClaimID() *CommandUpdate {
	_u.mutation.ClearClaimID()
	return _u
}

// SetReportDigest sets the "report_digest" field.
func (_u *CommandUpdate) SetReportDigest(v string) *CommandUpdate {
	_u.mutation.SetReportDigest(v)
	return _u
}

// SetNillableReportDigest sets the "report_digest" field if the given value is not nil.
func (_u *CommandUpdate) SetNillableReportDigest(v *string) *CommandUpdate {
	if v != nil {
		_u.SetReportDigest(*v)
	}
	return _u
}

// ClearReportDigest clears the value of the "report_digest" field.
func (_u *CommandUpdate) ClearReportDigest() *CommandUpdate {
	_u.mutation.ClearReportDigest()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CommandUpdate) SetCreatedAt(v time.Time) *CommandUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CommandUpdate) SetNillableCreatedAt(v *time.Time) *CommandUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *CommandUpdate) ClearCreatedAt() *CommandUpdate {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetClaimedAt sets the "claimed_at" field.
func (_u *CommandUpdate) SetClaimedAt(v time.Time) *CommandUpdate {
	_u.mutation.SetClaimedAt(v)
	return _u
}

// SetNillableClaimedAt sets the "claimed_at" field if the given value is not nil.
func (_u *CommandUpdate) SetNillableClaimedAt(v *time.Time) *CommandUpdate {
	if v != nil {
		_u.SetClaimedAt(*v)
	}
	return _u
}

// ClearClaimedAt clears the value of the "claimed_at" field.
func (_u *CommandUpdate) ClearClaimedAt() *CommandUpdate {
	_u.mutation.ClearClaimedAt()
	return _u
}

// SetStoppedAt sets the "stopped_at" field.
func (_u *CommandUpdate) SetStoppedAt(v time.Time) *CommandUpdate {
	_u.mutation.SetStoppedAt(v)
	return _u
}

// SetNillableStoppedAt sets the "stopped_at" field if the given value is not nil.
func (_u *CommandUpdate) SetNillableStoppedAt(v *time.Time) *CommandUpdate {
	if v != nil {
		_u.SetStoppedAt(*v)
	}
	return _u
}

// ClearStoppedAt clears the value of the "stopped_at" field.
func (_u *CommandUpdate) ClearStoppedAt() *CommandUpdate {
	_u.mutation.ClearStoppedAt()
	return _u
}

// Mutation returns the CommandMutation object of the builder.
func (_u *CommandUpdate) Mutation() *CommandMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CommandUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CommandUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CommandUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CommandUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CommandUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(command.Table, command.Columns, sqlgraph.NewFieldSpec(command.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GoalID(); ok {
		_spec.SetField(command.FieldGoalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AttemptID(); ok {
		_spec.SetField(command.FieldAttemptID, field.TypeString, value)
	}
	if value, ok := _u.mutation.WorkerID(); ok {
		_spec.SetField(command.FieldWorkerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(command.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClaimID(); ok {
		_spec.SetField(command.FieldClaimID, field.TypeString, value)
	}
	if _u.mutation.ClaimIDCleared() {
		_spec.ClearField(command.FieldClaimID, field.TypeString)
	}
	if value, ok := _u.mutation.ReportDigest(); ok {
		_spec.SetField(command.FieldReportDigest, field.TypeString, value)
	}
	if _u.mutation.ReportDigestCleared() {
		_spec.ClearField(command.FieldReportDigest, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(command.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(command.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ClaimedAt(); ok {
		_spec.SetField(command.FieldClaimedAt, field.TypeTime, value)
	}
	if _u.mutation.ClaimedAtCleared() {
		_spec.ClearField(command.FieldClaimedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.StoppedAt(); ok {
		_spec.SetField(command.FieldStoppedAt, field.TypeTime, value)
	}
	if _u.mutation.StoppedAtCleared() {
		_spec.ClearField(command.FieldStoppedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{command.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CommandUpdateOne is the builder for updating a single Command entity.
type CommandUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CommandMutation
}

// SetGoalID sets the "goal_id" field.
func (_u *CommandUpdateOne) SetGoalID(v string) *CommandUpdateOne {
	_u.mutation.SetGoalID(v)
	return _u
}

// SetNillableGoalID sets the "goal_id" field if the given value is not nil.
func (_u *CommandUpdateOne) SetNillableGoalID(v *string) *CommandUpdateOne {
	if v != nil {
		_u.SetGoalID(*v)
	}
	return _u
}

// SetAttemptID sets the "attempt_id" field.
func (_u *CommandUpdateOne) SetAttemptID(v string) *CommandUpdateOne {
	_u.mutation.SetAttemptID(v)
	return _u
}

// SetNillableAttemptID sets the "attempt_id" field if the given value is not nil.
func (_u *CommandUpdateOne) SetNillableAttemptID(v *string) *CommandUpdateOne {
	if v != nil {
		_u.SetAttemptID(*v)
	}
	return _u
}

// SetWorkerID sets the "worker_id" field.
func (_u *CommandUpdateOne) SetWorkerID(v string) *CommandUpdateOne {
	_u.mutation.SetWorkerID(v)
	return _u
}

// SetNillableWorkerID sets the "worker_id" field if the given value is not nil.
func (_u *CommandUpdateOne) SetNillableWorkerID(v *string) *CommandUpdateOne {
	if v != nil {
		_u.SetWorkerID(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *CommandUpdateOne) SetState(v string) *CommandUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *CommandUpdateOne) SetNillableState(v *string) *CommandUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetClaimID sets the "claim_id" field.
func (_u *CommandUpdateOne) SetClaimID(v string) *CommandUpdateOne {
	_u.mutation.SetClaimID(v)
	return _u
}

// SetNillableClaimID sets the "claim_id" field if the given value is not nil.
func (_u *CommandUpdateOne) SetNillableClaimID(v *string) *CommandUpdateOne {
	if v != nil {
		_u.SetClaimID(*v)
	}
	return _u
}

// ClearClaimID clears the value of the "claim_id" field.
func (_u *CommandUpdateOne) ClearClaimID() *CommandUpdateOne {
	_u.mutation.ClearClaimID()
	return _u
}

// SetReportDigest sets the "report_digest" field.
func (_u *CommandUpdateOne) SetReportDigest(v string) *CommandUpdateOne {
	_u.mutation.SetReportDigest(v)
	return _u
}

// SetNillableReportDigest sets the "report_digest" field if the given value is not nil.
func (_u *CommandUpdateOne) SetNillableReportDigest(v *string) *CommandUpdateOne {
	if v != nil {
		_u.SetReportDigest(*v)
	}
	return _u
}

// ClearReportDigest clears the value of the "report_digest" field.
func (_u *CommandUpdateOne) ClearReportDigest() *CommandUpdateOne {
	_u.mutation.ClearReportDigest()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CommandUpdateOne) SetCreatedAt(v time.Time) *CommandUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CommandUpdateOne) SetNillableCreatedAt(v *time.Time) *CommandUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *CommandUpdateOne) ClearCreatedAt() *CommandUpdateOne {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetClaimedAt sets the "claimed_at" field.
func (_u *CommandUpdateOne) SetClaimedAt(v time.Time) *CommandUpdateOne {
	_u.mutation.SetClaimedAt(v)
	return _u
}

// SetNillableClaimedAt sets the "claimed_at" field if the given value is not nil.
func (_u *CommandUpdateOne) SetNillableClaimedAt(v *time.Time) *CommandUpdateOne {
	if v != nil {
		_u.SetClaimedAt(*v)
	}
	return _u
}

// ClearClaimedAt clears the value of the "claimed_at" field.
func (_u *CommandUpdateOne) ClearClaimedAt() *CommandUpdateOne {
	_u.mutation.ClearClaimedAt()
	return _u
}

// SetStoppedAt sets the "stopped_at" field.
func (_u *CommandUpdateOne) SetStoppedAt(v time.Time) *CommandUpdateOne {
	_u.mutation.SetStoppedAt(v)
	return _u
}

// SetNillableStoppedAt sets the "stopped_at" field if the given value is not nil.
func (_u *CommandUpdateOne) SetNillableStoppedAt(v *time.Time) *CommandUpdateOne {
	if v != nil {
		_u.SetStoppedAt(*v)
	}
	return _u
}

// ClearStoppedAt clears the value of the "stopped_at" field.
func (_u *CommandUpdateOne) ClearStoppedAt() *CommandUpdateOne {
	_u.mutation.ClearStoppedAt()
	return _u
}

// Mutation returns the CommandMutation object of the builder.
func (_u *CommandUpdateOne) Mutation() *CommandMutation {
	return _u.mutation
}

// Where appends a list predicates to the CommandUpdate builder.
func (_u *CommandUpdateOne) Where(ps ...predicate.Command) *CommandUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CommandUpdateOne) Select(field string, fields ...string) *CommandUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Command entity.
func (_u *CommandUpdateOne) Save(ctx context.Context) (*Command, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CommandUpdateOne) SaveX(ctx context.Context) *Command {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CommandUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CommandUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CommandUpdateOne) sqlSave(ctx context.Context) (_node *Command, err error) {
	_spec := sqlgraph.NewUpdateSpec(command.Table, command.Columns, sqlgraph.NewFieldSpec(command.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Command.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, command.FieldID)
		for _, f := range fields {
			if !command.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != command.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GoalID(); ok {
		_spec.SetField(command.FieldGoalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AttemptID(); ok {
		_spec.SetField(command.FieldAttemptID, field.TypeString, value)
	}
	if value, ok := _u.mutation.WorkerID(); ok {
		_spec.SetField(command.FieldWorkerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(command.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClaimID(); ok {
		_spec.SetField(command.FieldClaimID, field.TypeString, value)
	}
	if _u.mutation.ClaimIDCleared() {
		_spec.ClearField(command.FieldClaimID, field.TypeString)
	}
	if value, ok := _u.mutation.ReportDigest(); ok {
		_spec.SetField(command.FieldReportDigest, field.TypeString, value)
	}
	if _u.mutation.ReportDigestCleared() {
		_spec.ClearField(command.FieldReportDigest, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(command.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(command.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ClaimedAt(); ok {
		_spec.SetField(command.FieldClaimedAt, field.TypeTime, value)
	}
	if _u.mutation.ClaimedAtCleared() {
		_spec.ClearField(command.FieldClaimedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.StoppedAt(); ok {
		_spec.SetField(command.FieldStoppedAt, field.TypeTime, value)
	}
	if _u.mutation.StoppedAtCleared() {
		_spec.ClearField(command.FieldStoppedAt, field.TypeTime)
	}
	_node = &Command{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{command.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
