// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/piglor/loom/services/loom/ent/integrationsetupsession"
	"github.com/piglor/loom/services/loom/ent/predicate"
)

// IntegrationSetupSessionDelete is the builder for deleting a IntegrationSetupSession entity.
type IntegrationSetupSessionDelete struct {
	config
	hooks    []Hook
	mutation *IntegrationSetupSessionMutation
}

// Where appends a list predicates to the IntegrationSetupSessionDelete builder.
func (_d *IntegrationSetupSessionDelete) Where(ps ...predicate.IntegrationSetupSession) *IntegrationSetupSessionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *IntegrationSetupSessionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *IntegrationSetupSessionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *IntegrationSetupSessionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(integrationsetupsession.Table, sqlgraph.NewFieldSpec(integrationsetupsession.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// IntegrationSetupSessionDeleteOne is the builder for deleting a single IntegrationSetupSession entity.
type IntegrationSetupSessionDeleteOne struct {
	_d *IntegrationSetupSessionDelete
}

// Where appends a list predicates to the IntegrationSetupSessionDelete builder.
func (_d *IntegrationSetupSessionDeleteOne) Where(ps ...predicate.IntegrationSetupSession) *IntegrationSetupSessionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *IntegrationSetupSessionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{integrationsetupsession.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *IntegrationSetupSessionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
