// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/piglor/loom/services/loom/ent/integrationsetupsession"
	"github.com/piglor/loom/services/loom/ent/predicate"
)

// IntegrationSetupSessionUpdate is the builder for updating IntegrationSetupSession entities.
type IntegrationSetupSessionUpdate struct {
	config
	hooks    []Hook
	mutation *IntegrationSetupSessionMutation
}

// Where appends a list predicates to the IntegrationSetupSessionUpdate builder.
func (_u *IntegrationSetupSessionUpdate) Where(ps ...predicate.IntegrationSetupSession) *IntegrationSetupSessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrganization sets the "organization" field.
func (_u *IntegrationSetupSessionUpdate) SetOrganization(v string) *IntegrationSetupSessionUpdate {
	_u.mutation.SetOrganization(v)
	return _u
}

// SetNillableOrganization sets the "organization" field if the given value is not nil.
func (_u *IntegrationSetupSessionUpdate) SetNillableOrganization(v *string) *IntegrationSetupSessionUpdate {
	if v != nil {
		_u.SetOrganization(*v)
	}
	return _u
}

// SetPluginID sets the "plugin_id" field.
func (_u *IntegrationSetupSessionUpdate) SetPluginID(v string) *IntegrationSetupSessionUpdate {
	_u.mutation.SetPluginID(v)
	return _u
}

// SetNillablePluginID sets the "plugin_id" field if the given value is not nil.
func (_u *IntegrationSetupSessionUpdate) SetNillablePluginID(v *string) *IntegrationSetupSessionUpdate {
	if v != nil {
		_u.SetPluginID(*v)
	}
	return _u
}

// SetMode sets the "mode" field.
func (_u *IntegrationSetupSessionUpdate) SetMode(v string) *IntegrationSetupSessionUpdate {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *IntegrationSetupSessionUpdate) SetNillableMode(v *string) *IntegrationSetupSessionUpdate {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetStateHash sets the "state_hash" field.
func (_u *IntegrationSetupSessionUpdate) SetStateHash(v string) *IntegrationSetupSessionUpdate {
	_u.mutation.SetStateHash(v)
	return _u
}

// SetNillableStateHash sets the "state_hash" field if the given value is not nil.
func (_u *IntegrationSetupSessionUpdate) SetNillableStateHash(v *string) *IntegrationSetupSessionUpdate {
	if v != nil {
		_u.SetStateHash(*v)
	}
	return _u
}

// SetStage sets the "stage" field.
func (_u *IntegrationSetupSessionUpdate) SetStage(v string) *IntegrationSetupSessionUpdate {
	_u.mutation.SetStage(v)
	return _u
}

// SetNillableStage sets the "stage" field if the given value is not nil.
func (_u *IntegrationSetupSessionUpdate) SetNillableStage(v *string) *IntegrationSetupSessionUpdate {
	if v != nil {
		_u.SetStage(*v)
	}
	return _u
}

// SetCredentialID sets the "credential_id" field.
func (_u *IntegrationSetupSessionUpdate) SetCredentialID(v string) *IntegrationSetupSessionUpdate {
	_u.mutation.SetCredentialID(v)
	return _u
}

// SetNillableCredentialID sets the "credential_id" field if the given value is not nil.
func (_u *IntegrationSetupSessionUpdate) SetNillableCredentialID(v *string) *IntegrationSetupSessionUpdate {
	if v != nil {
		_u.SetCredentialID(*v)
	}
	return _u
}

// ClearCredentialID clears the value of the "credential_id" field.
func (_u *IntegrationSetupSessionUpdate) ClearCredentialID() *IntegrationSetupSessionUpdate {
	_u.mutation.ClearCredentialID()
	return _u
}

// SetPendingInstallationID sets the "pending_installation_id" field.
func (_u *IntegrationSetupSessionUpdate) SetPendingInstallationID(v string) *IntegrationSetupSessionUpdate {
	_u.mutation.SetPendingInstallationID(v)
	return _u
}

// SetNillablePendingInstallationID sets the "pending_installation_id" field if the given value is not nil.
func (_u *IntegrationSetupSessionUpdate) SetNillablePendingInstallationID(v *string) *IntegrationSetupSessionUpdate {
	if v != nil {
		_u.SetPendingInstallationID(*v)
	}
	return _u
}

// ClearPendingInstallationID clears the value of the "pending_installation_id" field.
func (_u *IntegrationSetupSessionUpdate) ClearPendingInstallationID() *IntegrationSetupSessionUpdate {
	_u.mutation.ClearPendingInstallationID()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *IntegrationSetupSessionUpdate) SetExpiresAt(v time.Time) *IntegrationSetupSessionUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *IntegrationSetupSessionUpdate) SetNillableExpiresAt(v *time.Time) *IntegrationSetupSessionUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *IntegrationSetupSessionUpdate) SetConsumedAt(v time.Time) *IntegrationSetupSessionUpdate {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *IntegrationSetupSessionUpdate) SetNillableConsumedAt(v *time.Time) *IntegrationSetupSessionUpdate {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *IntegrationSetupSessionUpdate) ClearConsumedAt() *IntegrationSetupSessionUpdate {
	_u.mutation.ClearConsumedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *IntegrationSetupSessionUpdate) SetCreatedAt(v time.Time) *IntegrationSetupSessionUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *IntegrationSetupSessionUpdate) SetNillableCreatedAt(v *time.Time) *IntegrationSetupSessionUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *IntegrationSetupSessionUpdate) ClearCreatedAt() *IntegrationSetupSessionUpdate {
	_u.mutation.ClearCreatedAt()
	return _u
}

// Mutation returns the IntegrationSetupSessionMutation object of the builder.
func (_u *IntegrationSetupSessionUpdate) Mutation() *IntegrationSetupSessionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *IntegrationSetupSessionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IntegrationSetupSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *IntegrationSetupSessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IntegrationSetupSessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *IntegrationSetupSessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(integrationsetupsession.Table, integrationsetupsession.Columns, sqlgraph.NewFieldSpec(integrationsetupsession.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Organization(); ok {
		_spec.SetField(integrationsetupsession.FieldOrganization, field.TypeString, value)
	}
	if value, ok := _u.mutation.PluginID(); ok {
		_spec.SetField(integrationsetupsession.FieldPluginID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(integrationsetupsession.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.StateHash(); ok {
		_spec.SetField(integrationsetupsession.FieldStateHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Stage(); ok {
		_spec.SetField(integrationsetupsession.FieldStage, field.TypeString, value)
	}
	if value, ok := _u.mutation.CredentialID(); ok {
		_spec.SetField(integrationsetupsession.FieldCredentialID, field.TypeString, value)
	}
	if _u.mutation.CredentialIDCleared() {
		_spec.ClearField(integrationsetupsession.FieldCredentialID, field.TypeString)
	}
	if value, ok := _u.mutation.PendingInstallationID(); ok {
		_spec.SetField(integrationsetupsession.FieldPendingInstallationID, field.TypeString, value)
	}
	if _u.mutation.PendingInstallationIDCleared() {
		_spec.ClearField(integrationsetupsession.FieldPendingInstallationID, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(integrationsetupsession.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(integrationsetupsession.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(integrationsetupsession.FieldConsumedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(integrationsetupsession.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(integrationsetupsession.FieldCreatedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{integrationsetupsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// IntegrationSetupSessionUpdateOne is the builder for updating a single IntegrationSetupSession entity.
type IntegrationSetupSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IntegrationSetupSessionMutation
}

// SetOrganization sets the "organization" field.
func (_u *IntegrationSetupSessionUpdateOne) SetOrganization(v string) *IntegrationSetupSessionUpdateOne {
	_u.mutation.SetOrganization(v)
	return _u
}

// SetNillableOrganization sets the "organization" field if the given value is not nil.
func (_u *IntegrationSetupSessionUpdateOne) SetNillableOrganization(v *string) *IntegrationSetupSessionUpdateOne {
	if v != nil {
		_u.SetOrganization(*v)
	}
	return _u
}

// SetPluginID sets the "plugin_id" field.
func (_u *IntegrationSetupSessionUpdateOne) SetPluginID(v string) *IntegrationSetupSessionUpdateOne {
	_u.mutation.SetPluginID(v)
	return _u
}

// SetNillablePluginID sets the "plugin_id" field if the given value is not nil.
func (_u *IntegrationSetupSessionUpdateOne) SetNillablePluginID(v *string) *IntegrationSetupSessionUpdateOne {
	if v != nil {
		_u.SetPluginID(*v)
	}
	return _u
}

// SetMode sets the "mode" field.
func (_u *IntegrationSetupSessionUpdateOne) SetMode(v string) *IntegrationSetupSessionUpdateOne {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *IntegrationSetupSessionUpdateOne) SetNillableMode(v *string) *IntegrationSetupSessionUpdateOne {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetStateHash sets the "state_hash" field.
func (_u *IntegrationSetupSessionUpdateOne) SetStateHash(v string) *IntegrationSetupSessionUpdateOne {
	_u.mutation.SetStateHash(v)
	return _u
}

// SetNillableStateHash sets the "state_hash" field if the given value is not nil.
func (_u *IntegrationSetupSessionUpdateOne) SetNillableStateHash(v *string) *IntegrationSetupSessionUpdateOne {
	if v != nil {
		_u.SetStateHash(*v)
	}
	return _u
}

// SetStage sets the "stage" field.
func (_u *IntegrationSetupSessionUpdateOne) SetStage(v string) *IntegrationSetupSessionUpdateOne {
	_u.mutation.SetStage(v)
	return _u
}

// SetNillableStage sets the "stage" field if the given value is not nil.
func (_u *IntegrationSetupSessionUpdateOne) SetNillableStage(v *string) *IntegrationSetupSessionUpdateOne {
	if v != nil {
		_u.SetStage(*v)
	}
	return _u
}

// SetCredentialID sets the "credential_id" field.
func (_u *IntegrationSetupSessionUpdateOne) SetCredentialID(v string) *IntegrationSetupSessionUpdateOne {
	_u.mutation.SetCredentialID(v)
	return _u
}

// SetNillableCredentialID sets the "credential_id" field if the given value is not nil.
func (_u *IntegrationSetupSessionUpdateOne) SetNillableCredentialID(v *string) *IntegrationSetupSessionUpdateOne {
	if v != nil {
		_u.SetCredentialID(*v)
	}
	return _u
}

// ClearCredentialID clears the value of the "credential_id" field.
func (_u *IntegrationSetupSessionUpdateOne) ClearCredentialID() *IntegrationSetupSessionUpdateOne {
	_u.mutation.ClearCredentialID()
	return _u
}

// SetPendingInstallationID sets the "pending_installation_id" field.
func (_u *IntegrationSetupSessionUpdateOne) SetPendingInstallationID(v string) *IntegrationSetupSessionUpdateOne {
	_u.mutation.SetPendingInstallationID(v)
	return _u
}

// SetNillablePendingInstallationID sets the "pending_installation_id" field if the given value is not nil.
func (_u *IntegrationSetupSessionUpdateOne) SetNillablePendingInstallationID(v *string) *IntegrationSetupSessionUpdateOne {
	if v != nil {
		_u.SetPendingInstallationID(*v)
	}
	return _u
}

// ClearPendingInstallationID clears the value of the "pending_installation_id" field.
func (_u *IntegrationSetupSessionUpdateOne) ClearPendingInstallationID() *IntegrationSetupSessionUpdateOne {
	_u.mutation.ClearPendingInstallationID()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *IntegrationSetupSessionUpdateOne) SetExpiresAt(v time.Time) *IntegrationSetupSessionUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *IntegrationSetupSessionUpdateOne) SetNillableExpiresAt(v *time.Time) *IntegrationSetupSessionUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *IntegrationSetupSessionUpdateOne) SetConsumedAt(v time.Time) *IntegrationSetupSessionUpdateOne {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *IntegrationSetupSessionUpdateOne) SetNillableConsumedAt(v *time.Time) *IntegrationSetupSessionUpdateOne {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *IntegrationSetupSessionUpdateOne) ClearConsumedAt() *IntegrationSetupSessionUpdateOne {
	_u.mutation.ClearConsumedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *IntegrationSetupSessionUpdateOne) SetCreatedAt(v time.Time) *IntegrationSetupSessionUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *IntegrationSetupSessionUpdateOne) SetNillableCreatedAt(v *time.Time) *IntegrationSetupSessionUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *IntegrationSetupSessionUpdateOne) ClearCreatedAt() *IntegrationSetupSessionUpdateOne {
	_u.mutation.ClearCreatedAt()
	return _u
}

// Mutation returns the IntegrationSetupSessionMutation object of the builder.
func (_u *IntegrationSetupSessionUpdateOne) Mutation() *IntegrationSetupSessionMutation {
	return _u.mutation
}

// Where appends a list predicates to the IntegrationSetupSessionUpdate builder.
func (_u *IntegrationSetupSessionUpdateOne) Where(ps ...predicate.IntegrationSetupSession) *IntegrationSetupSessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *IntegrationSetupSessionUpdateOne) Select(field string, fields ...string) *IntegrationSetupSessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated IntegrationSetupSession entity.
func (_u *IntegrationSetupSessionUpdateOne) Save(ctx context.Context) (*IntegrationSetupSession, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IntegrationSetupSessionUpdateOne) SaveX(ctx context.Context) *IntegrationSetupSession {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *IntegrationSetupSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IntegrationSetupSessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *IntegrationSetupSessionUpdateOne) sqlSave(ctx context.Context) (_node *IntegrationSetupSession, err error) {
	_spec := sqlgraph.NewUpdateSpec(integrationsetupsession.Table, integrationsetupsession.Columns, sqlgraph.NewFieldSpec(integrationsetupsession.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "IntegrationSetupSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, integrationsetupsession.FieldID)
		for _, f := range fields {
			if !integrationsetupsession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != integrationsetupsession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Organization(); ok {
		_spec.SetField(integrationsetupsession.FieldOrganization, field.TypeString, value)
	}
	if value, ok := _u.mutation.PluginID(); ok {
		_spec.SetField(integrationsetupsession.FieldPluginID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(integrationsetupsession.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.StateHash(); ok {
		_spec.SetField(integrationsetupsession.FieldStateHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Stage(); ok {
		_spec.SetField(integrationsetupsession.FieldStage, field.TypeString, value)
	}
	if value, ok := _u.mutation.CredentialID(); ok {
		_spec.SetField(integrationsetupsession.FieldCredentialID, field.TypeString, value)
	}
	if _u.mutation.CredentialIDCleared() {
		_spec.ClearField(integrationsetupsession.FieldCredentialID, field.TypeString)
	}
	if value, ok := _u.mutation.PendingInstallationID(); ok {
		_spec.SetField(integrationsetupsession.FieldPendingInstallationID, field.TypeString, value)
	}
	if _u.mutation.PendingInstallationIDCleared() {
		_spec.ClearField(integrationsetupsession.FieldPendingInstallationID, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(integrationsetupsession.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(integrationsetupsession.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(integrationsetupsession.FieldConsumedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(integrationsetupsession.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(integrationsetupsession.FieldCreatedAt, field.TypeTime)
	}
	_node = &IntegrationSetupSession{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{integrationsetupsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
