// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/piglor/loom/services/loom/ent/integrationcredential"
)

// IntegrationCredentialCreate is the builder for creating a IntegrationCredential entity.
type IntegrationCredentialCreate struct {
	config
	mutation *IntegrationCredentialMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOrganization sets the "organization" field.
func (_c *IntegrationCredentialCreate) SetOrganization(v string) *IntegrationCredentialCreate {
	_c.mutation.SetOrganization(v)
	return _c
}

// SetPluginID sets the "plugin_id" field.
func (_c *IntegrationCredentialCreate) SetPluginID(v string) *IntegrationCredentialCreate {
	_c.mutation.SetPluginID(v)
	return _c
}

// SetLabel sets the "label" field.
func (_c *IntegrationCredentialCreate) SetLabel(v string) *IntegrationCredentialCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetSecretReference sets the "secret_reference" field.
func (_c *IntegrationCredentialCreate) SetSecretReference(v string) *IntegrationCredentialCreate {
	_c.mutation.SetSecretReference(v)
	return _c
}

// SetSecretVersion sets the "secret_version" field.
func (_c *IntegrationCredentialCreate) SetSecretVersion(v int) *IntegrationCredentialCreate {
	_c.mutation.SetSecretVersion(v)
	return _c
}

// SetState sets the "state" field.
func (_c *IntegrationCredentialCreate) SetState(v string) *IntegrationCredentialCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *IntegrationCredentialCreate) SetCreatedAt(v time.Time) *IntegrationCredentialCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *IntegrationCredentialCreate) SetNillableCreatedAt(v *time.Time) *IntegrationCredentialCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *IntegrationCredentialCreate) SetUpdatedAt(v time.Time) *IntegrationCredentialCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *IntegrationCredentialCreate) SetNillableUpdatedAt(v *time.Time) *IntegrationCredentialCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *IntegrationCredentialCreate) SetID(v string) *IntegrationCredentialCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *IntegrationCredentialCreate) SetNillableID(v *string) *IntegrationCredentialCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the IntegrationCredentialMutation object of the builder.
func (_c *IntegrationCredentialCreate) Mutation() *IntegrationCredentialMutation {
	return _c.mutation
}

// Save creates the IntegrationCredential in the database.
func (_c *IntegrationCredentialCreate) Save(ctx context.Context) (*IntegrationCredential, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IntegrationCredentialCreate) SaveX(ctx context.Context) *IntegrationCredential {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IntegrationCredentialCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IntegrationCredentialCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *IntegrationCredentialCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := integrationcredential.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *IntegrationCredentialCreate) check() error {
	if _, ok := _c.mutation.Organization(); !ok {
		return &ValidationError{Name: "organization", err: errors.New(`ent: missing required field "IntegrationCredential.organization"`)}
	}
	if _, ok := _c.mutation.PluginID(); !ok {
		return &ValidationError{Name: "plugin_id", err: errors.New(`ent: missing required field "IntegrationCredential.plugin_id"`)}
	}
	if _, ok := _c.mutation.Label(); !ok {
		return &ValidationError{Name: "label", err: errors.New(`ent: missing required field "IntegrationCredential.label"`)}
	}
	if _, ok := _c.mutation.SecretReference(); !ok {
		return &ValidationError{Name: "secret_reference", err: errors.New(`ent: missing required field "IntegrationCredential.secret_reference"`)}
	}
	if _, ok := _c.mutation.SecretVersion(); !ok {
		return &ValidationError{Name: "secret_version", err: errors.New(`ent: missing required field "IntegrationCredential.secret_version"`)}
	}
	if v, ok := _c.mutation.SecretVersion(); ok {
		if err := integrationcredential.SecretVersionValidator(v); err != nil {
			return &ValidationError{Name: "secret_version", err: fmt.Errorf(`ent: validator failed for field "IntegrationCredential.secret_version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "IntegrationCredential.state"`)}
	}
	return nil
}

func (_c *IntegrationCredentialCreate) sqlSave(ctx context.Context) (*IntegrationCredential, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected IntegrationCredential.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IntegrationCredentialCreate) createSpec() (*IntegrationCredential, *sqlgraph.CreateSpec) {
	var (
		_node = &IntegrationCredential{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(integrationcredential.Table, sqlgraph.NewFieldSpec(integrationcredential.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Organization(); ok {
		_spec.SetField(integrationcredential.FieldOrganization, field.TypeString, value)
		_node.Organization = value
	}
	if value, ok := _c.mutation.PluginID(); ok {
		_spec.SetField(integrationcredential.FieldPluginID, field.TypeString, value)
		_node.PluginID = value
	}
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(integrationcredential.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := _c.mutation.SecretReference(); ok {
		_spec.SetField(integrationcredential.FieldSecretReference, field.TypeString, value)
		_node.SecretReference = value
	}
	if value, ok := _c.mutation.SecretVersion(); ok {
		_spec.SetField(integrationcredential.FieldSecretVersion, field.TypeInt, value)
		_node.SecretVersion = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(integrationcredential.FieldState, field.TypeString, value)
		_node.State = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(integrationcredential.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(integrationcredential.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IntegrationCredential.Create().
//		SetOrganization(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IntegrationCredentialUpsert) {
//			SetOrganization(v+v).
//		}).
//		Exec(ctx)
func (_c *IntegrationCredentialCreate) OnConflict(opts ...sql.ConflictOption) *IntegrationCredentialUpsertOne {
	_c.conflict = opts
	return &IntegrationCredentialUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IntegrationCredential.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IntegrationCredentialCreate) OnConflictColumns(columns ...string) *IntegrationCredentialUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IntegrationCredentialUpsertOne{
		create: _c,
	}
}

type (
	// IntegrationCredentialUpsertOne is the builder for "upsert"-ing
	//  one IntegrationCredential node.
	IntegrationCredentialUpsertOne struct {
		create *IntegrationCredentialCreate
	}

	// IntegrationCredentialUpsert is the "OnConflict" setter.
	IntegrationCredentialUpsert struct {
		*sql.UpdateSet
	}
)

// SetOrganization sets the "organization" field.
func (u *IntegrationCredentialUpsert) SetOrganization(v string) *IntegrationCredentialUpsert {
	u.Set(integrationcredential.FieldOrganization, v)
	return u
}

// UpdateOrganization sets the "organization" field to the value that was provided on create.
func (u *IntegrationCredentialUpsert) UpdateOrganization() *IntegrationCredentialUpsert {
	u.SetExcluded(integrationcredential.FieldOrganization)
	return u
}

// SetPluginID sets the "plugin_id" field.
func (u *IntegrationCredentialUpsert) SetPluginID(v string) *IntegrationCredentialUpsert {
	u.Set(integrationcredential.FieldPluginID, v)
	return u
}

// UpdatePluginID sets the "plugin_id" field to the value that was provided on create.
func (u *IntegrationCredentialUpsert) UpdatePluginID() *IntegrationCredentialUpsert {
	u.SetExcluded(integrationcredential.FieldPluginID)
	return u
}

// SetLabel sets the "label" field.
func (u *IntegrationCredentialUpsert) SetLabel(v string) *IntegrationCredentialUpsert {
	u.Set(integrationcredential.FieldLabel, v)
	return u
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *IntegrationCredentialUpsert) UpdateLabel() *IntegrationCredentialUpsert {
	u.SetExcluded(integrationcredential.FieldLabel)
	return u
}

// SetSecretReference sets the "secret_reference" field.
func (u *IntegrationCredentialUpsert) SetSecretReference(v string) *IntegrationCredentialUpsert {
	u.Set(integrationcredential.FieldSecretReference, v)
	return u
}

// UpdateSecretReference sets the "secret_reference" field to the value that was provided on create.
func (u *IntegrationCredentialUpsert) UpdateSecretReference() *IntegrationCredentialUpsert {
	u.SetExcluded(integrationcredential.FieldSecretReference)
	return u
}

// SetSecretVersion sets the "secret_version" field.
func (u *IntegrationCredentialUpsert) SetSecretVersion(v int) *IntegrationCredentialUpsert {
	u.Set(integrationcredential.FieldSecretVersion, v)
	return u
}

// UpdateSecretVersion sets the "secret_version" field to the value that was provided on create.
func (u *IntegrationCredentialUpsert) UpdateSecretVersion() *IntegrationCredentialUpsert {
	u.SetExcluded(integrationcredential.FieldSecretVersion)
	return u
}

// AddSecretVersion adds v to the "secret_version" field.
func (u *IntegrationCredentialUpsert) AddSecretVersion(v int) *IntegrationCredentialUpsert {
	u.Add(integrationcredential.FieldSecretVersion, v)
	return u
}

// SetState sets the "state" field.
func (u *IntegrationCredentialUpsert) SetState(v string) *IntegrationCredentialUpsert {
	u.Set(integrationcredential.FieldState, v)
	return u
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *IntegrationCredentialUpsert) UpdateState() *IntegrationCredentialUpsert {
	u.SetExcluded(integrationcredential.FieldState)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *IntegrationCredentialUpsert) SetCreatedAt(v time.Time) *IntegrationCredentialUpsert {
	u.Set(integrationcredential.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *IntegrationCredentialUpsert) UpdateCreatedAt() *IntegrationCredentialUpsert {
	u.SetExcluded(integrationcredential.FieldCreatedAt)
	return u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (u *IntegrationCredentialUpsert) ClearCreatedAt() *IntegrationCredentialUpsert {
	u.SetNull(integrationcredential.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *IntegrationCredentialUpsert) SetUpdatedAt(v time.Time) *IntegrationCredentialUpsert {
	u.Set(integrationcredential.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IntegrationCredentialUpsert) UpdateUpdatedAt() *IntegrationCredentialUpsert {
	u.SetExcluded(integrationcredential.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *IntegrationCredentialUpsert) ClearUpdatedAt() *IntegrationCredentialUpsert {
	u.SetNull(integrationcredential.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.IntegrationCredential.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(integrationcredential.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *IntegrationCredentialUpsertOne) UpdateNewValues() *IntegrationCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(integrationcredential.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IntegrationCredential.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *IntegrationCredentialUpsertOne) Ignore() *IntegrationCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IntegrationCredentialUpsertOne) DoNothing() *IntegrationCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IntegrationCredentialCreate.OnConflict
// documentation for more info.
func (u *IntegrationCredentialUpsertOne) Update(set func(*IntegrationCredentialUpsert)) *IntegrationCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IntegrationCredentialUpsert{UpdateSet: update})
	}))
	return u
}

// SetOrganization sets the "organization" field.
func (u *IntegrationCredentialUpsertOne) SetOrganization(v string) *IntegrationCredentialUpsertOne {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.SetOrganization(v)
	})
}

// UpdateOrganization sets the "organization" field to the value that was provided on create.
func (u *IntegrationCredentialUpsertOne) UpdateOrganization() *IntegrationCredentialUpsertOne {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.UpdateOrganization()
	})
}

// SetPluginID sets the "plugin_id" field.
func (u *IntegrationCredentialUpsertOne) SetPluginID(v string) *IntegrationCredentialUpsertOne {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.SetPluginID(v)
	})
}

// UpdatePluginID sets the "plugin_id" field to the value that was provided on create.
func (u *IntegrationCredentialUpsertOne) UpdatePluginID() *IntegrationCredentialUpsertOne {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.UpdatePluginID()
	})
}

// SetLabel sets the "label" field.
func (u *IntegrationCredentialUpsertOne) SetLabel(v string) *IntegrationCredentialUpsertOne {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.SetLabel(v)
	})
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *IntegrationCredentialUpsertOne) UpdateLabel() *IntegrationCredentialUpsertOne {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.UpdateLabel()
	})
}

// SetSecretReference sets the "secret_reference" field.
func (u *IntegrationCredentialUpsertOne) SetSecretReference(v string) *IntegrationCredentialUpsertOne {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.SetSecretReference(v)
	})
}

// UpdateSecretReference sets the "secret_reference" field to the value that was provided on create.
func (u *IntegrationCredentialUpsertOne) UpdateSecretReference() *IntegrationCredentialUpsertOne {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.UpdateSecretReference()
	})
}

// SetSecretVersion sets the "secret_version" field.
func (u *IntegrationCredentialUpsertOne) SetSecretVersion(v int) *IntegrationCredentialUpsertOne {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.SetSecretVersion(v)
	})
}

// AddSecretVersion adds v to the "secret_version" field.
func (u *IntegrationCredentialUpsertOne) AddSecretVersion(v int) *IntegrationCredentialUpsertOne {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.AddSecretVersion(v)
	})
}

// UpdateSecretVersion sets the "secret_version" field to the value that was provided on create.
func (u *IntegrationCredentialUpsertOne) UpdateSecretVersion() *IntegrationCredentialUpsertOne {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.UpdateSecretVersion()
	})
}

// SetState sets the "state" field.
func (u *IntegrationCredentialUpsertOne) SetState(v string) *IntegrationCredentialUpsertOne {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *IntegrationCredentialUpsertOne) UpdateState() *IntegrationCredentialUpsertOne {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.UpdateState()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *IntegrationCredentialUpsertOne) SetCreatedAt(v time.Time) *IntegrationCredentialUpsertOne {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *IntegrationCredentialUpsertOne) UpdateCreatedAt() *IntegrationCredentialUpsertOne {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.UpdateCreatedAt()
	})
}

// ClearCreatedAt clears the value of the "created_at" field.
func (u *IntegrationCredentialUpsertOne) ClearCreatedAt() *IntegrationCredentialUpsertOne {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.ClearCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *IntegrationCredentialUpsertOne) SetUpdatedAt(v time.Time) *IntegrationCredentialUpsertOne {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IntegrationCredentialUpsertOne) UpdateUpdatedAt() *IntegrationCredentialUpsertOne {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *IntegrationCredentialUpsertOne) ClearUpdatedAt() *IntegrationCredentialUpsertOne {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.ClearUpdatedAt()
	})
}

// Exec executes the query.
func (u *IntegrationCredentialUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IntegrationCredentialCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IntegrationCredentialUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *IntegrationCredentialUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: IntegrationCredentialUpsertOne.ID is not supported by MySQL driver. Use IntegrationCredentialUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *IntegrationCredentialUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// IntegrationCredentialCreateBulk is the builder for creating many IntegrationCredential entities in bulk.
type IntegrationCredentialCreateBulk struct {
	config
	err      error
	builders []*IntegrationCredentialCreate
	conflict []sql.ConflictOption
}

// Save creates the IntegrationCredential entities in the database.
func (_c *IntegrationCredentialCreateBulk) Save(ctx context.Context) ([]*IntegrationCredential, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*IntegrationCredential, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IntegrationCredentialMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IntegrationCredentialCreateBulk) SaveX(ctx context.Context) []*IntegrationCredential {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IntegrationCredentialCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IntegrationCredentialCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IntegrationCredential.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IntegrationCredentialUpsert) {
//			SetOrganization(v+v).
//		}).
//		Exec(ctx)
func (_c *IntegrationCredentialCreateBulk) OnConflict(opts ...sql.ConflictOption) *IntegrationCredentialUpsertBulk {
	_c.conflict = opts
	return &IntegrationCredentialUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IntegrationCredential.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IntegrationCredentialCreateBulk) OnConflictColumns(columns ...string) *IntegrationCredentialUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IntegrationCredentialUpsertBulk{
		create: _c,
	}
}

// IntegrationCredentialUpsertBulk is the builder for "upsert"-ing
// a bulk of IntegrationCredential nodes.
type IntegrationCredentialUpsertBulk struct {
	create *IntegrationCredentialCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.IntegrationCredential.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(integrationcredential.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *IntegrationCredentialUpsertBulk) UpdateNewValues() *IntegrationCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(integrationcredential.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IntegrationCredential.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *IntegrationCredentialUpsertBulk) Ignore() *IntegrationCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IntegrationCredentialUpsertBulk) DoNothing() *IntegrationCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IntegrationCredentialCreateBulk.OnConflict
// documentation for more info.
func (u *IntegrationCredentialUpsertBulk) Update(set func(*IntegrationCredentialUpsert)) *IntegrationCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IntegrationCredentialUpsert{UpdateSet: update})
	}))
	return u
}

// SetOrganization sets the "organization" field.
func (u *IntegrationCredentialUpsertBulk) SetOrganization(v string) *IntegrationCredentialUpsertBulk {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.SetOrganization(v)
	})
}

// UpdateOrganization sets the "organization" field to the value that was provided on create.
func (u *IntegrationCredentialUpsertBulk) UpdateOrganization() *IntegrationCredentialUpsertBulk {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.UpdateOrganization()
	})
}

// SetPluginID sets the "plugin_id" field.
func (u *IntegrationCredentialUpsertBulk) SetPluginID(v string) *IntegrationCredentialUpsertBulk {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.SetPluginID(v)
	})
}

// UpdatePluginID sets the "plugin_id" field to the value that was provided on create.
func (u *IntegrationCredentialUpsertBulk) UpdatePluginID() *IntegrationCredentialUpsertBulk {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.UpdatePluginID()
	})
}

// SetLabel sets the "label" field.
func (u *IntegrationCredentialUpsertBulk) SetLabel(v string) *IntegrationCredentialUpsertBulk {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.SetLabel(v)
	})
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *IntegrationCredentialUpsertBulk) UpdateLabel() *IntegrationCredentialUpsertBulk {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.UpdateLabel()
	})
}

// SetSecretReference sets the "secret_reference" field.
func (u *IntegrationCredentialUpsertBulk) SetSecretReference(v string) *IntegrationCredentialUpsertBulk {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.SetSecretReference(v)
	})
}

// UpdateSecretReference sets the "secret_reference" field to the value that was provided on create.
func (u *IntegrationCredentialUpsertBulk) UpdateSecretReference() *IntegrationCredentialUpsertBulk {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.UpdateSecretReference()
	})
}

// SetSecretVersion sets the "secret_version" field.
func (u *IntegrationCredentialUpsertBulk) SetSecretVersion(v int) *IntegrationCredentialUpsertBulk {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.SetSecretVersion(v)
	})
}

// AddSecretVersion adds v to the "secret_version" field.
func (u *IntegrationCredentialUpsertBulk) AddSecretVersion(v int) *IntegrationCredentialUpsertBulk {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.AddSecretVersion(v)
	})
}

// UpdateSecretVersion sets the "secret_version" field to the value that was provided on create.
func (u *IntegrationCredentialUpsertBulk) UpdateSecretVersion() *IntegrationCredentialUpsertBulk {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.UpdateSecretVersion()
	})
}

// SetState sets the "state" field.
func (u *IntegrationCredentialUpsertBulk) SetState(v string) *IntegrationCredentialUpsertBulk {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *IntegrationCredentialUpsertBulk) UpdateState() *IntegrationCredentialUpsertBulk {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.UpdateState()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *IntegrationCredentialUpsertBulk) SetCreatedAt(v time.Time) *IntegrationCredentialUpsertBulk {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *IntegrationCredentialUpsertBulk) UpdateCreatedAt() *IntegrationCredentialUpsertBulk {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.UpdateCreatedAt()
	})
}

// ClearCreatedAt clears the value of the "created_at" field.
func (u *IntegrationCredentialUpsertBulk) ClearCreatedAt() *IntegrationCredentialUpsertBulk {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.ClearCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *IntegrationCredentialUpsertBulk) SetUpdatedAt(v time.Time) *IntegrationCredentialUpsertBulk {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IntegrationCredentialUpsertBulk) UpdateUpdatedAt() *IntegrationCredentialUpsertBulk {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *IntegrationCredentialUpsertBulk) ClearUpdatedAt() *IntegrationCredentialUpsertBulk {
	return u.Update(func(s *IntegrationCredentialUpsert) {
		s.ClearUpdatedAt()
	})
}

// Exec executes the query.
func (u *IntegrationCredentialUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the IntegrationCredentialCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IntegrationCredentialCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IntegrationCredentialUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
