// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/piglor/loom/services/loom/ent/run"
)

// Run is the model entity for the Run schema.
type Run struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// GoalID holds the value of the "goal_id" field.
	GoalID string `json:"goal_id,omitempty"`
	// Policy holds the value of the "policy" field.
	Policy map[string]interface{} `json:"policy,omitempty"`
	// WorkflowID holds the value of the "workflow_id" field.
	WorkflowID *string `json:"workflow_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Run) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case run.FieldPolicy:
			values[i] = new([]byte)
		case run.FieldID, run.FieldGoalID, run.FieldWorkflowID:
			values[i] = new(sql.NullString)
		case run.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Run fields.
func (_m *Run) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case run.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case run.FieldGoalID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field goal_id", values[i])
			} else if value.Valid {
				_m.GoalID = value.String
			}
		case run.FieldPolicy:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field policy", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Policy); err != nil {
					return fmt.Errorf("unmarshal field policy: %w", err)
				}
			}
		case run.FieldWorkflowID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field workflow_id", values[i])
			} else if value.Valid {
				_m.WorkflowID = new(string)
				*_m.WorkflowID = value.String
			}
		case run.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Run.
// This includes values selected through modifiers, order, etc.
func (_m *Run) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Run.
// Note that you need to call Run.Unwrap() before calling this method if this Run
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Run) Update() *RunUpdateOne {
	return NewRunClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Run entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Run) Unwrap() *Run {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Run is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Run) String() string {
	var builder strings.Builder
	builder.WriteString("Run(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("goal_id=")
	builder.WriteString(_m.GoalID)
	builder.WriteString(", ")
	builder.WriteString("policy=")
	builder.WriteString(fmt.Sprintf("%v", _m.Policy))
	builder.WriteString(", ")
	if v := _m.WorkflowID; v != nil {
		builder.WriteString("workflow_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Runs is a parsable slice of Run.
type Runs []*Run
