// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/piglor/loom/services/loom/ent/predicate"
	"github.com/piglor/loom/services/loom/ent/run"
)

// RunUpdate is the builder for updating Run entities.
type RunUpdate struct {
	config
	hooks    []Hook
	mutation *RunMutation
}

// Where appends a list predicates to the RunUpdate builder.
func (_u *RunUpdate) Where(ps ...predicate.Run) *RunUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGoalID sets the "goal_id" field.
func (_u *RunUpdate) SetGoalID(v string) *RunUpdate {
	_u.mutation.SetGoalID(v)
	return _u
}

// SetNillableGoalID sets the "goal_id" field if the given value is not nil.
func (_u *RunUpdate) SetNillableGoalID(v *string) *RunUpdate {
	if v != nil {
		_u.SetGoalID(*v)
	}
	return _u
}

// SetPolicy sets the "policy" field.
func (_u *RunUpdate) SetPolicy(v map[string]interface{}) *RunUpdate {
	_u.mutation.SetPolicy(v)
	return _u
}

// SetContext sets the "context" field.
func (_u *RunUpdate) SetContext(v map[string]interface{}) *RunUpdate {
	_u.mutation.SetContext(v)
	return _u
}

// ClearContext clears the value of the "context" field.
func (_u *RunUpdate) ClearContext() *RunUpdate {
	_u.mutation.ClearContext()
	return _u
}

// SetWorkflowID sets the "workflow_id" field.
func (_u *RunUpdate) SetWorkflowID(v string) *RunUpdate {
	_u.mutation.SetWorkflowID(v)
	return _u
}

// SetNillableWorkflowID sets the "workflow_id" field if the given value is not nil.
func (_u *RunUpdate) SetNillableWorkflowID(v *string) *RunUpdate {
	if v != nil {
		_u.SetWorkflowID(*v)
	}
	return _u
}

// ClearWorkflowID clears the value of the "workflow_id" field.
func (_u *RunUpdate) ClearWorkflowID() *RunUpdate {
	_u.mutation.ClearWorkflowID()
	return _u
}

// SetWorkflowDefinitionID sets the "workflow_definition_id" field.
func (_u *RunUpdate) SetWorkflowDefinitionID(v string) *RunUpdate {
	_u.mutation.SetWorkflowDefinitionID(v)
	return _u
}

// SetNillableWorkflowDefinitionID sets the "workflow_definition_id" field if the given value is not nil.
func (_u *RunUpdate) SetNillableWorkflowDefinitionID(v *string) *RunUpdate {
	if v != nil {
		_u.SetWorkflowDefinitionID(*v)
	}
	return _u
}

// ClearWorkflowDefinitionID clears the value of the "workflow_definition_id" field.
func (_u *RunUpdate) ClearWorkflowDefinitionID() *RunUpdate {
	_u.mutation.ClearWorkflowDefinitionID()
	return _u
}

// SetWorkflowVersionID sets the "workflow_version_id" field.
func (_u *RunUpdate) SetWorkflowVersionID(v string) *RunUpdate {
	_u.mutation.SetWorkflowVersionID(v)
	return _u
}

// SetNillableWorkflowVersionID sets the "workflow_version_id" field if the given value is not nil.
func (_u *RunUpdate) SetNillableWorkflowVersionID(v *string) *RunUpdate {
	if v != nil {
		_u.SetWorkflowVersionID(*v)
	}
	return _u
}

// ClearWorkflowVersionID clears the value of the "workflow_version_id" field.
func (_u *RunUpdate) ClearWorkflowVersionID() *RunUpdate {
	_u.mutation.ClearWorkflowVersionID()
	return _u
}

// SetParentRunID sets the "parent_run_id" field.
func (_u *RunUpdate) SetParentRunID(v string) *RunUpdate {
	_u.mutation.SetParentRunID(v)
	return _u
}

// SetNillableParentRunID sets the "parent_run_id" field if the given value is not nil.
func (_u *RunUpdate) SetNillableParentRunID(v *string) *RunUpdate {
	if v != nil {
		_u.SetParentRunID(*v)
	}
	return _u
}

// ClearParentRunID clears the value of the "parent_run_id" field.
func (_u *RunUpdate) ClearParentRunID() *RunUpdate {
	_u.mutation.ClearParentRunID()
	return _u
}

// SetInvokingStepKey sets the "invoking_step_key" field.
func (_u *RunUpdate) SetInvokingStepKey(v string) *RunUpdate {
	_u.mutation.SetInvokingStepKey(v)
	return _u
}

// SetNillableInvokingStepKey sets the "invoking_step_key" field if the given value is not nil.
func (_u *RunUpdate) SetNillableInvokingStepKey(v *string) *RunUpdate {
	if v != nil {
		_u.SetInvokingStepKey(*v)
	}
	return _u
}

// ClearInvokingStepKey clears the value of the "invoking_step_key" field.
func (_u *RunUpdate) ClearInvokingStepKey() *RunUpdate {
	_u.mutation.ClearInvokingStepKey()
	return _u
}

// SetState sets the "state" field.
func (_u *RunUpdate) SetState(v string) *RunUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *RunUpdate) SetNillableState(v *string) *RunUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetCurrentStepKey sets the "current_step_key" field.
func (_u *RunUpdate) SetCurrentStepKey(v string) *RunUpdate {
	_u.mutation.SetCurrentStepKey(v)
	return _u
}

// SetNillableCurrentStepKey sets the "current_step_key" field if the given value is not nil.
func (_u *RunUpdate) SetNillableCurrentStepKey(v *string) *RunUpdate {
	if v != nil {
		_u.SetCurrentStepKey(*v)
	}
	return _u
}

// ClearCurrentStepKey clears the value of the "current_step_key" field.
func (_u *RunUpdate) ClearCurrentStepKey() *RunUpdate {
	_u.mutation.ClearCurrentStepKey()
	return _u
}

// SetOrchestrationReference sets the "orchestration_reference" field.
func (_u *RunUpdate) SetOrchestrationReference(v string) *RunUpdate {
	_u.mutation.SetOrchestrationReference(v)
	return _u
}

// SetNillableOrchestrationReference sets the "orchestration_reference" field if the given value is not nil.
func (_u *RunUpdate) SetNillableOrchestrationReference(v *string) *RunUpdate {
	if v != nil {
		_u.SetOrchestrationReference(*v)
	}
	return _u
}

// ClearOrchestrationReference clears the value of the "orchestration_reference" field.
func (_u *RunUpdate) ClearOrchestrationReference() *RunUpdate {
	_u.mutation.ClearOrchestrationReference()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *RunUpdate) SetCreatedAt(v time.Time) *RunUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *RunUpdate) SetNillableCreatedAt(v *time.Time) *RunUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *RunUpdate) ClearCreatedAt() *RunUpdate {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RunUpdate) SetUpdatedAt(v time.Time) *RunUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *RunUpdate) SetNillableUpdatedAt(v *time.Time) *RunUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *RunUpdate) ClearUpdatedAt() *RunUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetEndedAt sets the "ended_at" field.
func (_u *RunUpdate) SetEndedAt(v time.Time) *RunUpdate {
	_u.mutation.SetEndedAt(v)
	return _u
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_u *RunUpdate) SetNillableEndedAt(v *time.Time) *RunUpdate {
	if v != nil {
		_u.SetEndedAt(*v)
	}
	return _u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (_u *RunUpdate) ClearEndedAt() *RunUpdate {
	_u.mutation.ClearEndedAt()
	return _u
}

// Mutation returns the RunMutation object of the builder.
func (_u *RunUpdate) Mutation() *RunMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RunUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RunUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RunUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RunUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RunUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(run.Table, run.Columns, sqlgraph.NewFieldSpec(run.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GoalID(); ok {
		_spec.SetField(run.FieldGoalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Policy(); ok {
		_spec.SetField(run.FieldPolicy, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Context(); ok {
		_spec.SetField(run.FieldContext, field.TypeJSON, value)
	}
	if _u.mutation.ContextCleared() {
		_spec.ClearField(run.FieldContext, field.TypeJSON)
	}
	if value, ok := _u.mutation.WorkflowID(); ok {
		_spec.SetField(run.FieldWorkflowID, field.TypeString, value)
	}
	if _u.mutation.WorkflowIDCleared() {
		_spec.ClearField(run.FieldWorkflowID, field.TypeString)
	}
	if value, ok := _u.mutation.WorkflowDefinitionID(); ok {
		_spec.SetField(run.FieldWorkflowDefinitionID, field.TypeString, value)
	}
	if _u.mutation.WorkflowDefinitionIDCleared() {
		_spec.ClearField(run.FieldWorkflowDefinitionID, field.TypeString)
	}
	if value, ok := _u.mutation.WorkflowVersionID(); ok {
		_spec.SetField(run.FieldWorkflowVersionID, field.TypeString, value)
	}
	if _u.mutation.WorkflowVersionIDCleared() {
		_spec.ClearField(run.FieldWorkflowVersionID, field.TypeString)
	}
	if value, ok := _u.mutation.ParentRunID(); ok {
		_spec.SetField(run.FieldParentRunID, field.TypeString, value)
	}
	if _u.mutation.ParentRunIDCleared() {
		_spec.ClearField(run.FieldParentRunID, field.TypeString)
	}
	if value, ok := _u.mutation.InvokingStepKey(); ok {
		_spec.SetField(run.FieldInvokingStepKey, field.TypeString, value)
	}
	if _u.mutation.InvokingStepKeyCleared() {
		_spec.ClearField(run.FieldInvokingStepKey, field.TypeString)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(run.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.CurrentStepKey(); ok {
		_spec.SetField(run.FieldCurrentStepKey, field.TypeString, value)
	}
	if _u.mutation.CurrentStepKeyCleared() {
		_spec.ClearField(run.FieldCurrentStepKey, field.TypeString)
	}
	if value, ok := _u.mutation.OrchestrationReference(); ok {
		_spec.SetField(run.FieldOrchestrationReference, field.TypeString, value)
	}
	if _u.mutation.OrchestrationReferenceCleared() {
		_spec.ClearField(run.FieldOrchestrationReference, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(run.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(run.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(run.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(run.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EndedAt(); ok {
		_spec.SetField(run.FieldEndedAt, field.TypeTime, value)
	}
	if _u.mutation.EndedAtCleared() {
		_spec.ClearField(run.FieldEndedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{run.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RunUpdateOne is the builder for updating a single Run entity.
type RunUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RunMutation
}

// SetGoalID sets the "goal_id" field.
func (_u *RunUpdateOne) SetGoalID(v string) *RunUpdateOne {
	_u.mutation.SetGoalID(v)
	return _u
}

// SetNillableGoalID sets the "goal_id" field if the given value is not nil.
func (_u *RunUpdateOne) SetNillableGoalID(v *string) *RunUpdateOne {
	if v != nil {
		_u.SetGoalID(*v)
	}
	return _u
}

// SetPolicy sets the "policy" field.
func (_u *RunUpdateOne) SetPolicy(v map[string]interface{}) *RunUpdateOne {
	_u.mutation.SetPolicy(v)
	return _u
}

// SetContext sets the "context" field.
func (_u *RunUpdateOne) SetContext(v map[string]interface{}) *RunUpdateOne {
	_u.mutation.SetContext(v)
	return _u
}

// ClearContext clears the value of the "context" field.
func (_u *RunUpdateOne) ClearContext() *RunUpdateOne {
	_u.mutation.ClearContext()
	return _u
}

// SetWorkflowID sets the "workflow_id" field.
func (_u *RunUpdateOne) SetWorkflowID(v string) *RunUpdateOne {
	_u.mutation.SetWorkflowID(v)
	return _u
}

// SetNillableWorkflowID sets the "workflow_id" field if the given value is not nil.
func (_u *RunUpdateOne) SetNillableWorkflowID(v *string) *RunUpdateOne {
	if v != nil {
		_u.SetWorkflowID(*v)
	}
	return _u
}

// ClearWorkflowID clears the value of the "workflow_id" field.
func (_u *RunUpdateOne) ClearWorkflowID() *RunUpdateOne {
	_u.mutation.ClearWorkflowID()
	return _u
}

// SetWorkflowDefinitionID sets the "workflow_definition_id" field.
func (_u *RunUpdateOne) SetWorkflowDefinitionID(v string) *RunUpdateOne {
	_u.mutation.SetWorkflowDefinitionID(v)
	return _u
}

// SetNillableWorkflowDefinitionID sets the "workflow_definition_id" field if the given value is not nil.
func (_u *RunUpdateOne) SetNillableWorkflowDefinitionID(v *string) *RunUpdateOne {
	if v != nil {
		_u.SetWorkflowDefinitionID(*v)
	}
	return _u
}

// ClearWorkflowDefinitionID clears the value of the "workflow_definition_id" field.
func (_u *RunUpdateOne) ClearWorkflowDefinitionID() *RunUpdateOne {
	_u.mutation.ClearWorkflowDefinitionID()
	return _u
}

// SetWorkflowVersionID sets the "workflow_version_id" field.
func (_u *RunUpdateOne) SetWorkflowVersionID(v string) *RunUpdateOne {
	_u.mutation.SetWorkflowVersionID(v)
	return _u
}

// SetNillableWorkflowVersionID sets the "workflow_version_id" field if the given value is not nil.
func (_u *RunUpdateOne) SetNillableWorkflowVersionID(v *string) *RunUpdateOne {
	if v != nil {
		_u.SetWorkflowVersionID(*v)
	}
	return _u
}

// ClearWorkflowVersionID clears the value of the "workflow_version_id" field.
func (_u *RunUpdateOne) ClearWorkflowVersionID() *RunUpdateOne {
	_u.mutation.ClearWorkflowVersionID()
	return _u
}

// SetParentRunID sets the "parent_run_id" field.
func (_u *RunUpdateOne) SetParentRunID(v string) *RunUpdateOne {
	_u.mutation.SetParentRunID(v)
	return _u
}

// SetNillableParentRunID sets the "parent_run_id" field if the given value is not nil.
func (_u *RunUpdateOne) SetNillableParentRunID(v *string) *RunUpdateOne {
	if v != nil {
		_u.SetParentRunID(*v)
	}
	return _u
}

// ClearParentRunID clears the value of the "parent_run_id" field.
func (_u *RunUpdateOne) ClearParentRunID() *RunUpdateOne {
	_u.mutation.ClearParentRunID()
	return _u
}

// SetInvokingStepKey sets the "invoking_step_key" field.
func (_u *RunUpdateOne) SetInvokingStepKey(v string) *RunUpdateOne {
	_u.mutation.SetInvokingStepKey(v)
	return _u
}

// SetNillableInvokingStepKey sets the "invoking_step_key" field if the given value is not nil.
func (_u *RunUpdateOne) SetNillableInvokingStepKey(v *string) *RunUpdateOne {
	if v != nil {
		_u.SetInvokingStepKey(*v)
	}
	return _u
}

// ClearInvokingStepKey clears the value of the "invoking_step_key" field.
func (_u *RunUpdateOne) ClearInvokingStepKey() *RunUpdateOne {
	_u.mutation.ClearInvokingStepKey()
	return _u
}

// SetState sets the "state" field.
func (_u *RunUpdateOne) SetState(v string) *RunUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *RunUpdateOne) SetNillableState(v *string) *RunUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetCurrentStepKey sets the "current_step_key" field.
func (_u *RunUpdateOne) SetCurrentStepKey(v string) *RunUpdateOne {
	_u.mutation.SetCurrentStepKey(v)
	return _u
}

// SetNillableCurrentStepKey sets the "current_step_key" field if the given value is not nil.
func (_u *RunUpdateOne) SetNillableCurrentStepKey(v *string) *RunUpdateOne {
	if v != nil {
		_u.SetCurrentStepKey(*v)
	}
	return _u
}

// ClearCurrentStepKey clears the value of the "current_step_key" field.
func (_u *RunUpdateOne) ClearCurrentStepKey() *RunUpdateOne {
	_u.mutation.ClearCurrentStepKey()
	return _u
}

// SetOrchestrationReference sets the "orchestration_reference" field.
func (_u *RunUpdateOne) SetOrchestrationReference(v string) *RunUpdateOne {
	_u.mutation.SetOrchestrationReference(v)
	return _u
}

// SetNillableOrchestrationReference sets the "orchestration_reference" field if the given value is not nil.
func (_u *RunUpdateOne) SetNillableOrchestrationReference(v *string) *RunUpdateOne {
	if v != nil {
		_u.SetOrchestrationReference(*v)
	}
	return _u
}

// ClearOrchestrationReference clears the value of the "orchestration_reference" field.
func (_u *RunUpdateOne) ClearOrchestrationReference() *RunUpdateOne {
	_u.mutation.ClearOrchestrationReference()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *RunUpdateOne) SetCreatedAt(v time.Time) *RunUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *RunUpdateOne) SetNillableCreatedAt(v *time.Time) *RunUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *RunUpdateOne) ClearCreatedAt() *RunUpdateOne {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RunUpdateOne) SetUpdatedAt(v time.Time) *RunUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *RunUpdateOne) SetNillableUpdatedAt(v *time.Time) *RunUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *RunUpdateOne) ClearUpdatedAt() *RunUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetEndedAt sets the "ended_at" field.
func (_u *RunUpdateOne) SetEndedAt(v time.Time) *RunUpdateOne {
	_u.mutation.SetEndedAt(v)
	return _u
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_u *RunUpdateOne) SetNillableEndedAt(v *time.Time) *RunUpdateOne {
	if v != nil {
		_u.SetEndedAt(*v)
	}
	return _u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (_u *RunUpdateOne) ClearEndedAt() *RunUpdateOne {
	_u.mutation.ClearEndedAt()
	return _u
}

// Mutation returns the RunMutation object of the builder.
func (_u *RunUpdateOne) Mutation() *RunMutation {
	return _u.mutation
}

// Where appends a list predicates to the RunUpdate builder.
func (_u *RunUpdateOne) Where(ps ...predicate.Run) *RunUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RunUpdateOne) Select(field string, fields ...string) *RunUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Run entity.
func (_u *RunUpdateOne) Save(ctx context.Context) (*Run, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RunUpdateOne) SaveX(ctx context.Context) *Run {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RunUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RunUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RunUpdateOne) sqlSave(ctx context.Context) (_node *Run, err error) {
	_spec := sqlgraph.NewUpdateSpec(run.Table, run.Columns, sqlgraph.NewFieldSpec(run.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Run.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, run.FieldID)
		for _, f := range fields {
			if !run.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != run.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GoalID(); ok {
		_spec.SetField(run.FieldGoalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Policy(); ok {
		_spec.SetField(run.FieldPolicy, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Context(); ok {
		_spec.SetField(run.FieldContext, field.TypeJSON, value)
	}
	if _u.mutation.ContextCleared() {
		_spec.ClearField(run.FieldContext, field.TypeJSON)
	}
	if value, ok := _u.mutation.WorkflowID(); ok {
		_spec.SetField(run.FieldWorkflowID, field.TypeString, value)
	}
	if _u.mutation.WorkflowIDCleared() {
		_spec.ClearField(run.FieldWorkflowID, field.TypeString)
	}
	if value, ok := _u.mutation.WorkflowDefinitionID(); ok {
		_spec.SetField(run.FieldWorkflowDefinitionID, field.TypeString, value)
	}
	if _u.mutation.WorkflowDefinitionIDCleared() {
		_spec.ClearField(run.FieldWorkflowDefinitionID, field.TypeString)
	}
	if value, ok := _u.mutation.WorkflowVersionID(); ok {
		_spec.SetField(run.FieldWorkflowVersionID, field.TypeString, value)
	}
	if _u.mutation.WorkflowVersionIDCleared() {
		_spec.ClearField(run.FieldWorkflowVersionID, field.TypeString)
	}
	if value, ok := _u.mutation.ParentRunID(); ok {
		_spec.SetField(run.FieldParentRunID, field.TypeString, value)
	}
	if _u.mutation.ParentRunIDCleared() {
		_spec.ClearField(run.FieldParentRunID, field.TypeString)
	}
	if value, ok := _u.mutation.InvokingStepKey(); ok {
		_spec.SetField(run.FieldInvokingStepKey, field.TypeString, value)
	}
	if _u.mutation.InvokingStepKeyCleared() {
		_spec.ClearField(run.FieldInvokingStepKey, field.TypeString)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(run.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.CurrentStepKey(); ok {
		_spec.SetField(run.FieldCurrentStepKey, field.TypeString, value)
	}
	if _u.mutation.CurrentStepKeyCleared() {
		_spec.ClearField(run.FieldCurrentStepKey, field.TypeString)
	}
	if value, ok := _u.mutation.OrchestrationReference(); ok {
		_spec.SetField(run.FieldOrchestrationReference, field.TypeString, value)
	}
	if _u.mutation.OrchestrationReferenceCleared() {
		_spec.ClearField(run.FieldOrchestrationReference, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(run.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(run.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(run.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(run.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EndedAt(); ok {
		_spec.SetField(run.FieldEndedAt, field.TypeTime, value)
	}
	if _u.mutation.EndedAtCleared() {
		_spec.ClearField(run.FieldEndedAt, field.TypeTime)
	}
	_node = &Run{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{run.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
