// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/piglor/loom/services/loom/ent/attempt"
	"github.com/piglor/loom/services/loom/ent/authidentity"
	"github.com/piglor/loom/services/loom/ent/authoauthstate"
	"github.com/piglor/loom/services/loom/ent/authsession"
	"github.com/piglor/loom/services/loom/ent/command"
	"github.com/piglor/loom/services/loom/ent/event"
	"github.com/piglor/loom/services/loom/ent/goal"
	"github.com/piglor/loom/services/loom/ent/integrationbinding"
	"github.com/piglor/loom/services/loom/ent/integrationcredential"
	"github.com/piglor/loom/services/loom/ent/integrationdelivery"
	"github.com/piglor/loom/services/loom/ent/integrationinstance"
	"github.com/piglor/loom/services/loom/ent/integrationsetupsession"
	"github.com/piglor/loom/services/loom/ent/outbox"
	"github.com/piglor/loom/services/loom/ent/run"
	"github.com/piglor/loom/services/loom/ent/schema"
	"github.com/piglor/loom/services/loom/ent/session"
	"github.com/piglor/loom/services/loom/ent/user"
	"github.com/piglor/loom/services/loom/ent/wait"
	"github.com/piglor/loom/services/loom/ent/waithistory"
	"github.com/piglor/loom/services/loom/ent/worker"
	"github.com/piglor/loom/services/loom/ent/workflowdefinition"
	"github.com/piglor/loom/services/loom/ent/workflowsteprun"
	"github.com/piglor/loom/services/loom/ent/workflowtriggerbinding"
	"github.com/piglor/loom/services/loom/ent/workflowversion"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	attemptFields := schema.Attempt{}.Fields()
	_ = attemptFields
	// attemptDescID is the schema descriptor for id field.
	attemptDescID := attemptFields[0].Descriptor()
	// attempt.DefaultID holds the default value on creation for the id field.
	attempt.DefaultID = attemptDescID.Default.(func() string)
	authidentityFields := schema.AuthIdentity{}.Fields()
	_ = authidentityFields
	// authidentityDescID is the schema descriptor for id field.
	authidentityDescID := authidentityFields[0].Descriptor()
	// authidentity.DefaultID holds the default value on creation for the id field.
	authidentity.DefaultID = authidentityDescID.Default.(func() string)
	authoauthstateFields := schema.AuthOAuthState{}.Fields()
	_ = authoauthstateFields
	// authoauthstateDescID is the schema descriptor for id field.
	authoauthstateDescID := authoauthstateFields[0].Descriptor()
	// authoauthstate.DefaultID holds the default value on creation for the id field.
	authoauthstate.DefaultID = authoauthstateDescID.Default.(func() string)
	authsessionFields := schema.AuthSession{}.Fields()
	_ = authsessionFields
	// authsessionDescID is the schema descriptor for id field.
	authsessionDescID := authsessionFields[0].Descriptor()
	// authsession.DefaultID holds the default value on creation for the id field.
	authsession.DefaultID = authsessionDescID.Default.(func() string)
	commandFields := schema.Command{}.Fields()
	_ = commandFields
	// commandDescID is the schema descriptor for id field.
	commandDescID := commandFields[0].Descriptor()
	// command.DefaultID holds the default value on creation for the id field.
	command.DefaultID = commandDescID.Default.(func() string)
	eventFields := schema.Event{}.Fields()
	_ = eventFields
	// eventDescID is the schema descriptor for id field.
	eventDescID := eventFields[0].Descriptor()
	// event.DefaultID holds the default value on creation for the id field.
	event.DefaultID = eventDescID.Default.(func() string)
	goalFields := schema.Goal{}.Fields()
	_ = goalFields
	// goalDescPhase is the schema descriptor for phase field.
	goalDescPhase := goalFields[5].Descriptor()
	// goal.DefaultPhase holds the default value on creation for the phase field.
	goal.DefaultPhase = goalDescPhase.Default.(int)
	// goalDescID is the schema descriptor for id field.
	goalDescID := goalFields[0].Descriptor()
	// goal.DefaultID holds the default value on creation for the id field.
	goal.DefaultID = goalDescID.Default.(func() string)
	integrationbindingFields := schema.IntegrationBinding{}.Fields()
	_ = integrationbindingFields
	// integrationbindingDescID is the schema descriptor for id field.
	integrationbindingDescID := integrationbindingFields[0].Descriptor()
	// integrationbinding.DefaultID holds the default value on creation for the id field.
	integrationbinding.DefaultID = integrationbindingDescID.Default.(func() string)
	integrationcredentialFields := schema.IntegrationCredential{}.Fields()
	_ = integrationcredentialFields
	// integrationcredentialDescSecretVersion is the schema descriptor for secret_version field.
	integrationcredentialDescSecretVersion := integrationcredentialFields[5].Descriptor()
	// integrationcredential.SecretVersionValidator is a validator for the "secret_version" field. It is called by the builders before save.
	integrationcredential.SecretVersionValidator = integrationcredentialDescSecretVersion.Validators[0].(func(int) error)
	// integrationcredentialDescID is the schema descriptor for id field.
	integrationcredentialDescID := integrationcredentialFields[0].Descriptor()
	// integrationcredential.DefaultID holds the default value on creation for the id field.
	integrationcredential.DefaultID = integrationcredentialDescID.Default.(func() string)
	integrationdeliveryFields := schema.IntegrationDelivery{}.Fields()
	_ = integrationdeliveryFields
	// integrationdeliveryDescID is the schema descriptor for id field.
	integrationdeliveryDescID := integrationdeliveryFields[0].Descriptor()
	// integrationdelivery.DefaultID holds the default value on creation for the id field.
	integrationdelivery.DefaultID = integrationdeliveryDescID.Default.(func() string)
	integrationinstanceFields := schema.IntegrationInstance{}.Fields()
	_ = integrationinstanceFields
	// integrationinstanceDescID is the schema descriptor for id field.
	integrationinstanceDescID := integrationinstanceFields[0].Descriptor()
	// integrationinstance.DefaultID holds the default value on creation for the id field.
	integrationinstance.DefaultID = integrationinstanceDescID.Default.(func() string)
	integrationsetupsessionFields := schema.IntegrationSetupSession{}.Fields()
	_ = integrationsetupsessionFields
	// integrationsetupsessionDescID is the schema descriptor for id field.
	integrationsetupsessionDescID := integrationsetupsessionFields[0].Descriptor()
	// integrationsetupsession.DefaultID holds the default value on creation for the id field.
	integrationsetupsession.DefaultID = integrationsetupsessionDescID.Default.(func() string)
	outboxFields := schema.Outbox{}.Fields()
	_ = outboxFields
	// outboxDescStepKey is the schema descriptor for step_key field.
	outboxDescStepKey := outboxFields[3].Descriptor()
	// outbox.DefaultStepKey holds the default value on creation for the step_key field.
	outbox.DefaultStepKey = outboxDescStepKey.Default.(string)
	// outboxDescFailures is the schema descriptor for failures field.
	outboxDescFailures := outboxFields[7].Descriptor()
	// outbox.DefaultFailures holds the default value on creation for the failures field.
	outbox.DefaultFailures = outboxDescFailures.Default.(int)
	// outboxDescID is the schema descriptor for id field.
	outboxDescID := outboxFields[0].Descriptor()
	// outbox.DefaultID holds the default value on creation for the id field.
	outbox.DefaultID = outboxDescID.Default.(func() string)
	runFields := schema.Run{}.Fields()
	_ = runFields
	// runDescState is the schema descriptor for state field.
	runDescState := runFields[9].Descriptor()
	// run.DefaultState holds the default value on creation for the state field.
	run.DefaultState = runDescState.Default.(string)
	// runDescID is the schema descriptor for id field.
	runDescID := runFields[0].Descriptor()
	// run.DefaultID holds the default value on creation for the id field.
	run.DefaultID = runDescID.Default.(func() string)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescID is the schema descriptor for id field.
	sessionDescID := sessionFields[0].Descriptor()
	// session.DefaultID holds the default value on creation for the id field.
	session.DefaultID = sessionDescID.Default.(func() string)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescDisplayName is the schema descriptor for display_name field.
	userDescDisplayName := userFields[3].Descriptor()
	// user.DefaultDisplayName holds the default value on creation for the display_name field.
	user.DefaultDisplayName = userDescDisplayName.Default.(string)
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[4].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(string)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() string)
	waitFields := schema.Wait{}.Fields()
	_ = waitFields
	// waitDescGeneration is the schema descriptor for generation field.
	waitDescGeneration := waitFields[3].Descriptor()
	// wait.DefaultGeneration holds the default value on creation for the generation field.
	wait.DefaultGeneration = waitDescGeneration.Default.(int)
	// waitDescID is the schema descriptor for id field.
	waitDescID := waitFields[0].Descriptor()
	// wait.DefaultID holds the default value on creation for the id field.
	wait.DefaultID = waitDescID.Default.(func() string)
	waithistoryFields := schema.WaitHistory{}.Fields()
	_ = waithistoryFields
	// waithistoryDescID is the schema descriptor for id field.
	waithistoryDescID := waithistoryFields[0].Descriptor()
	// waithistory.DefaultID holds the default value on creation for the id field.
	waithistory.DefaultID = waithistoryDescID.Default.(func() string)
	workerFields := schema.Worker{}.Fields()
	_ = workerFields
	// workerDescID is the schema descriptor for id field.
	workerDescID := workerFields[0].Descriptor()
	// worker.DefaultID holds the default value on creation for the id field.
	worker.DefaultID = workerDescID.Default.(func() string)
	workflowdefinitionFields := schema.WorkflowDefinition{}.Fields()
	_ = workflowdefinitionFields
	// workflowdefinitionDescDescription is the schema descriptor for description field.
	workflowdefinitionDescDescription := workflowdefinitionFields[3].Descriptor()
	// workflowdefinition.DefaultDescription holds the default value on creation for the description field.
	workflowdefinition.DefaultDescription = workflowdefinitionDescDescription.Default.(string)
	// workflowdefinitionDescState is the schema descriptor for state field.
	workflowdefinitionDescState := workflowdefinitionFields[4].Descriptor()
	// workflowdefinition.DefaultState holds the default value on creation for the state field.
	workflowdefinition.DefaultState = workflowdefinitionDescState.Default.(string)
	// workflowdefinitionDescLatestVersion is the schema descriptor for latest_version field.
	workflowdefinitionDescLatestVersion := workflowdefinitionFields[6].Descriptor()
	// workflowdefinition.DefaultLatestVersion holds the default value on creation for the latest_version field.
	workflowdefinition.DefaultLatestVersion = workflowdefinitionDescLatestVersion.Default.(int)
	// workflowdefinitionDescID is the schema descriptor for id field.
	workflowdefinitionDescID := workflowdefinitionFields[0].Descriptor()
	// workflowdefinition.DefaultID holds the default value on creation for the id field.
	workflowdefinition.DefaultID = workflowdefinitionDescID.Default.(func() string)
	workflowsteprunFields := schema.WorkflowStepRun{}.Fields()
	_ = workflowsteprunFields
	// workflowsteprunDescPosition is the schema descriptor for position field.
	workflowsteprunDescPosition := workflowsteprunFields[4].Descriptor()
	// workflowsteprun.PositionValidator is a validator for the "position" field. It is called by the builders before save.
	workflowsteprun.PositionValidator = workflowsteprunDescPosition.Validators[0].(func(int) error)
	// workflowsteprunDescAttempt is the schema descriptor for attempt field.
	workflowsteprunDescAttempt := workflowsteprunFields[6].Descriptor()
	// workflowsteprun.DefaultAttempt holds the default value on creation for the attempt field.
	workflowsteprun.DefaultAttempt = workflowsteprunDescAttempt.Default.(int)
	// workflowsteprunDescID is the schema descriptor for id field.
	workflowsteprunDescID := workflowsteprunFields[0].Descriptor()
	// workflowsteprun.DefaultID holds the default value on creation for the id field.
	workflowsteprun.DefaultID = workflowsteprunDescID.Default.(func() string)
	workflowtriggerbindingFields := schema.WorkflowTriggerBinding{}.Fields()
	_ = workflowtriggerbindingFields
	// workflowtriggerbindingDescResource is the schema descriptor for resource field.
	workflowtriggerbindingDescResource := workflowtriggerbindingFields[7].Descriptor()
	// workflowtriggerbinding.DefaultResource holds the default value on creation for the resource field.
	workflowtriggerbinding.DefaultResource = workflowtriggerbindingDescResource.Default.(string)
	// workflowtriggerbindingDescVersion is the schema descriptor for version field.
	workflowtriggerbindingDescVersion := workflowtriggerbindingFields[8].Descriptor()
	// workflowtriggerbinding.DefaultVersion holds the default value on creation for the version field.
	workflowtriggerbinding.DefaultVersion = workflowtriggerbindingDescVersion.Default.(string)
	// workflowtriggerbindingDescEnabled is the schema descriptor for enabled field.
	workflowtriggerbindingDescEnabled := workflowtriggerbindingFields[9].Descriptor()
	// workflowtriggerbinding.DefaultEnabled holds the default value on creation for the enabled field.
	workflowtriggerbinding.DefaultEnabled = workflowtriggerbindingDescEnabled.Default.(bool)
	// workflowtriggerbindingDescID is the schema descriptor for id field.
	workflowtriggerbindingDescID := workflowtriggerbindingFields[0].Descriptor()
	// workflowtriggerbinding.DefaultID holds the default value on creation for the id field.
	workflowtriggerbinding.DefaultID = workflowtriggerbindingDescID.Default.(func() string)
	workflowversionFields := schema.WorkflowVersion{}.Fields()
	_ = workflowversionFields
	// workflowversionDescVersion is the schema descriptor for version field.
	workflowversionDescVersion := workflowversionFields[3].Descriptor()
	// workflowversion.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	workflowversion.VersionValidator = workflowversionDescVersion.Validators[0].(func(int) error)
	// workflowversionDescID is the schema descriptor for id field.
	workflowversionDescID := workflowversionFields[0].Descriptor()
	// workflowversion.DefaultID holds the default value on creation for the id field.
	workflowversion.DefaultID = workflowversionDescID.Default.(func() string)
}
