// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/piglor/loom/services/loom/ent/waithistory"
)

// WaitHistoryCreate is the builder for creating a WaitHistory entity.
type WaitHistoryCreate struct {
	config
	mutation *WaitHistoryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetGoalID sets the "goal_id" field.
func (_c *WaitHistoryCreate) SetGoalID(v string) *WaitHistoryCreate {
	_c.mutation.SetGoalID(v)
	return _c
}

// SetRunID sets the "run_id" field.
func (_c *WaitHistoryCreate) SetRunID(v string) *WaitHistoryCreate {
	_c.mutation.SetRunID(v)
	return _c
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (_c *WaitHistoryCreate) SetNillableRunID(v *string) *WaitHistoryCreate {
	if v != nil {
		_c.SetRunID(*v)
	}
	return _c
}

// SetGeneration sets the "generation" field.
func (_c *WaitHistoryCreate) SetGeneration(v int) *WaitHistoryCreate {
	_c.mutation.SetGeneration(v)
	return _c
}

// SetCondition sets the "condition" field.
func (_c *WaitHistoryCreate) SetCondition(v map[string]interface{}) *WaitHistoryCreate {
	_c.mutation.SetCondition(v)
	return _c
}

// SetArmedAt sets the "armed_at" field.
func (_c *WaitHistoryCreate) SetArmedAt(v time.Time) *WaitHistoryCreate {
	_c.mutation.SetArmedAt(v)
	return _c
}

// SetNillableArmedAt sets the "armed_at" field if the given value is not nil.
func (_c *WaitHistoryCreate) SetNillableArmedAt(v *time.Time) *WaitHistoryCreate {
	if v != nil {
		_c.SetArmedAt(*v)
	}
	return _c
}

// SetSatisfiedAt sets the "satisfied_at" field.
func (_c *WaitHistoryCreate) SetSatisfiedAt(v time.Time) *WaitHistoryCreate {
	_c.mutation.SetSatisfiedAt(v)
	return _c
}

// SetNillableSatisfiedAt sets the "satisfied_at" field if the given value is not nil.
func (_c *WaitHistoryCreate) SetNillableSatisfiedAt(v *time.Time) *WaitHistoryCreate {
	if v != nil {
		_c.SetSatisfiedAt(*v)
	}
	return _c
}

// SetEventID sets the "event_id" field.
func (_c *WaitHistoryCreate) SetEventID(v string) *WaitHistoryCreate {
	_c.mutation.SetEventID(v)
	return _c
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (_c *WaitHistoryCreate) SetNillableEventID(v *string) *WaitHistoryCreate {
	if v != nil {
		_c.SetEventID(*v)
	}
	return _c
}

// SetClosedAt sets the "closed_at" field.
func (_c *WaitHistoryCreate) SetClosedAt(v time.Time) *WaitHistoryCreate {
	_c.mutation.SetClosedAt(v)
	return _c
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_c *WaitHistoryCreate) SetNillableClosedAt(v *time.Time) *WaitHistoryCreate {
	if v != nil {
		_c.SetClosedAt(*v)
	}
	return _c
}

// SetPreparedByAttempt sets the "prepared_by_attempt" field.
func (_c *WaitHistoryCreate) SetPreparedByAttempt(v string) *WaitHistoryCreate {
	_c.mutation.SetPreparedByAttempt(v)
	return _c
}

// SetNillablePreparedByAttempt sets the "prepared_by_attempt" field if the given value is not nil.
func (_c *WaitHistoryCreate) SetNillablePreparedByAttempt(v *string) *WaitHistoryCreate {
	if v != nil {
		_c.SetPreparedByAttempt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *WaitHistoryCreate) SetID(v string) *WaitHistoryCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *WaitHistoryCreate) SetNillableID(v *string) *WaitHistoryCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the WaitHistoryMutation object of the builder.
func (_c *WaitHistoryCreate) Mutation() *WaitHistoryMutation {
	return _c.mutation
}

// Save creates the WaitHistory in the database.
func (_c *WaitHistoryCreate) Save(ctx context.Context) (*WaitHistory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WaitHistoryCreate) SaveX(ctx context.Context) *WaitHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WaitHistoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WaitHistoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WaitHistoryCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := waithistory.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WaitHistoryCreate) check() error {
	if _, ok := _c.mutation.GoalID(); !ok {
		return &ValidationError{Name: "goal_id", err: errors.New(`ent: missing required field "WaitHistory.goal_id"`)}
	}
	if _, ok := _c.mutation.Generation(); !ok {
		return &ValidationError{Name: "generation", err: errors.New(`ent: missing required field "WaitHistory.generation"`)}
	}
	if _, ok := _c.mutation.Condition(); !ok {
		return &ValidationError{Name: "condition", err: errors.New(`ent: missing required field "WaitHistory.condition"`)}
	}
	return nil
}

func (_c *WaitHistoryCreate) sqlSave(ctx context.Context) (*WaitHistory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected WaitHistory.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WaitHistoryCreate) createSpec() (*WaitHistory, *sqlgraph.CreateSpec) {
	var (
		_node = &WaitHistory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(waithistory.Table, sqlgraph.NewFieldSpec(waithistory.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.GoalID(); ok {
		_spec.SetField(waithistory.FieldGoalID, field.TypeString, value)
		_node.GoalID = value
	}
	if value, ok := _c.mutation.RunID(); ok {
		_spec.SetField(waithistory.FieldRunID, field.TypeString, value)
		_node.RunID = &value
	}
	if value, ok := _c.mutation.Generation(); ok {
		_spec.SetField(waithistory.FieldGeneration, field.TypeInt, value)
		_node.Generation = value
	}
	if value, ok := _c.mutation.Condition(); ok {
		_spec.SetField(waithistory.FieldCondition, field.TypeJSON, value)
		_node.Condition = value
	}
	if value, ok := _c.mutation.ArmedAt(); ok {
		_spec.SetField(waithistory.FieldArmedAt, field.TypeTime, value)
		_node.ArmedAt = &value
	}
	if value, ok := _c.mutation.SatisfiedAt(); ok {
		_spec.SetField(waithistory.FieldSatisfiedAt, field.TypeTime, value)
		_node.SatisfiedAt = &value
	}
	if value, ok := _c.mutation.EventID(); ok {
		_spec.SetField(waithistory.FieldEventID, field.TypeString, value)
		_node.EventID = &value
	}
	if value, ok := _c.mutation.ClosedAt(); ok {
		_spec.SetField(waithistory.FieldClosedAt, field.TypeTime, value)
		_node.ClosedAt = &value
	}
	if value, ok := _c.mutation.PreparedByAttempt(); ok {
		_spec.SetField(waithistory.FieldPreparedByAttempt, field.TypeString, value)
		_node.PreparedByAttempt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WaitHistory.Create().
//		SetGoalID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WaitHistoryUpsert) {
//			SetGoalID(v+v).
//		}).
//		Exec(ctx)
func (_c *WaitHistoryCreate) OnConflict(opts ...sql.ConflictOption) *WaitHistoryUpsertOne {
	_c.conflict = opts
	return &WaitHistoryUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WaitHistory.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WaitHistoryCreate) OnConflictColumns(columns ...string) *WaitHistoryUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WaitHistoryUpsertOne{
		create: _c,
	}
}

type (
	// WaitHistoryUpsertOne is the builder for "upsert"-ing
	//  one WaitHistory node.
	WaitHistoryUpsertOne struct {
		create *WaitHistoryCreate
	}

	// WaitHistoryUpsert is the "OnConflict" setter.
	WaitHistoryUpsert struct {
		*sql.UpdateSet
	}
)

// SetGoalID sets the "goal_id" field.
func (u *WaitHistoryUpsert) SetGoalID(v string) *WaitHistoryUpsert {
	u.Set(waithistory.FieldGoalID, v)
	return u
}

// UpdateGoalID sets the "goal_id" field to the value that was provided on create.
func (u *WaitHistoryUpsert) UpdateGoalID() *WaitHistoryUpsert {
	u.SetExcluded(waithistory.FieldGoalID)
	return u
}

// SetRunID sets the "run_id" field.
func (u *WaitHistoryUpsert) SetRunID(v string) *WaitHistoryUpsert {
	u.Set(waithistory.FieldRunID, v)
	return u
}

// UpdateRunID sets the "run_id" field to the value that was provided on create.
func (u *WaitHistoryUpsert) UpdateRunID() *WaitHistoryUpsert {
	u.SetExcluded(waithistory.FieldRunID)
	return u
}

// ClearRunID clears the value of the "run_id" field.
func (u *WaitHistoryUpsert) ClearRunID() *WaitHistoryUpsert {
	u.SetNull(waithistory.FieldRunID)
	return u
}

// SetGeneration sets the "generation" field.
func (u *WaitHistoryUpsert) SetGeneration(v int) *WaitHistoryUpsert {
	u.Set(waithistory.FieldGeneration, v)
	return u
}

// UpdateGeneration sets the "generation" field to the value that was provided on create.
func (u *WaitHistoryUpsert) UpdateGeneration() *WaitHistoryUpsert {
	u.SetExcluded(waithistory.FieldGeneration)
	return u
}

// AddGeneration adds v to the "generation" field.
func (u *WaitHistoryUpsert) AddGeneration(v int) *WaitHistoryUpsert {
	u.Add(waithistory.FieldGeneration, v)
	return u
}

// SetCondition sets the "condition" field.
func (u *WaitHistoryUpsert) SetCondition(v map[string]interface{}) *WaitHistoryUpsert {
	u.Set(waithistory.FieldCondition, v)
	return u
}

// UpdateCondition sets the "condition" field to the value that was provided on create.
func (u *WaitHistoryUpsert) UpdateCondition() *WaitHistoryUpsert {
	u.SetExcluded(waithistory.FieldCondition)
	return u
}

// SetArmedAt sets the "armed_at" field.
func (u *WaitHistoryUpsert) SetArmedAt(v time.Time) *WaitHistoryUpsert {
	u.Set(waithistory.FieldArmedAt, v)
	return u
}

// UpdateArmedAt sets the "armed_at" field to the value that was provided on create.
func (u *WaitHistoryUpsert) UpdateArmedAt() *WaitHistoryUpsert {
	u.SetExcluded(waithistory.FieldArmedAt)
	return u
}

// ClearArmedAt clears the value of the "armed_at" field.
func (u *WaitHistoryUpsert) ClearArmedAt() *WaitHistoryUpsert {
	u.SetNull(waithistory.FieldArmedAt)
	return u
}

// SetSatisfiedAt sets the "satisfied_at" field.
func (u *WaitHistoryUpsert) SetSatisfiedAt(v time.Time) *WaitHistoryUpsert {
	u.Set(waithistory.FieldSatisfiedAt, v)
	return u
}

// UpdateSatisfiedAt sets the "satisfied_at" field to the value that was provided on create.
func (u *WaitHistoryUpsert) UpdateSatisfiedAt() *WaitHistoryUpsert {
	u.SetExcluded(waithistory.FieldSatisfiedAt)
	return u
}

// ClearSatisfiedAt clears the value of the "satisfied_at" field.
func (u *WaitHistoryUpsert) ClearSatisfiedAt() *WaitHistoryUpsert {
	u.SetNull(waithistory.FieldSatisfiedAt)
	return u
}

// SetEventID sets the "event_id" field.
func (u *WaitHistoryUpsert) SetEventID(v string) *WaitHistoryUpsert {
	u.Set(waithistory.FieldEventID, v)
	return u
}

// UpdateEventID sets the "event_id" field to the value that was provided on create.
func (u *WaitHistoryUpsert) UpdateEventID() *WaitHistoryUpsert {
	u.SetExcluded(waithistory.FieldEventID)
	return u
}

// ClearEventID clears the value of the "event_id" field.
func (u *WaitHistoryUpsert) ClearEventID() *WaitHistoryUpsert {
	u.SetNull(waithistory.FieldEventID)
	return u
}

// SetClosedAt sets the "closed_at" field.
func (u *WaitHistoryUpsert) SetClosedAt(v time.Time) *WaitHistoryUpsert {
	u.Set(waithistory.FieldClosedAt, v)
	return u
}

// UpdateClosedAt sets the "closed_at" field to the value that was provided on create.
func (u *WaitHistoryUpsert) UpdateClosedAt() *WaitHistoryUpsert {
	u.SetExcluded(waithistory.FieldClosedAt)
	return u
}

// ClearClosedAt clears the value of the "closed_at" field.
func (u *WaitHistoryUpsert) ClearClosedAt() *WaitHistoryUpsert {
	u.SetNull(waithistory.FieldClosedAt)
	return u
}

// SetPreparedByAttempt sets the "prepared_by_attempt" field.
func (u *WaitHistoryUpsert) SetPreparedByAttempt(v string) *WaitHistoryUpsert {
	u.Set(waithistory.FieldPreparedByAttempt, v)
	return u
}

// UpdatePreparedByAttempt sets the "prepared_by_attempt" field to the value that was provided on create.
func (u *WaitHistoryUpsert) UpdatePreparedByAttempt() *WaitHistoryUpsert {
	u.SetExcluded(waithistory.FieldPreparedByAttempt)
	return u
}

// ClearPreparedByAttempt clears the value of the "prepared_by_attempt" field.
func (u *WaitHistoryUpsert) ClearPreparedByAttempt() *WaitHistoryUpsert {
	u.SetNull(waithistory.FieldPreparedByAttempt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.WaitHistory.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(waithistory.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *WaitHistoryUpsertOne) UpdateNewValues() *WaitHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(waithistory.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WaitHistory.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *WaitHistoryUpsertOne) Ignore() *WaitHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WaitHistoryUpsertOne) DoNothing() *WaitHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WaitHistoryCreate.OnConflict
// documentation for more info.
func (u *WaitHistoryUpsertOne) Update(set func(*WaitHistoryUpsert)) *WaitHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WaitHistoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetGoalID sets the "goal_id" field.
func (u *WaitHistoryUpsertOne) SetGoalID(v string) *WaitHistoryUpsertOne {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.SetGoalID(v)
	})
}

// UpdateGoalID sets the "goal_id" field to the value that was provided on create.
func (u *WaitHistoryUpsertOne) UpdateGoalID() *WaitHistoryUpsertOne {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.UpdateGoalID()
	})
}

// SetRunID sets the "run_id" field.
func (u *WaitHistoryUpsertOne) SetRunID(v string) *WaitHistoryUpsertOne {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.SetRunID(v)
	})
}

// UpdateRunID sets the "run_id" field to the value that was provided on create.
func (u *WaitHistoryUpsertOne) UpdateRunID() *WaitHistoryUpsertOne {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.UpdateRunID()
	})
}

// ClearRunID clears the value of the "run_id" field.
func (u *WaitHistoryUpsertOne) ClearRunID() *WaitHistoryUpsertOne {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.ClearRunID()
	})
}

// SetGeneration sets the "generation" field.
func (u *WaitHistoryUpsertOne) SetGeneration(v int) *WaitHistoryUpsertOne {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.SetGeneration(v)
	})
}

// AddGeneration adds v to the "generation" field.
func (u *WaitHistoryUpsertOne) AddGeneration(v int) *WaitHistoryUpsertOne {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.AddGeneration(v)
	})
}

// UpdateGeneration sets the "generation" field to the value that was provided on create.
func (u *WaitHistoryUpsertOne) UpdateGeneration() *WaitHistoryUpsertOne {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.UpdateGeneration()
	})
}

// SetCondition sets the "condition" field.
func (u *WaitHistoryUpsertOne) SetCondition(v map[string]interface{}) *WaitHistoryUpsertOne {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.SetCondition(v)
	})
}

// UpdateCondition sets the "condition" field to the value that was provided on create.
func (u *WaitHistoryUpsertOne) UpdateCondition() *WaitHistoryUpsertOne {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.UpdateCondition()
	})
}

// SetArmedAt sets the "armed_at" field.
func (u *WaitHistoryUpsertOne) SetArmedAt(v time.Time) *WaitHistoryUpsertOne {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.SetArmedAt(v)
	})
}

// UpdateArmedAt sets the "armed_at" field to the value that was provided on create.
func (u *WaitHistoryUpsertOne) UpdateArmedAt() *WaitHistoryUpsertOne {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.UpdateArmedAt()
	})
}

// ClearArmedAt clears the value of the "armed_at" field.
func (u *WaitHistoryUpsertOne) ClearArmedAt() *WaitHistoryUpsertOne {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.ClearArmedAt()
	})
}

// SetSatisfiedAt sets the "satisfied_at" field.
func (u *WaitHistoryUpsertOne) SetSatisfiedAt(v time.Time) *WaitHistoryUpsertOne {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.SetSatisfiedAt(v)
	})
}

// UpdateSatisfiedAt sets the "satisfied_at" field to the value that was provided on create.
func (u *WaitHistoryUpsertOne) UpdateSatisfiedAt() *WaitHistoryUpsertOne {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.UpdateSatisfiedAt()
	})
}

// ClearSatisfiedAt clears the value of the "satisfied_at" field.
func (u *WaitHistoryUpsertOne) ClearSatisfiedAt() *WaitHistoryUpsertOne {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.ClearSatisfiedAt()
	})
}

// SetEventID sets the "event_id" field.
func (u *WaitHistoryUpsertOne) SetEventID(v string) *WaitHistoryUpsertOne {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.SetEventID(v)
	})
}

// UpdateEventID sets the "event_id" field to the value that was provided on create.
func (u *WaitHistoryUpsertOne) UpdateEventID() *WaitHistoryUpsertOne {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.UpdateEventID()
	})
}

// ClearEventID clears the value of the "event_id" field.
func (u *WaitHistoryUpsertOne) ClearEventID() *WaitHistoryUpsertOne {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.ClearEventID()
	})
}

// SetClosedAt sets the "closed_at" field.
func (u *WaitHistoryUpsertOne) SetClosedAt(v time.Time) *WaitHistoryUpsertOne {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.SetClosedAt(v)
	})
}

// UpdateClosedAt sets the "closed_at" field to the value that was provided on create.
func (u *WaitHistoryUpsertOne) UpdateClosedAt() *WaitHistoryUpsertOne {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.UpdateClosedAt()
	})
}

// ClearClosedAt clears the value of the "closed_at" field.
func (u *WaitHistoryUpsertOne) ClearClosedAt() *WaitHistoryUpsertOne {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.ClearClosedAt()
	})
}

// SetPreparedByAttempt sets the "prepared_by_attempt" field.
func (u *WaitHistoryUpsertOne) SetPreparedByAttempt(v string) *WaitHistoryUpsertOne {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.SetPreparedByAttempt(v)
	})
}

// UpdatePreparedByAttempt sets the "prepared_by_attempt" field to the value that was provided on create.
func (u *WaitHistoryUpsertOne) UpdatePreparedByAttempt() *WaitHistoryUpsertOne {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.UpdatePreparedByAttempt()
	})
}

// ClearPreparedByAttempt clears the value of the "prepared_by_attempt" field.
func (u *WaitHistoryUpsertOne) ClearPreparedByAttempt() *WaitHistoryUpsertOne {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.ClearPreparedByAttempt()
	})
}

// Exec executes the query.
func (u *WaitHistoryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WaitHistoryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WaitHistoryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *WaitHistoryUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: WaitHistoryUpsertOne.ID is not supported by MySQL driver. Use WaitHistoryUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *WaitHistoryUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// WaitHistoryCreateBulk is the builder for creating many WaitHistory entities in bulk.
type WaitHistoryCreateBulk struct {
	config
	err      error
	builders []*WaitHistoryCreate
	conflict []sql.ConflictOption
}

// Save creates the WaitHistory entities in the database.
func (_c *WaitHistoryCreateBulk) Save(ctx context.Context) ([]*WaitHistory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WaitHistory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WaitHistoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WaitHistoryCreateBulk) SaveX(ctx context.Context) []*WaitHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WaitHistoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WaitHistoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WaitHistory.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WaitHistoryUpsert) {
//			SetGoalID(v+v).
//		}).
//		Exec(ctx)
func (_c *WaitHistoryCreateBulk) OnConflict(opts ...sql.ConflictOption) *WaitHistoryUpsertBulk {
	_c.conflict = opts
	return &WaitHistoryUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WaitHistory.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WaitHistoryCreateBulk) OnConflictColumns(columns ...string) *WaitHistoryUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WaitHistoryUpsertBulk{
		create: _c,
	}
}

// WaitHistoryUpsertBulk is the builder for "upsert"-ing
// a bulk of WaitHistory nodes.
type WaitHistoryUpsertBulk struct {
	create *WaitHistoryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.WaitHistory.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(waithistory.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *WaitHistoryUpsertBulk) UpdateNewValues() *WaitHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(waithistory.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WaitHistory.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *WaitHistoryUpsertBulk) Ignore() *WaitHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WaitHistoryUpsertBulk) DoNothing() *WaitHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WaitHistoryCreateBulk.OnConflict
// documentation for more info.
func (u *WaitHistoryUpsertBulk) Update(set func(*WaitHistoryUpsert)) *WaitHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WaitHistoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetGoalID sets the "goal_id" field.
func (u *WaitHistoryUpsertBulk) SetGoalID(v string) *WaitHistoryUpsertBulk {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.SetGoalID(v)
	})
}

// UpdateGoalID sets the "goal_id" field to the value that was provided on create.
func (u *WaitHistoryUpsertBulk) UpdateGoalID() *WaitHistoryUpsertBulk {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.UpdateGoalID()
	})
}

// SetRunID sets the "run_id" field.
func (u *WaitHistoryUpsertBulk) SetRunID(v string) *WaitHistoryUpsertBulk {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.SetRunID(v)
	})
}

// UpdateRunID sets the "run_id" field to the value that was provided on create.
func (u *WaitHistoryUpsertBulk) UpdateRunID() *WaitHistoryUpsertBulk {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.UpdateRunID()
	})
}

// ClearRunID clears the value of the "run_id" field.
func (u *WaitHistoryUpsertBulk) ClearRunID() *WaitHistoryUpsertBulk {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.ClearRunID()
	})
}

// SetGeneration sets the "generation" field.
func (u *WaitHistoryUpsertBulk) SetGeneration(v int) *WaitHistoryUpsertBulk {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.SetGeneration(v)
	})
}

// AddGeneration adds v to the "generation" field.
func (u *WaitHistoryUpsertBulk) AddGeneration(v int) *WaitHistoryUpsertBulk {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.AddGeneration(v)
	})
}

// UpdateGeneration sets the "generation" field to the value that was provided on create.
func (u *WaitHistoryUpsertBulk) UpdateGeneration() *WaitHistoryUpsertBulk {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.UpdateGeneration()
	})
}

// SetCondition sets the "condition" field.
func (u *WaitHistoryUpsertBulk) SetCondition(v map[string]interface{}) *WaitHistoryUpsertBulk {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.SetCondition(v)
	})
}

// UpdateCondition sets the "condition" field to the value that was provided on create.
func (u *WaitHistoryUpsertBulk) UpdateCondition() *WaitHistoryUpsertBulk {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.UpdateCondition()
	})
}

// SetArmedAt sets the "armed_at" field.
func (u *WaitHistoryUpsertBulk) SetArmedAt(v time.Time) *WaitHistoryUpsertBulk {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.SetArmedAt(v)
	})
}

// UpdateArmedAt sets the "armed_at" field to the value that was provided on create.
func (u *WaitHistoryUpsertBulk) UpdateArmedAt() *WaitHistoryUpsertBulk {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.UpdateArmedAt()
	})
}

// ClearArmedAt clears the value of the "armed_at" field.
func (u *WaitHistoryUpsertBulk) ClearArmedAt() *WaitHistoryUpsertBulk {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.ClearArmedAt()
	})
}

// SetSatisfiedAt sets the "satisfied_at" field.
func (u *WaitHistoryUpsertBulk) SetSatisfiedAt(v time.Time) *WaitHistoryUpsertBulk {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.SetSatisfiedAt(v)
	})
}

// UpdateSatisfiedAt sets the "satisfied_at" field to the value that was provided on create.
func (u *WaitHistoryUpsertBulk) UpdateSatisfiedAt() *WaitHistoryUpsertBulk {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.UpdateSatisfiedAt()
	})
}

// ClearSatisfiedAt clears the value of the "satisfied_at" field.
func (u *WaitHistoryUpsertBulk) ClearSatisfiedAt() *WaitHistoryUpsertBulk {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.ClearSatisfiedAt()
	})
}

// SetEventID sets the "event_id" field.
func (u *WaitHistoryUpsertBulk) SetEventID(v string) *WaitHistoryUpsertBulk {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.SetEventID(v)
	})
}

// UpdateEventID sets the "event_id" field to the value that was provided on create.
func (u *WaitHistoryUpsertBulk) UpdateEventID() *WaitHistoryUpsertBulk {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.UpdateEventID()
	})
}

// ClearEventID clears the value of the "event_id" field.
func (u *WaitHistoryUpsertBulk) ClearEventID() *WaitHistoryUpsertBulk {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.ClearEventID()
	})
}

// SetClosedAt sets the "closed_at" field.
func (u *WaitHistoryUpsertBulk) SetClosedAt(v time.Time) *WaitHistoryUpsertBulk {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.SetClosedAt(v)
	})
}

// UpdateClosedAt sets the "closed_at" field to the value that was provided on create.
func (u *WaitHistoryUpsertBulk) UpdateClosedAt() *WaitHistoryUpsertBulk {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.UpdateClosedAt()
	})
}

// ClearClosedAt clears the value of the "closed_at" field.
func (u *WaitHistoryUpsertBulk) ClearClosedAt() *WaitHistoryUpsertBulk {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.ClearClosedAt()
	})
}

// SetPreparedByAttempt sets the "prepared_by_attempt" field.
func (u *WaitHistoryUpsertBulk) SetPreparedByAttempt(v string) *WaitHistoryUpsertBulk {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.SetPreparedByAttempt(v)
	})
}

// UpdatePreparedByAttempt sets the "prepared_by_attempt" field to the value that was provided on create.
func (u *WaitHistoryUpsertBulk) UpdatePreparedByAttempt() *WaitHistoryUpsertBulk {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.UpdatePreparedByAttempt()
	})
}

// ClearPreparedByAttempt clears the value of the "prepared_by_attempt" field.
func (u *WaitHistoryUpsertBulk) ClearPreparedByAttempt() *WaitHistoryUpsertBulk {
	return u.Update(func(s *WaitHistoryUpsert) {
		s.ClearPreparedByAttempt()
	})
}

// Exec executes the query.
func (u *WaitHistoryUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the WaitHistoryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WaitHistoryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WaitHistoryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
