// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/piglor/loom/services/loom/ent/waithistory"
)

// WaitHistory is the model entity for the WaitHistory schema.
type WaitHistory struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// GoalID holds the value of the "goal_id" field.
	GoalID string `json:"goal_id,omitempty"`
	// RunID holds the value of the "run_id" field.
	RunID *string `json:"run_id,omitempty"`
	// Generation holds the value of the "generation" field.
	Generation int `json:"generation,omitempty"`
	// Condition holds the value of the "condition" field.
	Condition map[string]interface{} `json:"condition,omitempty"`
	// ArmedAt holds the value of the "armed_at" field.
	ArmedAt *time.Time `json:"armed_at,omitempty"`
	// SatisfiedAt holds the value of the "satisfied_at" field.
	SatisfiedAt *time.Time `json:"satisfied_at,omitempty"`
	// EventID holds the value of the "event_id" field.
	EventID *string `json:"event_id,omitempty"`
	// ClosedAt holds the value of the "closed_at" field.
	ClosedAt *time.Time `json:"closed_at,omitempty"`
	// PreparedByAttempt holds the value of the "prepared_by_attempt" field.
	PreparedByAttempt *string `json:"prepared_by_attempt,omitempty"`
	selectValues      sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WaitHistory) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case waithistory.FieldCondition:
			values[i] = new([]byte)
		case waithistory.FieldGeneration:
			values[i] = new(sql.NullInt64)
		case waithistory.FieldID, waithistory.FieldGoalID, waithistory.FieldRunID, waithistory.FieldEventID, waithistory.FieldPreparedByAttempt:
			values[i] = new(sql.NullString)
		case waithistory.FieldArmedAt, waithistory.FieldSatisfiedAt, waithistory.FieldClosedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WaitHistory fields.
func (_m *WaitHistory) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case waithistory.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case waithistory.FieldGoalID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field goal_id", values[i])
			} else if value.Valid {
				_m.GoalID = value.String
			}
		case waithistory.FieldRunID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field run_id", values[i])
			} else if value.Valid {
				_m.RunID = new(string)
				*_m.RunID = value.String
			}
		case waithistory.FieldGeneration:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field generation", values[i])
			} else if value.Valid {
				_m.Generation = int(value.Int64)
			}
		case waithistory.FieldCondition:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field condition", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Condition); err != nil {
					return fmt.Errorf("unmarshal field condition: %w", err)
				}
			}
		case waithistory.FieldArmedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field armed_at", values[i])
			} else if value.Valid {
				_m.ArmedAt = new(time.Time)
				*_m.ArmedAt = value.Time
			}
		case waithistory.FieldSatisfiedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field satisfied_at", values[i])
			} else if value.Valid {
				_m.SatisfiedAt = new(time.Time)
				*_m.SatisfiedAt = value.Time
			}
		case waithistory.FieldEventID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_id", values[i])
			} else if value.Valid {
				_m.EventID = new(string)
				*_m.EventID = value.String
			}
		case waithistory.FieldClosedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field closed_at", values[i])
			} else if value.Valid {
				_m.ClosedAt = new(time.Time)
				*_m.ClosedAt = value.Time
			}
		case waithistory.FieldPreparedByAttempt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prepared_by_attempt", values[i])
			} else if value.Valid {
				_m.PreparedByAttempt = new(string)
				*_m.PreparedByAttempt = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WaitHistory.
// This includes values selected through modifiers, order, etc.
func (_m *WaitHistory) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this WaitHistory.
// Note that you need to call WaitHistory.Unwrap() before calling this method if this WaitHistory
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WaitHistory) Update() *WaitHistoryUpdateOne {
	return NewWaitHistoryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WaitHistory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WaitHistory) Unwrap() *WaitHistory {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WaitHistory is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WaitHistory) String() string {
	var builder strings.Builder
	builder.WriteString("WaitHistory(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("goal_id=")
	builder.WriteString(_m.GoalID)
	builder.WriteString(", ")
	if v := _m.RunID; v != nil {
		builder.WriteString("run_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("generation=")
	builder.WriteString(fmt.Sprintf("%v", _m.Generation))
	builder.WriteString(", ")
	builder.WriteString("condition=")
	builder.WriteString(fmt.Sprintf("%v", _m.Condition))
	builder.WriteString(", ")
	if v := _m.ArmedAt; v != nil {
		builder.WriteString("armed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.SatisfiedAt; v != nil {
		builder.WriteString("satisfied_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.EventID; v != nil {
		builder.WriteString("event_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ClosedAt; v != nil {
		builder.WriteString("closed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.PreparedByAttempt; v != nil {
		builder.WriteString("prepared_by_attempt=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// WaitHistories is a parsable slice of WaitHistory.
type WaitHistories []*WaitHistory
