// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/piglor/loom/services/loom/ent/workflowtriggerbinding"
)

// WorkflowTriggerBinding is the model entity for the WorkflowTriggerBinding schema.
type WorkflowTriggerBinding struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Organization holds the value of the "organization" field.
	Organization string `json:"organization,omitempty"`
	// WorkflowVersionID holds the value of the "workflow_version_id" field.
	WorkflowVersionID string `json:"workflow_version_id,omitempty"`
	// IntegrationInstanceID holds the value of the "integration_instance_id" field.
	IntegrationInstanceID string `json:"integration_instance_id,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// IngressInstance holds the value of the "ingress_instance" field.
	IngressInstance string `json:"ingress_instance,omitempty"`
	// EventType holds the value of the "event_type" field.
	EventType string `json:"event_type,omitempty"`
	// Resource holds the value of the "resource" field.
	Resource string `json:"resource,omitempty"`
	// Version holds the value of the "version" field.
	Version string `json:"version,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WorkflowTriggerBinding) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case workflowtriggerbinding.FieldEnabled:
			values[i] = new(sql.NullBool)
		case workflowtriggerbinding.FieldID, workflowtriggerbinding.FieldOrganization, workflowtriggerbinding.FieldWorkflowVersionID, workflowtriggerbinding.FieldIntegrationInstanceID, workflowtriggerbinding.FieldSource, workflowtriggerbinding.FieldIngressInstance, workflowtriggerbinding.FieldEventType, workflowtriggerbinding.FieldResource, workflowtriggerbinding.FieldVersion:
			values[i] = new(sql.NullString)
		case workflowtriggerbinding.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WorkflowTriggerBinding fields.
func (_m *WorkflowTriggerBinding) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case workflowtriggerbinding.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case workflowtriggerbinding.FieldOrganization:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field organization", values[i])
			} else if value.Valid {
				_m.Organization = value.String
			}
		case workflowtriggerbinding.FieldWorkflowVersionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field workflow_version_id", values[i])
			} else if value.Valid {
				_m.WorkflowVersionID = value.String
			}
		case workflowtriggerbinding.FieldIntegrationInstanceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field integration_instance_id", values[i])
			} else if value.Valid {
				_m.IntegrationInstanceID = value.String
			}
		case workflowtriggerbinding.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case workflowtriggerbinding.FieldIngressInstance:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ingress_instance", values[i])
			} else if value.Valid {
				_m.IngressInstance = value.String
			}
		case workflowtriggerbinding.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				_m.EventType = value.String
			}
		case workflowtriggerbinding.FieldResource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resource", values[i])
			} else if value.Valid {
				_m.Resource = value.String
			}
		case workflowtriggerbinding.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.String
			}
		case workflowtriggerbinding.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case workflowtriggerbinding.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WorkflowTriggerBinding.
// This includes values selected through modifiers, order, etc.
func (_m *WorkflowTriggerBinding) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this WorkflowTriggerBinding.
// Note that you need to call WorkflowTriggerBinding.Unwrap() before calling this method if this WorkflowTriggerBinding
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WorkflowTriggerBinding) Update() *WorkflowTriggerBindingUpdateOne {
	return NewWorkflowTriggerBindingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WorkflowTriggerBinding entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WorkflowTriggerBinding) Unwrap() *WorkflowTriggerBinding {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WorkflowTriggerBinding is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WorkflowTriggerBinding) String() string {
	var builder strings.Builder
	builder.WriteString("WorkflowTriggerBinding(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("organization=")
	builder.WriteString(_m.Organization)
	builder.WriteString(", ")
	builder.WriteString("workflow_version_id=")
	builder.WriteString(_m.WorkflowVersionID)
	builder.WriteString(", ")
	builder.WriteString("integration_instance_id=")
	builder.WriteString(_m.IntegrationInstanceID)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("ingress_instance=")
	builder.WriteString(_m.IngressInstance)
	builder.WriteString(", ")
	builder.WriteString("event_type=")
	builder.WriteString(_m.EventType)
	builder.WriteString(", ")
	builder.WriteString("resource=")
	builder.WriteString(_m.Resource)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(_m.Version)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// WorkflowTriggerBindings is a parsable slice of WorkflowTriggerBinding.
type WorkflowTriggerBindings []*WorkflowTriggerBinding
