// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/piglor/loom/services/loom/ent/worker"
)

// WorkerCreate is the builder for creating a Worker entity.
type WorkerCreate struct {
	config
	mutation *WorkerMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRuntime sets the "runtime" field.
func (_c *WorkerCreate) SetRuntime(v string) *WorkerCreate {
	_c.mutation.SetRuntime(v)
	return _c
}

// SetCapabilities sets the "capabilities" field.
func (_c *WorkerCreate) SetCapabilities(v []string) *WorkerCreate {
	_c.mutation.SetCapabilities(v)
	return _c
}

// SetOrganization sets the "organization" field.
func (_c *WorkerCreate) SetOrganization(v string) *WorkerCreate {
	_c.mutation.SetOrganization(v)
	return _c
}

// SetNillableOrganization sets the "organization" field if the given value is not nil.
func (_c *WorkerCreate) SetNillableOrganization(v *string) *WorkerCreate {
	if v != nil {
		_c.SetOrganization(*v)
	}
	return _c
}

// SetTokenHash sets the "token_hash" field.
func (_c *WorkerCreate) SetTokenHash(v string) *WorkerCreate {
	_c.mutation.SetTokenHash(v)
	return _c
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_c *WorkerCreate) SetNillableTokenHash(v *string) *WorkerCreate {
	if v != nil {
		_c.SetTokenHash(*v)
	}
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *WorkerCreate) SetRevokedAt(v time.Time) *WorkerCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *WorkerCreate) SetNillableRevokedAt(v *time.Time) *WorkerCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_c *WorkerCreate) SetLastSeenAt(v time.Time) *WorkerCreate {
	_c.mutation.SetLastSeenAt(v)
	return _c
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_c *WorkerCreate) SetNillableLastSeenAt(v *time.Time) *WorkerCreate {
	if v != nil {
		_c.SetLastSeenAt(*v)
	}
	return _c
}

// SetWorkspaceRef sets the "workspace_ref" field.
func (_c *WorkerCreate) SetWorkspaceRef(v string) *WorkerCreate {
	_c.mutation.SetWorkspaceRef(v)
	return _c
}

// SetNillableWorkspaceRef sets the "workspace_ref" field if the given value is not nil.
func (_c *WorkerCreate) SetNillableWorkspaceRef(v *string) *WorkerCreate {
	if v != nil {
		_c.SetWorkspaceRef(*v)
	}
	return _c
}

// SetLabels sets the "labels" field.
func (_c *WorkerCreate) SetLabels(v map[string]interface{}) *WorkerCreate {
	_c.mutation.SetLabels(v)
	return _c
}

// SetID sets the "id" field.
func (_c *WorkerCreate) SetID(v string) *WorkerCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *WorkerCreate) SetNillableID(v *string) *WorkerCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the WorkerMutation object of the builder.
func (_c *WorkerCreate) Mutation() *WorkerMutation {
	return _c.mutation
}

// Save creates the Worker in the database.
func (_c *WorkerCreate) Save(ctx context.Context) (*Worker, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WorkerCreate) SaveX(ctx context.Context) *Worker {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WorkerCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := worker.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WorkerCreate) check() error {
	if _, ok := _c.mutation.Runtime(); !ok {
		return &ValidationError{Name: "runtime", err: errors.New(`ent: missing required field "Worker.runtime"`)}
	}
	if _, ok := _c.mutation.Capabilities(); !ok {
		return &ValidationError{Name: "capabilities", err: errors.New(`ent: missing required field "Worker.capabilities"`)}
	}
	return nil
}

func (_c *WorkerCreate) sqlSave(ctx context.Context) (*Worker, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Worker.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WorkerCreate) createSpec() (*Worker, *sqlgraph.CreateSpec) {
	var (
		_node = &Worker{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(worker.Table, sqlgraph.NewFieldSpec(worker.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Runtime(); ok {
		_spec.SetField(worker.FieldRuntime, field.TypeString, value)
		_node.Runtime = value
	}
	if value, ok := _c.mutation.Capabilities(); ok {
		_spec.SetField(worker.FieldCapabilities, field.TypeJSON, value)
		_node.Capabilities = value
	}
	if value, ok := _c.mutation.Organization(); ok {
		_spec.SetField(worker.FieldOrganization, field.TypeString, value)
		_node.Organization = &value
	}
	if value, ok := _c.mutation.TokenHash(); ok {
		_spec.SetField(worker.FieldTokenHash, field.TypeString, value)
		_node.TokenHash = &value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(worker.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	if value, ok := _c.mutation.LastSeenAt(); ok {
		_spec.SetField(worker.FieldLastSeenAt, field.TypeTime, value)
		_node.LastSeenAt = &value
	}
	if value, ok := _c.mutation.WorkspaceRef(); ok {
		_spec.SetField(worker.FieldWorkspaceRef, field.TypeString, value)
		_node.WorkspaceRef = &value
	}
	if value, ok := _c.mutation.Labels(); ok {
		_spec.SetField(worker.FieldLabels, field.TypeJSON, value)
		_node.Labels = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Worker.Create().
//		SetRuntime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WorkerUpsert) {
//			SetRuntime(v+v).
//		}).
//		Exec(ctx)
func (_c *WorkerCreate) OnConflict(opts ...sql.ConflictOption) *WorkerUpsertOne {
	_c.conflict = opts
	return &WorkerUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Worker.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WorkerCreate) OnConflictColumns(columns ...string) *WorkerUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WorkerUpsertOne{
		create: _c,
	}
}

type (
	// WorkerUpsertOne is the builder for "upsert"-ing
	//  one Worker node.
	WorkerUpsertOne struct {
		create *WorkerCreate
	}

	// WorkerUpsert is the "OnConflict" setter.
	WorkerUpsert struct {
		*sql.UpdateSet
	}
)

// SetRuntime sets the "runtime" field.
func (u *WorkerUpsert) SetRuntime(v string) *WorkerUpsert {
	u.Set(worker.FieldRuntime, v)
	return u
}

// UpdateRuntime sets the "runtime" field to the value that was provided on create.
func (u *WorkerUpsert) UpdateRuntime() *WorkerUpsert {
	u.SetExcluded(worker.FieldRuntime)
	return u
}

// SetCapabilities sets the "capabilities" field.
func (u *WorkerUpsert) SetCapabilities(v []string) *WorkerUpsert {
	u.Set(worker.FieldCapabilities, v)
	return u
}

// UpdateCapabilities sets the "capabilities" field to the value that was provided on create.
func (u *WorkerUpsert) UpdateCapabilities() *WorkerUpsert {
	u.SetExcluded(worker.FieldCapabilities)
	return u
}

// SetOrganization sets the "organization" field.
func (u *WorkerUpsert) SetOrganization(v string) *WorkerUpsert {
	u.Set(worker.FieldOrganization, v)
	return u
}

// UpdateOrganization sets the "organization" field to the value that was provided on create.
func (u *WorkerUpsert) UpdateOrganization() *WorkerUpsert {
	u.SetExcluded(worker.FieldOrganization)
	return u
}

// ClearOrganization clears the value of the "organization" field.
func (u *WorkerUpsert) ClearOrganization() *WorkerUpsert {
	u.SetNull(worker.FieldOrganization)
	return u
}

// SetTokenHash sets the "token_hash" field.
func (u *WorkerUpsert) SetTokenHash(v string) *WorkerUpsert {
	u.Set(worker.FieldTokenHash, v)
	return u
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *WorkerUpsert) UpdateTokenHash() *WorkerUpsert {
	u.SetExcluded(worker.FieldTokenHash)
	return u
}

// ClearTokenHash clears the value of the "token_hash" field.
func (u *WorkerUpsert) ClearTokenHash() *WorkerUpsert {
	u.SetNull(worker.FieldTokenHash)
	return u
}

// SetRevokedAt sets the "revoked_at" field.
func (u *WorkerUpsert) SetRevokedAt(v time.Time) *WorkerUpsert {
	u.Set(worker.FieldRevokedAt, v)
	return u
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *WorkerUpsert) UpdateRevokedAt() *WorkerUpsert {
	u.SetExcluded(worker.FieldRevokedAt)
	return u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *WorkerUpsert) ClearRevokedAt() *WorkerUpsert {
	u.SetNull(worker.FieldRevokedAt)
	return u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *WorkerUpsert) SetLastSeenAt(v time.Time) *WorkerUpsert {
	u.Set(worker.FieldLastSeenAt, v)
	return u
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *WorkerUpsert) UpdateLastSeenAt() *WorkerUpsert {
	u.SetExcluded(worker.FieldLastSeenAt)
	return u
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (u *WorkerUpsert) ClearLastSeenAt() *WorkerUpsert {
	u.SetNull(worker.FieldLastSeenAt)
	return u
}

// SetWorkspaceRef sets the "workspace_ref" field.
func (u *WorkerUpsert) SetWorkspaceRef(v string) *WorkerUpsert {
	u.Set(worker.FieldWorkspaceRef, v)
	return u
}

// UpdateWorkspaceRef sets the "workspace_ref" field to the value that was provided on create.
func (u *WorkerUpsert) UpdateWorkspaceRef() *WorkerUpsert {
	u.SetExcluded(worker.FieldWorkspaceRef)
	return u
}

// ClearWorkspaceRef clears the value of the "workspace_ref" field.
func (u *WorkerUpsert) ClearWorkspaceRef() *WorkerUpsert {
	u.SetNull(worker.FieldWorkspaceRef)
	return u
}

// SetLabels sets the "labels" field.
func (u *WorkerUpsert) SetLabels(v map[string]interface{}) *WorkerUpsert {
	u.Set(worker.FieldLabels, v)
	return u
}

// UpdateLabels sets the "labels" field to the value that was provided on create.
func (u *WorkerUpsert) UpdateLabels() *WorkerUpsert {
	u.SetExcluded(worker.FieldLabels)
	return u
}

// ClearLabels clears the value of the "labels" field.
func (u *WorkerUpsert) ClearLabels() *WorkerUpsert {
	u.SetNull(worker.FieldLabels)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Worker.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(worker.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *WorkerUpsertOne) UpdateNewValues() *WorkerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(worker.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Worker.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *WorkerUpsertOne) Ignore() *WorkerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WorkerUpsertOne) DoNothing() *WorkerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WorkerCreate.OnConflict
// documentation for more info.
func (u *WorkerUpsertOne) Update(set func(*WorkerUpsert)) *WorkerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WorkerUpsert{UpdateSet: update})
	}))
	return u
}

// SetRuntime sets the "runtime" field.
func (u *WorkerUpsertOne) SetRuntime(v string) *WorkerUpsertOne {
	return u.Update(func(s *WorkerUpsert) {
		s.SetRuntime(v)
	})
}

// UpdateRuntime sets the "runtime" field to the value that was provided on create.
func (u *WorkerUpsertOne) UpdateRuntime() *WorkerUpsertOne {
	return u.Update(func(s *WorkerUpsert) {
		s.UpdateRuntime()
	})
}

// SetCapabilities sets the "capabilities" field.
func (u *WorkerUpsertOne) SetCapabilities(v []string) *WorkerUpsertOne {
	return u.Update(func(s *WorkerUpsert) {
		s.SetCapabilities(v)
	})
}

// UpdateCapabilities sets the "capabilities" field to the value that was provided on create.
func (u *WorkerUpsertOne) UpdateCapabilities() *WorkerUpsertOne {
	return u.Update(func(s *WorkerUpsert) {
		s.UpdateCapabilities()
	})
}

// SetOrganization sets the "organization" field.
func (u *WorkerUpsertOne) SetOrganization(v string) *WorkerUpsertOne {
	return u.Update(func(s *WorkerUpsert) {
		s.SetOrganization(v)
	})
}

// UpdateOrganization sets the "organization" field to the value that was provided on create.
func (u *WorkerUpsertOne) UpdateOrganization() *WorkerUpsertOne {
	return u.Update(func(s *WorkerUpsert) {
		s.UpdateOrganization()
	})
}

// ClearOrganization clears the value of the "organization" field.
func (u *WorkerUpsertOne) ClearOrganization() *WorkerUpsertOne {
	return u.Update(func(s *WorkerUpsert) {
		s.ClearOrganization()
	})
}

// SetTokenHash sets the "token_hash" field.
func (u *WorkerUpsertOne) SetTokenHash(v string) *WorkerUpsertOne {
	return u.Update(func(s *WorkerUpsert) {
		s.SetTokenHash(v)
	})
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *WorkerUpsertOne) UpdateTokenHash() *WorkerUpsertOne {
	return u.Update(func(s *WorkerUpsert) {
		s.UpdateTokenHash()
	})
}

// ClearTokenHash clears the value of the "token_hash" field.
func (u *WorkerUpsertOne) ClearTokenHash() *WorkerUpsertOne {
	return u.Update(func(s *WorkerUpsert) {
		s.ClearTokenHash()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *WorkerUpsertOne) SetRevokedAt(v time.Time) *WorkerUpsertOne {
	return u.Update(func(s *WorkerUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *WorkerUpsertOne) UpdateRevokedAt() *WorkerUpsertOne {
	return u.Update(func(s *WorkerUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *WorkerUpsertOne) ClearRevokedAt() *WorkerUpsertOne {
	return u.Update(func(s *WorkerUpsert) {
		s.ClearRevokedAt()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *WorkerUpsertOne) SetLastSeenAt(v time.Time) *WorkerUpsertOne {
	return u.Update(func(s *WorkerUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *WorkerUpsertOne) UpdateLastSeenAt() *WorkerUpsertOne {
	return u.Update(func(s *WorkerUpsert) {
		s.UpdateLastSeenAt()
	})
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (u *WorkerUpsertOne) ClearLastSeenAt() *WorkerUpsertOne {
	return u.Update(func(s *WorkerUpsert) {
		s.ClearLastSeenAt()
	})
}

// SetWorkspaceRef sets the "workspace_ref" field.
func (u *WorkerUpsertOne) SetWorkspaceRef(v string) *WorkerUpsertOne {
	return u.Update(func(s *WorkerUpsert) {
		s.SetWorkspaceRef(v)
	})
}

// UpdateWorkspaceRef sets the "workspace_ref" field to the value that was provided on create.
func (u *WorkerUpsertOne) UpdateWorkspaceRef() *WorkerUpsertOne {
	return u.Update(func(s *WorkerUpsert) {
		s.UpdateWorkspaceRef()
	})
}

// ClearWorkspaceRef clears the value of the "workspace_ref" field.
func (u *WorkerUpsertOne) ClearWorkspaceRef() *WorkerUpsertOne {
	return u.Update(func(s *WorkerUpsert) {
		s.ClearWorkspaceRef()
	})
}

// SetLabels sets the "labels" field.
func (u *WorkerUpsertOne) SetLabels(v map[string]interface{}) *WorkerUpsertOne {
	return u.Update(func(s *WorkerUpsert) {
		s.SetLabels(v)
	})
}

// UpdateLabels sets the "labels" field to the value that was provided on create.
func (u *WorkerUpsertOne) UpdateLabels() *WorkerUpsertOne {
	return u.Update(func(s *WorkerUpsert) {
		s.UpdateLabels()
	})
}

// ClearLabels clears the value of the "labels" field.
func (u *WorkerUpsertOne) ClearLabels() *WorkerUpsertOne {
	return u.Update(func(s *WorkerUpsert) {
		s.ClearLabels()
	})
}

// Exec executes the query.
func (u *WorkerUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WorkerCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WorkerUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *WorkerUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: WorkerUpsertOne.ID is not supported by MySQL driver. Use WorkerUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *WorkerUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// WorkerCreateBulk is the builder for creating many Worker entities in bulk.
type WorkerCreateBulk struct {
	config
	err      error
	builders []*WorkerCreate
	conflict []sql.ConflictOption
}

// Save creates the Worker entities in the database.
func (_c *WorkerCreateBulk) Save(ctx context.Context) ([]*Worker, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Worker, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WorkerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WorkerCreateBulk) SaveX(ctx context.Context) []*Worker {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Worker.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WorkerUpsert) {
//			SetRuntime(v+v).
//		}).
//		Exec(ctx)
func (_c *WorkerCreateBulk) OnConflict(opts ...sql.ConflictOption) *WorkerUpsertBulk {
	_c.conflict = opts
	return &WorkerUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Worker.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WorkerCreateBulk) OnConflictColumns(columns ...string) *WorkerUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WorkerUpsertBulk{
		create: _c,
	}
}

// WorkerUpsertBulk is the builder for "upsert"-ing
// a bulk of Worker nodes.
type WorkerUpsertBulk struct {
	create *WorkerCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Worker.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(worker.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *WorkerUpsertBulk) UpdateNewValues() *WorkerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(worker.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Worker.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *WorkerUpsertBulk) Ignore() *WorkerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WorkerUpsertBulk) DoNothing() *WorkerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WorkerCreateBulk.OnConflict
// documentation for more info.
func (u *WorkerUpsertBulk) Update(set func(*WorkerUpsert)) *WorkerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WorkerUpsert{UpdateSet: update})
	}))
	return u
}

// SetRuntime sets the "runtime" field.
func (u *WorkerUpsertBulk) SetRuntime(v string) *WorkerUpsertBulk {
	return u.Update(func(s *WorkerUpsert) {
		s.SetRuntime(v)
	})
}

// UpdateRuntime sets the "runtime" field to the value that was provided on create.
func (u *WorkerUpsertBulk) UpdateRuntime() *WorkerUpsertBulk {
	return u.Update(func(s *WorkerUpsert) {
		s.UpdateRuntime()
	})
}

// SetCapabilities sets the "capabilities" field.
func (u *WorkerUpsertBulk) SetCapabilities(v []string) *WorkerUpsertBulk {
	return u.Update(func(s *WorkerUpsert) {
		s.SetCapabilities(v)
	})
}

// UpdateCapabilities sets the "capabilities" field to the value that was provided on create.
func (u *WorkerUpsertBulk) UpdateCapabilities() *WorkerUpsertBulk {
	return u.Update(func(s *WorkerUpsert) {
		s.UpdateCapabilities()
	})
}

// SetOrganization sets the "organization" field.
func (u *WorkerUpsertBulk) SetOrganization(v string) *WorkerUpsertBulk {
	return u.Update(func(s *WorkerUpsert) {
		s.SetOrganization(v)
	})
}

// UpdateOrganization sets the "organization" field to the value that was provided on create.
func (u *WorkerUpsertBulk) UpdateOrganization() *WorkerUpsertBulk {
	return u.Update(func(s *WorkerUpsert) {
		s.UpdateOrganization()
	})
}

// ClearOrganization clears the value of the "organization" field.
func (u *WorkerUpsertBulk) ClearOrganization() *WorkerUpsertBulk {
	return u.Update(func(s *WorkerUpsert) {
		s.ClearOrganization()
	})
}

// SetTokenHash sets the "token_hash" field.
func (u *WorkerUpsertBulk) SetTokenHash(v string) *WorkerUpsertBulk {
	return u.Update(func(s *WorkerUpsert) {
		s.SetTokenHash(v)
	})
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *WorkerUpsertBulk) UpdateTokenHash() *WorkerUpsertBulk {
	return u.Update(func(s *WorkerUpsert) {
		s.UpdateTokenHash()
	})
}

// ClearTokenHash clears the value of the "token_hash" field.
func (u *WorkerUpsertBulk) ClearTokenHash() *WorkerUpsertBulk {
	return u.Update(func(s *WorkerUpsert) {
		s.ClearTokenHash()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *WorkerUpsertBulk) SetRevokedAt(v time.Time) *WorkerUpsertBulk {
	return u.Update(func(s *WorkerUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *WorkerUpsertBulk) UpdateRevokedAt() *WorkerUpsertBulk {
	return u.Update(func(s *WorkerUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *WorkerUpsertBulk) ClearRevokedAt() *WorkerUpsertBulk {
	return u.Update(func(s *WorkerUpsert) {
		s.ClearRevokedAt()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *WorkerUpsertBulk) SetLastSeenAt(v time.Time) *WorkerUpsertBulk {
	return u.Update(func(s *WorkerUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *WorkerUpsertBulk) UpdateLastSeenAt() *WorkerUpsertBulk {
	return u.Update(func(s *WorkerUpsert) {
		s.UpdateLastSeenAt()
	})
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (u *WorkerUpsertBulk) ClearLastSeenAt() *WorkerUpsertBulk {
	return u.Update(func(s *WorkerUpsert) {
		s.ClearLastSeenAt()
	})
}

// SetWorkspaceRef sets the "workspace_ref" field.
func (u *WorkerUpsertBulk) SetWorkspaceRef(v string) *WorkerUpsertBulk {
	return u.Update(func(s *WorkerUpsert) {
		s.SetWorkspaceRef(v)
	})
}

// UpdateWorkspaceRef sets the "workspace_ref" field to the value that was provided on create.
func (u *WorkerUpsertBulk) UpdateWorkspaceRef() *WorkerUpsertBulk {
	return u.Update(func(s *WorkerUpsert) {
		s.UpdateWorkspaceRef()
	})
}

// ClearWorkspaceRef clears the value of the "workspace_ref" field.
func (u *WorkerUpsertBulk) ClearWorkspaceRef() *WorkerUpsertBulk {
	return u.Update(func(s *WorkerUpsert) {
		s.ClearWorkspaceRef()
	})
}

// SetLabels sets the "labels" field.
func (u *WorkerUpsertBulk) SetLabels(v map[string]interface{}) *WorkerUpsertBulk {
	return u.Update(func(s *WorkerUpsert) {
		s.SetLabels(v)
	})
}

// UpdateLabels sets the "labels" field to the value that was provided on create.
func (u *WorkerUpsertBulk) UpdateLabels() *WorkerUpsertBulk {
	return u.Update(func(s *WorkerUpsert) {
		s.UpdateLabels()
	})
}

// ClearLabels clears the value of the "labels" field.
func (u *WorkerUpsertBulk) ClearLabels() *WorkerUpsertBulk {
	return u.Update(func(s *WorkerUpsert) {
		s.ClearLabels()
	})
}

// Exec executes the query.
func (u *WorkerUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the WorkerCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WorkerCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WorkerUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
