// Code generated by ent, DO NOT EDIT.

package worker

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/piglor/loom/services/loom/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Worker {
	return predicate.Worker(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Worker {
	return predicate.Worker(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Worker {
	return predicate.Worker(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Worker {
	return predicate.Worker(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Worker {
	return predicate.Worker(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Worker {
	return predicate.Worker(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Worker {
	return predicate.Worker(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Worker {
	return predicate.Worker(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Worker {
	return predicate.Worker(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Worker {
	return predicate.Worker(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Worker {
	return predicate.Worker(sql.FieldContainsFold(FieldID, id))
}

// Runtime applies equality check predicate on the "runtime" field. It's identical to RuntimeEQ.
func Runtime(v string) predicate.Worker {
	return predicate.Worker(sql.FieldEQ(FieldRuntime, v))
}

// Organization applies equality check predicate on the "organization" field. It's identical to OrganizationEQ.
func Organization(v string) predicate.Worker {
	return predicate.Worker(sql.FieldEQ(FieldOrganization, v))
}

// TokenHash applies equality check predicate on the "token_hash" field. It's identical to TokenHashEQ.
func TokenHash(v string) predicate.Worker {
	return predicate.Worker(sql.FieldEQ(FieldTokenHash, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.Worker {
	return predicate.Worker(sql.FieldEQ(FieldRevokedAt, v))
}

// LastSeenAt applies equality check predicate on the "last_seen_at" field. It's identical to LastSeenAtEQ.
func LastSeenAt(v time.Time) predicate.Worker {
	return predicate.Worker(sql.FieldEQ(FieldLastSeenAt, v))
}

// WorkspaceRef applies equality check predicate on the "workspace_ref" field. It's identical to WorkspaceRefEQ.
func WorkspaceRef(v string) predicate.Worker {
	return predicate.Worker(sql.FieldEQ(FieldWorkspaceRef, v))
}

// RuntimeEQ applies the EQ predicate on the "runtime" field.
func RuntimeEQ(v string) predicate.Worker {
	return predicate.Worker(sql.FieldEQ(FieldRuntime, v))
}

// RuntimeNEQ applies the NEQ predicate on the "runtime" field.
func RuntimeNEQ(v string) predicate.Worker {
	return predicate.Worker(sql.FieldNEQ(FieldRuntime, v))
}

// RuntimeIn applies the In predicate on the "runtime" field.
func RuntimeIn(vs ...string) predicate.Worker {
	return predicate.Worker(sql.FieldIn(FieldRuntime, vs...))
}

// RuntimeNotIn applies the NotIn predicate on the "runtime" field.
func RuntimeNotIn(vs ...string) predicate.Worker {
	return predicate.Worker(sql.FieldNotIn(FieldRuntime, vs...))
}

// RuntimeGT applies the GT predicate on the "runtime" field.
func RuntimeGT(v string) predicate.Worker {
	return predicate.Worker(sql.FieldGT(FieldRuntime, v))
}

// RuntimeGTE applies the GTE predicate on the "runtime" field.
func RuntimeGTE(v string) predicate.Worker {
	return predicate.Worker(sql.FieldGTE(FieldRuntime, v))
}

// RuntimeLT applies the LT predicate on the "runtime" field.
func RuntimeLT(v string) predicate.Worker {
	return predicate.Worker(sql.FieldLT(FieldRuntime, v))
}

// RuntimeLTE applies the LTE predicate on the "runtime" field.
func RuntimeLTE(v string) predicate.Worker {
	return predicate.Worker(sql.FieldLTE(FieldRuntime, v))
}

// RuntimeContains applies the Contains predicate on the "runtime" field.
func RuntimeContains(v string) predicate.Worker {
	return predicate.Worker(sql.FieldContains(FieldRuntime, v))
}

// RuntimeHasPrefix applies the HasPrefix predicate on the "runtime" field.
func RuntimeHasPrefix(v string) predicate.Worker {
	return predicate.Worker(sql.FieldHasPrefix(FieldRuntime, v))
}

// RuntimeHasSuffix applies the HasSuffix predicate on the "runtime" field.
func RuntimeHasSuffix(v string) predicate.Worker {
	return predicate.Worker(sql.FieldHasSuffix(FieldRuntime, v))
}

// RuntimeEqualFold applies the EqualFold predicate on the "runtime" field.
func RuntimeEqualFold(v string) predicate.Worker {
	return predicate.Worker(sql.FieldEqualFold(FieldRuntime, v))
}

// RuntimeContainsFold applies the ContainsFold predicate on the "runtime" field.
func RuntimeContainsFold(v string) predicate.Worker {
	return predicate.Worker(sql.FieldContainsFold(FieldRuntime, v))
}

// OrganizationEQ applies the EQ predicate on the "organization" field.
func OrganizationEQ(v string) predicate.Worker {
	return predicate.Worker(sql.FieldEQ(FieldOrganization, v))
}

// OrganizationNEQ applies the NEQ predicate on the "organization" field.
func OrganizationNEQ(v string) predicate.Worker {
	return predicate.Worker(sql.FieldNEQ(FieldOrganization, v))
}

// OrganizationIn applies the In predicate on the "organization" field.
func OrganizationIn(vs ...string) predicate.Worker {
	return predicate.Worker(sql.FieldIn(FieldOrganization, vs...))
}

// OrganizationNotIn applies the NotIn predicate on the "organization" field.
func OrganizationNotIn(vs ...string) predicate.Worker {
	return predicate.Worker(sql.FieldNotIn(FieldOrganization, vs...))
}

// OrganizationGT applies the GT predicate on the "organization" field.
func OrganizationGT(v string) predicate.Worker {
	return predicate.Worker(sql.FieldGT(FieldOrganization, v))
}

// OrganizationGTE applies the GTE predicate on the "organization" field.
func OrganizationGTE(v string) predicate.Worker {
	return predicate.Worker(sql.FieldGTE(FieldOrganization, v))
}

// OrganizationLT applies the LT predicate on the "organization" field.
func OrganizationLT(v string) predicate.Worker {
	return predicate.Worker(sql.FieldLT(FieldOrganization, v))
}

// OrganizationLTE applies the LTE predicate on the "organization" field.
func OrganizationLTE(v string) predicate.Worker {
	return predicate.Worker(sql.FieldLTE(FieldOrganization, v))
}

// OrganizationContains applies the Contains predicate on the "organization" field.
func OrganizationContains(v string) predicate.Worker {
	return predicate.Worker(sql.FieldContains(FieldOrganization, v))
}

// OrganizationHasPrefix applies the HasPrefix predicate on the "organization" field.
func OrganizationHasPrefix(v string) predicate.Worker {
	return predicate.Worker(sql.FieldHasPrefix(FieldOrganization, v))
}

// OrganizationHasSuffix applies the HasSuffix predicate on the "organization" field.
func OrganizationHasSuffix(v string) predicate.Worker {
	return predicate.Worker(sql.FieldHasSuffix(FieldOrganization, v))
}

// OrganizationIsNil applies the IsNil predicate on the "organization" field.
func OrganizationIsNil() predicate.Worker {
	return predicate.Worker(sql.FieldIsNull(FieldOrganization))
}

// OrganizationNotNil applies the NotNil predicate on the "organization" field.
func OrganizationNotNil() predicate.Worker {
	return predicate.Worker(sql.FieldNotNull(FieldOrganization))
}

// OrganizationEqualFold applies the EqualFold predicate on the "organization" field.
func OrganizationEqualFold(v string) predicate.Worker {
	return predicate.Worker(sql.FieldEqualFold(FieldOrganization, v))
}

// OrganizationContainsFold applies the ContainsFold predicate on the "organization" field.
func OrganizationContainsFold(v string) predicate.Worker {
	return predicate.Worker(sql.FieldContainsFold(FieldOrganization, v))
}

// TokenHashEQ applies the EQ predicate on the "token_hash" field.
func TokenHashEQ(v string) predicate.Worker {
	return predicate.Worker(sql.FieldEQ(FieldTokenHash, v))
}

// TokenHashNEQ applies the NEQ predicate on the "token_hash" field.
func TokenHashNEQ(v string) predicate.Worker {
	return predicate.Worker(sql.FieldNEQ(FieldTokenHash, v))
}

// TokenHashIn applies the In predicate on the "token_hash" field.
func TokenHashIn(vs ...string) predicate.Worker {
	return predicate.Worker(sql.FieldIn(FieldTokenHash, vs...))
}

// TokenHashNotIn applies the NotIn predicate on the "token_hash" field.
func TokenHashNotIn(vs ...string) predicate.Worker {
	return predicate.Worker(sql.FieldNotIn(FieldTokenHash, vs...))
}

// TokenHashGT applies the GT predicate on the "token_hash" field.
func TokenHashGT(v string) predicate.Worker {
	return predicate.Worker(sql.FieldGT(FieldTokenHash, v))
}

// TokenHashGTE applies the GTE predicate on the "token_hash" field.
func TokenHashGTE(v string) predicate.Worker {
	return predicate.Worker(sql.FieldGTE(FieldTokenHash, v))
}

// TokenHashLT applies the LT predicate on the "token_hash" field.
func TokenHashLT(v string) predicate.Worker {
	return predicate.Worker(sql.FieldLT(FieldTokenHash, v))
}

// TokenHashLTE applies the LTE predicate on the "token_hash" field.
func TokenHashLTE(v string) predicate.Worker {
	return predicate.Worker(sql.FieldLTE(FieldTokenHash, v))
}

// TokenHashContains applies the Contains predicate on the "token_hash" field.
func TokenHashContains(v string) predicate.Worker {
	return predicate.Worker(sql.FieldContains(FieldTokenHash, v))
}

// TokenHashHasPrefix applies the HasPrefix predicate on the "token_hash" field.
func TokenHashHasPrefix(v string) predicate.Worker {
	return predicate.Worker(sql.FieldHasPrefix(FieldTokenHash, v))
}

// TokenHashHasSuffix applies the HasSuffix predicate on the "token_hash" field.
func TokenHashHasSuffix(v string) predicate.Worker {
	return predicate.Worker(sql.FieldHasSuffix(FieldTokenHash, v))
}

// TokenHashIsNil applies the IsNil predicate on the "token_hash" field.
func TokenHashIsNil() predicate.Worker {
	return predicate.Worker(sql.FieldIsNull(FieldTokenHash))
}

// TokenHashNotNil applies the NotNil predicate on the "token_hash" field.
func TokenHashNotNil() predicate.Worker {
	return predicate.Worker(sql.FieldNotNull(FieldTokenHash))
}

// TokenHashEqualFold applies the EqualFold predicate on the "token_hash" field.
func TokenHashEqualFold(v string) predicate.Worker {
	return predicate.Worker(sql.FieldEqualFold(FieldTokenHash, v))
}

// TokenHashContainsFold applies the ContainsFold predicate on the "token_hash" field.
func TokenHashContainsFold(v string) predicate.Worker {
	return predicate.Worker(sql.FieldContainsFold(FieldTokenHash, v))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.Worker {
	return predicate.Worker(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.Worker {
	return predicate.Worker(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.Worker {
	return predicate.Worker(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.Worker {
	return predicate.Worker(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.Worker {
	return predicate.Worker(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.Worker {
	return predicate.Worker(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.Worker {
	return predicate.Worker(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.Worker {
	return predicate.Worker(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.Worker {
	return predicate.Worker(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.Worker {
	return predicate.Worker(sql.FieldNotNull(FieldRevokedAt))
}

// LastSeenAtEQ applies the EQ predicate on the "last_seen_at" field.
func LastSeenAtEQ(v time.Time) predicate.Worker {
	return predicate.Worker(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSeenAtNEQ applies the NEQ predicate on the "last_seen_at" field.
func LastSeenAtNEQ(v time.Time) predicate.Worker {
	return predicate.Worker(sql.FieldNEQ(FieldLastSeenAt, v))
}

// LastSeenAtIn applies the In predicate on the "last_seen_at" field.
func LastSeenAtIn(vs ...time.Time) predicate.Worker {
	return predicate.Worker(sql.FieldIn(FieldLastSeenAt, vs...))
}

// LastSeenAtNotIn applies the NotIn predicate on the "last_seen_at" field.
func LastSeenAtNotIn(vs ...time.Time) predicate.Worker {
	return predicate.Worker(sql.FieldNotIn(FieldLastSeenAt, vs...))
}

// LastSeenAtGT applies the GT predicate on the "last_seen_at" field.
func LastSeenAtGT(v time.Time) predicate.Worker {
	return predicate.Worker(sql.FieldGT(FieldLastSeenAt, v))
}

// LastSeenAtGTE applies the GTE predicate on the "last_seen_at" field.
func LastSeenAtGTE(v time.Time) predicate.Worker {
	return predicate.Worker(sql.FieldGTE(FieldLastSeenAt, v))
}

// LastSeenAtLT applies the LT predicate on the "last_seen_at" field.
func LastSeenAtLT(v time.Time) predicate.Worker {
	return predicate.Worker(sql.FieldLT(FieldLastSeenAt, v))
}

// LastSeenAtLTE applies the LTE predicate on the "last_seen_at" field.
func LastSeenAtLTE(v time.Time) predicate.Worker {
	return predicate.Worker(sql.FieldLTE(FieldLastSeenAt, v))
}

// LastSeenAtIsNil applies the IsNil predicate on the "last_seen_at" field.
func LastSeenAtIsNil() predicate.Worker {
	return predicate.Worker(sql.FieldIsNull(FieldLastSeenAt))
}

// LastSeenAtNotNil applies the NotNil predicate on the "last_seen_at" field.
func LastSeenAtNotNil() predicate.Worker {
	return predicate.Worker(sql.FieldNotNull(FieldLastSeenAt))
}

// WorkspaceRefEQ applies the EQ predicate on the "workspace_ref" field.
func WorkspaceRefEQ(v string) predicate.Worker {
	return predicate.Worker(sql.FieldEQ(FieldWorkspaceRef, v))
}

// WorkspaceRefNEQ applies the NEQ predicate on the "workspace_ref" field.
func WorkspaceRefNEQ(v string) predicate.Worker {
	return predicate.Worker(sql.FieldNEQ(FieldWorkspaceRef, v))
}

// WorkspaceRefIn applies the In predicate on the "workspace_ref" field.
func WorkspaceRefIn(vs ...string) predicate.Worker {
	return predicate.Worker(sql.FieldIn(FieldWorkspaceRef, vs...))
}

// WorkspaceRefNotIn applies the NotIn predicate on the "workspace_ref" field.
func WorkspaceRefNotIn(vs ...string) predicate.Worker {
	return predicate.Worker(sql.FieldNotIn(FieldWorkspaceRef, vs...))
}

// WorkspaceRefGT applies the GT predicate on the "workspace_ref" field.
func WorkspaceRefGT(v string) predicate.Worker {
	return predicate.Worker(sql.FieldGT(FieldWorkspaceRef, v))
}

// WorkspaceRefGTE applies the GTE predicate on the "workspace_ref" field.
func WorkspaceRefGTE(v string) predicate.Worker {
	return predicate.Worker(sql.FieldGTE(FieldWorkspaceRef, v))
}

// WorkspaceRefLT applies the LT predicate on the "workspace_ref" field.
func WorkspaceRefLT(v string) predicate.Worker {
	return predicate.Worker(sql.FieldLT(FieldWorkspaceRef, v))
}

// WorkspaceRefLTE applies the LTE predicate on the "workspace_ref" field.
func WorkspaceRefLTE(v string) predicate.Worker {
	return predicate.Worker(sql.FieldLTE(FieldWorkspaceRef, v))
}

// WorkspaceRefContains applies the Contains predicate on the "workspace_ref" field.
func WorkspaceRefContains(v string) predicate.Worker {
	return predicate.Worker(sql.FieldContains(FieldWorkspaceRef, v))
}

// WorkspaceRefHasPrefix applies the HasPrefix predicate on the "workspace_ref" field.
func WorkspaceRefHasPrefix(v string) predicate.Worker {
	return predicate.Worker(sql.FieldHasPrefix(FieldWorkspaceRef, v))
}

// WorkspaceRefHasSuffix applies the HasSuffix predicate on the "workspace_ref" field.
func WorkspaceRefHasSuffix(v string) predicate.Worker {
	return predicate.Worker(sql.FieldHasSuffix(FieldWorkspaceRef, v))
}

// WorkspaceRefIsNil applies the IsNil predicate on the "workspace_ref" field.
func WorkspaceRefIsNil() predicate.Worker {
	return predicate.Worker(sql.FieldIsNull(FieldWorkspaceRef))
}

// WorkspaceRefNotNil applies the NotNil predicate on the "workspace_ref" field.
func WorkspaceRefNotNil() predicate.Worker {
	return predicate.Worker(sql.FieldNotNull(FieldWorkspaceRef))
}

// WorkspaceRefEqualFold applies the EqualFold predicate on the "workspace_ref" field.
func WorkspaceRefEqualFold(v string) predicate.Worker {
	return predicate.Worker(sql.FieldEqualFold(FieldWorkspaceRef, v))
}

// WorkspaceRefContainsFold applies the ContainsFold predicate on the "workspace_ref" field.
func WorkspaceRefContainsFold(v string) predicate.Worker {
	return predicate.Worker(sql.FieldContainsFold(FieldWorkspaceRef, v))
}

// LabelsIsNil applies the IsNil predicate on the "labels" field.
func LabelsIsNil() predicate.Worker {
	return predicate.Worker(sql.FieldIsNull(FieldLabels))
}

// LabelsNotNil applies the NotNil predicate on the "labels" field.
func LabelsNotNil() predicate.Worker {
	return predicate.Worker(sql.FieldNotNull(FieldLabels))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Worker) predicate.Worker {
	return predicate.Worker(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Worker) predicate.Worker {
	return predicate.Worker(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Worker) predicate.Worker {
	return predicate.Worker(sql.NotPredicates(p))
}
