// Code generated by ent, DO NOT EDIT.

package integrationinstance

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the integrationinstance type in the database.
	Label = "integration_instance"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOrganization holds the string denoting the organization field in the database.
	FieldOrganization = "organization"
	// FieldCredentialID holds the string denoting the credential_id field in the database.
	FieldCredentialID = "credential_id"
	// FieldPluginID holds the string denoting the plugin_id field in the database.
	FieldPluginID = "plugin_id"
	// FieldExternalInstanceID holds the string denoting the external_instance_id field in the database.
	FieldExternalInstanceID = "external_instance_id"
	// FieldRoutingIdentity holds the string denoting the routing_identity field in the database.
	FieldRoutingIdentity = "routing_identity"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldAccountLabel holds the string denoting the account_label field in the database.
	FieldAccountLabel = "account_label"
	// FieldRepositorySelection holds the string denoting the repository_selection field in the database.
	FieldRepositorySelection = "repository_selection"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldLastVerifiedAt holds the string denoting the last_verified_at field in the database.
	FieldLastVerifiedAt = "last_verified_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the integrationinstance in the database.
	Table = "integration_instances"
)

// Columns holds all SQL columns for integrationinstance fields.
var Columns = []string{
	FieldID,
	FieldOrganization,
	FieldCredentialID,
	FieldPluginID,
	FieldExternalInstanceID,
	FieldRoutingIdentity,
	FieldAccountID,
	FieldAccountLabel,
	FieldRepositorySelection,
	FieldMetadata,
	FieldState,
	FieldLastVerifiedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the IntegrationInstance queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOrganization orders the results by the organization field.
func ByOrganization(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrganization, opts...).ToFunc()
}

// ByCredentialID orders the results by the credential_id field.
func ByCredentialID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCredentialID, opts...).ToFunc()
}

// ByPluginID orders the results by the plugin_id field.
func ByPluginID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPluginID, opts...).ToFunc()
}

// ByExternalInstanceID orders the results by the external_instance_id field.
func ByExternalInstanceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalInstanceID, opts...).ToFunc()
}

// ByRoutingIdentity orders the results by the routing_identity field.
func ByRoutingIdentity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRoutingIdentity, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByAccountLabel orders the results by the account_label field.
func ByAccountLabel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountLabel, opts...).ToFunc()
}

// ByRepositorySelection orders the results by the repository_selection field.
func ByRepositorySelection(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRepositorySelection, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByLastVerifiedAt orders the results by the last_verified_at field.
func ByLastVerifiedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastVerifiedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
