// Code generated by ent, DO NOT EDIT.

package workflowversion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/piglor/loom/services/loom/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldContainsFold(FieldID, id))
}

// DefinitionID applies equality check predicate on the "definition_id" field. It's identical to DefinitionIDEQ.
func DefinitionID(v string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldEQ(FieldDefinitionID, v))
}

// Organization applies equality check predicate on the "organization" field. It's identical to OrganizationEQ.
func Organization(v string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldEQ(FieldOrganization, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldEQ(FieldVersion, v))
}

// SpecDigest applies equality check predicate on the "spec_digest" field. It's identical to SpecDigestEQ.
func SpecDigest(v string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldEQ(FieldSpecDigest, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldEQ(FieldCreatedAt, v))
}

// DefinitionIDEQ applies the EQ predicate on the "definition_id" field.
func DefinitionIDEQ(v string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldEQ(FieldDefinitionID, v))
}

// DefinitionIDNEQ applies the NEQ predicate on the "definition_id" field.
func DefinitionIDNEQ(v string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldNEQ(FieldDefinitionID, v))
}

// DefinitionIDIn applies the In predicate on the "definition_id" field.
func DefinitionIDIn(vs ...string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldIn(FieldDefinitionID, vs...))
}

// DefinitionIDNotIn applies the NotIn predicate on the "definition_id" field.
func DefinitionIDNotIn(vs ...string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldNotIn(FieldDefinitionID, vs...))
}

// DefinitionIDGT applies the GT predicate on the "definition_id" field.
func DefinitionIDGT(v string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldGT(FieldDefinitionID, v))
}

// DefinitionIDGTE applies the GTE predicate on the "definition_id" field.
func DefinitionIDGTE(v string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldGTE(FieldDefinitionID, v))
}

// DefinitionIDLT applies the LT predicate on the "definition_id" field.
func DefinitionIDLT(v string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldLT(FieldDefinitionID, v))
}

// DefinitionIDLTE applies the LTE predicate on the "definition_id" field.
func DefinitionIDLTE(v string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldLTE(FieldDefinitionID, v))
}

// DefinitionIDContains applies the Contains predicate on the "definition_id" field.
func DefinitionIDContains(v string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldContains(FieldDefinitionID, v))
}

// DefinitionIDHasPrefix applies the HasPrefix predicate on the "definition_id" field.
func DefinitionIDHasPrefix(v string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldHasPrefix(FieldDefinitionID, v))
}

// DefinitionIDHasSuffix applies the HasSuffix predicate on the "definition_id" field.
func DefinitionIDHasSuffix(v string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldHasSuffix(FieldDefinitionID, v))
}

// DefinitionIDEqualFold applies the EqualFold predicate on the "definition_id" field.
func DefinitionIDEqualFold(v string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldEqualFold(FieldDefinitionID, v))
}

// DefinitionIDContainsFold applies the ContainsFold predicate on the "definition_id" field.
func DefinitionIDContainsFold(v string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldContainsFold(FieldDefinitionID, v))
}

// OrganizationEQ applies the EQ predicate on the "organization" field.
func OrganizationEQ(v string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldEQ(FieldOrganization, v))
}

// OrganizationNEQ applies the NEQ predicate on the "organization" field.
func OrganizationNEQ(v string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldNEQ(FieldOrganization, v))
}

// OrganizationIn applies the In predicate on the "organization" field.
func OrganizationIn(vs ...string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldIn(FieldOrganization, vs...))
}

// OrganizationNotIn applies the NotIn predicate on the "organization" field.
func OrganizationNotIn(vs ...string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldNotIn(FieldOrganization, vs...))
}

// OrganizationGT applies the GT predicate on the "organization" field.
func OrganizationGT(v string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldGT(FieldOrganization, v))
}

// OrganizationGTE applies the GTE predicate on the "organization" field.
func OrganizationGTE(v string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldGTE(FieldOrganization, v))
}

// OrganizationLT applies the LT predicate on the "organization" field.
func OrganizationLT(v string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldLT(FieldOrganization, v))
}

// OrganizationLTE applies the LTE predicate on the "organization" field.
func OrganizationLTE(v string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldLTE(FieldOrganization, v))
}

// OrganizationContains applies the Contains predicate on the "organization" field.
func OrganizationContains(v string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldContains(FieldOrganization, v))
}

// OrganizationHasPrefix applies the HasPrefix predicate on the "organization" field.
func OrganizationHasPrefix(v string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldHasPrefix(FieldOrganization, v))
}

// OrganizationHasSuffix applies the HasSuffix predicate on the "organization" field.
func OrganizationHasSuffix(v string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldHasSuffix(FieldOrganization, v))
}

// OrganizationEqualFold applies the EqualFold predicate on the "organization" field.
func OrganizationEqualFold(v string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldEqualFold(FieldOrganization, v))
}

// OrganizationContainsFold applies the ContainsFold predicate on the "organization" field.
func OrganizationContainsFold(v string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldContainsFold(FieldOrganization, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldLTE(FieldVersion, v))
}

// SpecDigestEQ applies the EQ predicate on the "spec_digest" field.
func SpecDigestEQ(v string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldEQ(FieldSpecDigest, v))
}

// SpecDigestNEQ applies the NEQ predicate on the "spec_digest" field.
func SpecDigestNEQ(v string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldNEQ(FieldSpecDigest, v))
}

// SpecDigestIn applies the In predicate on the "spec_digest" field.
func SpecDigestIn(vs ...string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldIn(FieldSpecDigest, vs...))
}

// SpecDigestNotIn applies the NotIn predicate on the "spec_digest" field.
func SpecDigestNotIn(vs ...string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldNotIn(FieldSpecDigest, vs...))
}

// SpecDigestGT applies the GT predicate on the "spec_digest" field.
func SpecDigestGT(v string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldGT(FieldSpecDigest, v))
}

// SpecDigestGTE applies the GTE predicate on the "spec_digest" field.
func SpecDigestGTE(v string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldGTE(FieldSpecDigest, v))
}

// SpecDigestLT applies the LT predicate on the "spec_digest" field.
func SpecDigestLT(v string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldLT(FieldSpecDigest, v))
}

// SpecDigestLTE applies the LTE predicate on the "spec_digest" field.
func SpecDigestLTE(v string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldLTE(FieldSpecDigest, v))
}

// SpecDigestContains applies the Contains predicate on the "spec_digest" field.
func SpecDigestContains(v string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldContains(FieldSpecDigest, v))
}

// SpecDigestHasPrefix applies the HasPrefix predicate on the "spec_digest" field.
func SpecDigestHasPrefix(v string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldHasPrefix(FieldSpecDigest, v))
}

// SpecDigestHasSuffix applies the HasSuffix predicate on the "spec_digest" field.
func SpecDigestHasSuffix(v string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldHasSuffix(FieldSpecDigest, v))
}

// SpecDigestEqualFold applies the EqualFold predicate on the "spec_digest" field.
func SpecDigestEqualFold(v string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldEqualFold(FieldSpecDigest, v))
}

// SpecDigestContainsFold applies the ContainsFold predicate on the "spec_digest" field.
func SpecDigestContainsFold(v string) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldContainsFold(FieldSpecDigest, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.FieldNotNull(FieldCreatedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WorkflowVersion) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WorkflowVersion) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WorkflowVersion) predicate.WorkflowVersion {
	return predicate.WorkflowVersion(sql.NotPredicates(p))
}
