// Code generated by ent, DO NOT EDIT.

package authoauthstate

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the authoauthstate type in the database.
	Label = "auth_oauth_state"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOrganization holds the string denoting the organization field in the database.
	FieldOrganization = "organization"
	// FieldStateHash holds the string denoting the state_hash field in the database.
	FieldStateHash = "state_hash"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldConsumedAt holds the string denoting the consumed_at field in the database.
	FieldConsumedAt = "consumed_at"
	// Table holds the table name of the authoauthstate in the database.
	Table = "auth_oauth_states"
)

// Columns holds all SQL columns for authoauthstate fields.
var Columns = []string{
	FieldID,
	FieldOrganization,
	FieldStateHash,
	FieldExpiresAt,
	FieldConsumedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the AuthOAuthState queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOrganization orders the results by the organization field.
func ByOrganization(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrganization, opts...).ToFunc()
}

// ByStateHash orders the results by the state_hash field.
func ByStateHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStateHash, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByConsumedAt orders the results by the consumed_at field.
func ByConsumedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConsumedAt, opts...).ToFunc()
}
